### ISSUE TITLE
difficulties with pplacer in CheckM.

### ISSUE THREAD

**Issue by itiago** [Ecogenomics/CheckM#101]
I cannot use CheckM since it cannot "find" pplacer...

I have downloaded pplacer-Linux-v1.1.alpha17.zip, unziped and runned : "python setup.py install"
then set path:

sudo nano /etc/bash.bashrc
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

sudo nano /home/igor/.bashrc
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

sudo nano /etc/profile

export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer/scripts
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

THEN runned CheckM:

"igor@ubuntu:~/metaBAT/bin/AC3_ANVIo_metaBat_bining/CheckM_results$ checkm lineage_wf -x fa /home/igor/metaBAT/bin/AC3_ANVIo_metaBat_bining /home/igor/metaBAT/bin/AC3_ANVIo_metaBat_bining/CheckM_results/

[CheckM - tree] Placing bins in reference genome tree.

Identifying marker genes in 45 bins with 1 threads:
Finished processing 45 of 45 (100.00%) bins.
Saving HMM info to file.

Calculating genome statistics for 45 bins with 1 threads:
Finished processing 45 of 45 (100.00%) bins.

Extracting marker genes to align.
Parsing HMM hits to marker genes:
Finished parsing hits for 45 of 45 (100.00%) bins.
Extracting 43 HMMs with 1 threads:
Finished extracting 43 of 43 (100.00%) HMMs.
Aligning 43 marker genes with 1 threads:
Finished aligning 43 of 43 (100.00%) marker genes.

[Error] Make sure pplacer is on your system path.

Controlled exit resulting from an unrecoverable error or warning. "

Could you please help?
Thank you

**Comment by dparks1134** [comment]
You need to put <code>pplacer</code> on your system path. You can find detailed information on how to do this at:
http://www.troubleshooters.com/linux/prepostpath.htm

**Comment by itiago** [comment]
Hi 
but I did: I added:

this:
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/pplacer
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/guppy
export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/rppr

to the three files: bash.bashrc, .bashrc, profile
by editing them using:

sudo nano /etc/bash.bashrc
sudo nano /home/igor/.bashrc
sudo nano /etc/profile

isn't this the correct way to do it?
Thanks

**Comment by dparks1134** [comment]
Hello. You need to log in and out of your terminal for the <code>.bashrc</code> script to be re-executed. Once <code>pplacer</code> is correctly on your path, you will be able to type <code>pplacer -h</code> to bring up its help menu.

**Comment by itiago** [comment]
Hi, if I do that, nothing happens, If I go to pplacer folder the same, but if I write ./pplacer -h it gives me the menu. I don't think i was able to install pplacer. I've runned the "python setup.py install" command on the pplacer/scripts folder, but still.....
Could you please advise me on how to install pplacer properly?
Thanks

**Comment by dparks1134** [comment]
I think the problem is that your system path should only point to the directory containing pplacer and not the executable file itself. Try adding the following to your <code>.bashrc</code> file:
`export PATH=$PATH:/home/igor/CheckM/pplacer-Linux-v1.1.alpha17/`

Remember that you need reload your <code>.bashrc</code> file before this will take effect. Easiest way to do this is to simply log off your system and log back in.

**Comment by itiago** [comment]
THANK YOU!
CheckM was able to fetch pplacer! waiting for results ;)

Appreciated your help!
Best

**Comment by dparks1134** [comment]
Excellent. Glad it is working!
