### ISSUE TITLE
problem reading results from lineage_wf command

### ISSUE THREAD

**Issue by itiago** [Ecogenomics/CheckM#102]
Hi
How can I know if my bins are correct or not, if there is a contamination, the classification...
Resuming I don't get the files that Checkm provides. Is there a table where this values are provided?
(I already went to Wiki page)
Thanks for any help
Best

**Comment by dparks1134** [comment]
Hello. I'm not sure I follow your question. The <code>lineage_wf</code> command prints a table to the console indicating completeness and contamination estimates along with other information. Further information can be obtained using the <code>qa</code> command:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

**Comment by itiago** [comment]
Hi, first thank you for your availability!
 yes is true, on shell I can see that table, but in results folder I don't seem to find it, is there a command that we need to write so that is printed?
And is there a place where a explanation for the results exist? for instance, what is the threshold for the contamination? and what is strain heterogeneity? I have bins with 0.41 in contamination and  66.67 in strain heterogeneity. and what is the 0, 1, 2, 3, 4, 5+? Is the number of different copies found for a marker gene?
Thank you for any feedback
best

**Comment by dparks1134** [comment]
Hello. Information about the usage of CheckM, generation of different output files, and how to interpret them can be found on the CheckM wiki:
https://github.com/Ecogenomics/CheckM/wiki

In particular, take a look at the "qa" command:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

The CheckM manuscript also contains information on how specific values are determined:
http://genome.cshlp.org/content/25/7/1043

Cheers,
Donovan

**Comment by itiago** [comment]
Thanks Donovan, will do!
best

**Comment by nixon444** [comment]
Sorry if I missed something here, I am familiar with the "qa" command, and the workflows that incorporate it, but is there no way of asking checkm to save the same table it pronts as a .txt or .tsv (or similar) file? Currently having to screen grab the tables it prints and manually entering the results into a spreadsheet. I figure there must be a way to ask the tool to do this for me? If so, what exactly do I need to tell it using either the "qa" or "lineage_wf" commands?

Cheers!

**Comment by dparks1134** [comment]
Yes - results can be written to file. Take a look at the `--file` and `--tab_table` flags.
