### ISSUE TITLE
Getting Strain heterogeneity

### ISSUE THREAD

**Issue by ariahahn** [Ecogenomics/CheckM#103]
Hi - great software.

Initially a report it output to screen:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id                                      Marker lineage           # genomes   # markers   # marker sets   0    1    2   3   4   5+   Completeness   Contamination   Strain heterogeneity  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  GCF_000003135.1   f__Bifidobacteriaceae (UID1462)       65         476           217        0   476   0   0   0   0       100.00           0.00               0.00          
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I can recover most these numbers from other outputs ("bin_stats_ext.tsv") but where do I find Strain heterogeneity? Essentially I would like to try recreate the table above from the other outputs (as we did not pipe to a file).

Thanks!

**Comment by dparks1134** [comment]
You can regenerate the output using the <code>qa</code> command. Certainly no need to pull out the data manually or rerun the full analyses. 

E.g.,
> checkm --tab_table -f qa.o2.tsv -o 2 ./output/lineage.ms ./output

where "output" is the directory with the CheckM results from running the <code>lineage_wf</code> command.

**Comment by ariahahn** [comment]
That's great! Thanks!
