### ISSUE TITLE
Change "strain heterogeneity" column name

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/CheckM#104]
This is a bit of a confusing column name since it doesn't measure true strain heterogeneity. Daan suggested "Contamination with AAI>90%" which captures what is actually measured and clarifies that it is a proportion of all contamination.

**Comment by Devadas07** [comment]
hai sir 
what does strain heterogeneity values represent in the results? what it means if 100 is the strain heterogeneity and what it means if it is other than 100 if some value is there.
I am little confused with whether the contamination is from different species or from same species.

**Comment by dparks1134** [comment]
100 means all the marker genes found two or more times are very similar to each other (default: >90% AAI). This implies the source of the contamination is one or more highly similar organisms. A value of 0 would indicate that all the reported contaminated is from more distantly related organisms (i.e. <90% AAI between duplicates marker genes). Values in between scale between these two extreme cases.

**Comment by dparks1134** [comment]
Still less than ideal, but grandfathering this label at this point.
