### ISSUE TITLE
Cannot run checkm, error after missing files

### ISSUE THREAD

**Issue by itiago** [Ecogenomics/CheckM#105]
Dear Donovan
This is very strange, since I already run successfully checkm, I'm using a different set of bins, but I always have this error, could you please help me on this one?
Thank you
Best

igor@ubuntu:~/AC3_Binning_MyCC$ checkm lineage_wf -x fasta /home/igor/AC3_Binning_MyCC/ /home/igor/AC3_Binning_MyCC/checkm_results/

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 52 bins with 1 threads:
    Finished processing 52 of 52 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 52 bins with 1 threads:
    Finished processing 52 of 52 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 52 of 52 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 52 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("/home/igor/AC3_Binning_MyCC/checkm_results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/home/igor/AC3_Binning_MyCC/checkm_results/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:18:06.705 || Total: 0:18:06.705 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 52 of 52 (100.00%) bins.

  Determining marker sets for each genome bin.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1245, in parseOptions
    self.lineageSet(options)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 230, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/usr/local/lib/python2.7/dist-packages/checkm/treeParser.py", line 477, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/usr/local/lib/python2.7/dist-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/usr/local/lib/python2.7/dist-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/home/igor/AC3_Binning_MyCC/checkm_results/storage/tree/concatenated.tre'
igor@ubuntu:~/AC3_Binning_MyCC$

**Comment by dparks1134** [comment]
It appears you are running out of memory. If you can run CheckM on a
machine with more memory, that would be best. Otherwise, you can try the
reduce_tree flag:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
