### ISSUE TITLE
Using CheckM for fungal de-novo assemblies?

### ISSUE THREAD

**Issue by MichaelFokinNZ** [Ecogenomics/CheckM#106]
Would you recommend using CheckM for Eukaryotic microorganisms?

**Comment by dparks1134** [comment]
CheckM is specific to Bacteria and Archaea. I would suggest looking at BUSCO for this purpose:
http://busco.ezlab.org/

**Comment by Buuntu** [comment]
Is there a comparison of checkM vs BUSCO for bacterial genomes?  I've used BUSCO with pretty good results in the past, how is checkM better?

**Comment by dparks1134** [comment]
I don't know of any direct comparison. CheckM aims to use marker genes that are tailored to specific bacterial and archaeal lineages in order to improve quality estimates.
