### ISSUE TITLE
IO error for taxon_marker_sets

### ISSUE THREAD

**Issue by epulo5** [Ecogenomics/CheckM#110]
I've recently installed checkm and am getting an IO error for the taxon marker sets when following the taxon-specific workflow instructions. Even `checkm taxon_list --rank phylum` produces this error. 

Do I need to download additional scripts? I followed the wiki instructions [https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm](url) for installing checkm.

**Comment by dparks1134** [comment]
Can you send me the output produced by CheckM? No additional scripts are
needed.

**Comment by epulo5** [comment]
Thank you for getting back to me. See below.

> checkm taxon_list --rank phylum

*******************************************************************************
 [CheckM - taxon_list] Listing available taxonomic-specific marker sets.
*******************************************************************************

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/home/francine/anaconda3/envs/py27/bin/checkm", line 712, in
<module>
    checkmParser.parseOptions(args)
  File
"/home/francine/anaconda3/envs/py27/lib/python2.7/site-packages/checkm/main.py",
line 1225, in parseOptions
    self.taxonList(options)
  File
"/home/francine/anaconda3/envs/py27/lib/python2.7/site-packages/checkm/main.py",
line 241, in taxonList
    taxonParser.list(options.rank)
  File
"/home/francine/anaconda3/envs/py27/lib/python2.7/site-packages/checkm/taxonParser.py",
line 55, in list
    taxonMarkerSets = self.readMarkerSets()
  File
"/home/francine/anaconda3/envs/py27/lib/python2.7/site-packages/checkm/taxonParser.py",
line 40, in readMarkerSets
    for line in open(DefaultValues.TAXON_MARKER_SETS):
IOError: [Errno 2] No such file or directory:
u'/home/francine/taxon_marker_sets.tsv'

**Comment by dparks1134** [comment]
Hello. It appears CheckM is  having trouble finding the file <code>taxon_marker_sets.tsv</code>. This is part of the CheckM precalculated data files which you must install on your system and point CheckM to:
https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

Please let me know  if this doesn't resolve the issue.

**Comment by epulo5** [comment]
Problem resolved. Thanks!
