### ISSUE TITLE
CheckM does not recognized file format

### ISSUE THREAD

**Issue by hudenise** [Ecogenomics/CheckM#111]
Hi,
I'm new to CheckM and tried to run it to assess the quality of bins produced by MaxBin. There is 14 bins in fasta format. I tried:
checkm lineage_wf -t 8 -x fasta maxbin  CheckM
it recognizes the 14 bins but then at the first step CheckM - tree:
Identifying marker genes in 14 bins with 8 threads:
    Finished processing 0 of 14 (0.00%) bins.
Error: Unrecognized format, trying to open hmm file /tmp/c57d5483-bc83-4151-8950-13fb179eee28 for reading.
I've tried to change the file format to fna with no progress.
Is it something I missed from the quick start or workflows?

Same error when using metawatt to bin the contigs
Thanks for your help

**Comment by dparks1134** [comment]
This appears to be something incompatible with your system setup. Can you verify that you have HMMER >=3.1b1 and have installed the CheckM data files as described here:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements

**Comment by hudenise** [comment]
My bad, I've pointed it to HMMR 3.0. Thanks for the quick answer

**Comment by dparks1134** [comment]
Issue was related to HMMER version.
