### ISSUE TITLE
https://data.ace.uq.edu.au/ is not reachable

### ISSUE THREAD

**Issue by karchern** [Ecogenomics/CheckM#113]
Hello,

this might be a temporary issue or an issue with my network, but i cannot reach the data under https://data.ace.uq.edu.au/. My machine does not appear to be the problem, as other machines in my network are also not able to reach the domain.

Cheers,
Nic

**Comment by dparks1134** [comment]
Hello Nic,

Our server is offline until sometime tomorrow. Sorry for the inconvenience. 

Cheers,
Donovan

**Comment by dparks1134** [comment]
Temporary issue that is resolved.
