### ISSUE TITLE
recursion depth reached

### ISSUE THREAD

**Issue by karchern** [Ecogenomics/CheckM#118]
Hi,

I've been using checkm recently without problems. Currently, I am trying to evaluate around 4000 bins (size around 3 mbps each) using the standard checkm lineage_wf command, like so:

checkm lineage_wf -t 12 -x fa BIN_FOLDER OUTPUT_FOLDER

I am getting the following error:
RuntimeError: maximum recursion depth exceeded while calling a Python object

At the moment, I cannot give you the full error log as my tmux session has a very small scrollback buffer... I will update this issue as soon as I was able to reproduce and capture stderr.

In the meantime, are there are any suspicions what could cause this?

Thanks!

**Comment by dparks1134** [comment]
Hello. I've never encountered a recursion depth issue. However, unless you have a lot of memory on your machine it is usually better to process genomes in smaller batches. I typically do 1000 genomes at a time.

https://github.com/Ecogenomics/CheckM/wiki/Bugs-and-Feature-Requests#processing-large-numbers-of-genomes

**Comment by karchern** [comment]
Hi,
your approach allowed me to process my bins. Thanks!

**Comment by nick-youngblut** [comment]
I've encountered this issue too with ~20000 bins. While the proposed solution can work, it still leaves an upper limit on the number of bins that checkM can handle, without the user knowing how many that is until after a lot of time/computation. It may be good to at least include a warning if the user provides a lot of bins.

**Comment by ggautreau** [comment]
@nick-youngblut 
If you add ```sys.setrecursionlimit(20000)``` in the code of checkM does it fix you issue ?

https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it

**Comment by nick-youngblut** [comment]
Thanks @ggautreau for the suggestion, but no, that doesn't fix the problem

**Comment by matrs** [comment]
I just tried to process 2300 genomes and found this error. The problem is that this triggers when  many files have been processed and as far i can tell there isn't a restart option.  I don't think the problem is related to memory (because the wiki  refers to that specifically). It would very useful if this is mentioned in the wiki.

I'm using `v1.1.3`
