### ISSUE TITLE
Plotting .tre file 

### ISSUE THREAD

**Issue by BojkArth** [Ecogenomics/CheckM#119]
Hi, I am running a bunch of metagenomic bins through checkm. I use lineage_wf and would like to build a tree that places my bins in a tree with reference genomes. The only output file that contains the reference genomes is the concatenated.tre file. It's probably me, but I am unable to process this with a toolbox like ete3. 

I would also be happy to calculate the tree myself, but concatenated.fasta only has my own genomic bins. 

Does anyone know how to get a tree in newick format, or an aligned .fasta/faa file that contains the reference sequences?

Thanks
bojk

**Comment by dparks1134** [comment]
Hello bojk,

The aligned reference sequences are part of the CheckM reference data. It will be in the directory <checkm_data>/genome_tree/genome_tree_full.refpkg. The file you are after is genome_tree.fasta. The concatenated.tre file is viewable in Dendroscope and is in Newick format. I'm not sure why this doesn't work with ete3. You can also get other Newick tree representations using "checkm tree_qa" as described here (in particular, output formats 3 and 4):
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#tree_qa

Cheers,
Donovan
