### ISSUE TITLE
possible to get ssu_finder without seq_file?

### ISSUE THREAD

**Issue by Kirk3gaard** [Ecogenomics/CheckM#123]
Hi

It would be great if it was possible to use ssu_finder without the seq_file and just provide the bin_folder. The sequences will be in the bin_folder anyway? Or am I missing something.

ssu_finder - identify SSU (16S/18S) rRNAs in sequences

**Comment by dparks1134** [comment]
Hello. The command uses the sequences used to generate the bins so it can identify 16S rRNA sequences that may not have been binned. It only uses the bins themselves to determine if 16S rRNA sequence appears in a bin or not. If you aren't interested in unbinned 16S sequences you can concatenated together all your bins and use this as the seq_file.

**Comment by Kirk3gaard** [comment]
Thanks for the reply. That sounds like a cool option. I will remember that if I encounter a bin without a 16S sequence. Great suggeestion.
