### ISSUE TITLE
change tsv format?

### ISSUE THREAD

**Issue by Kirk3gaard** [Ecogenomics/CheckM#124]
Hi

I have had a look at the current  tsv output and it looks a bit funky example of bin_stats.tree.tsv:
Streptococcus	{'Translation table': 11, 'GC std': 0.02256571402016602, '# ambiguous bases': 0, 'Genome size': 1705195, 'Longest contig': 128731, 'N50 (scaffolds)': 32139, 'Mean scaffold length': 22436.776315789473, '# contigs': 76, '# scaffolds': 76, '# predicted genes': 1755, 'Longest scaffold': 128731, 'GC': 0.4049941502291527, 'N50 (contigs)': 32139, 'Coding density': 0.8815068071393595, 'Mean contig length': 22436.776315789473}
Ecoli	{'Translation table': 11, 'GC std': 0.0, '# ambiguous bases': 0, 'Genome size': 4633976, 'Longest contig': 4633976, 'N50 (scaffolds)': 4633976, 'Mean scaffold length': 4633976.0, '# contigs': 1, '# scaffolds': 1, '# predicted genes': 4315, 'Longest scaffold': 4633976, 'GC': 0.5078274035083479, 'N50 (contigs)': 4633976, 'Coding density': 0.8742011180032007, 'Mean contig length': 4633976.0}

Is it possible to change the tsv outputs to something with a header and tab separated values? e.g.
bin\tTranslation table\tGC std\t# ambiguous bases\tGenome size\tLongest contig\tN50 (scaffolds)\tMean scaffold length\t# contigs\t# scaffolds\t# predicted genes\tLongest scaffold\tGC\tN50 (contigs)\tCoding density\tMean contig length
Streptococcus\t11\t0.02256571402016602\t0\t1705195\t128731\t32139\t22436.776315789473\t76\t76\t1755\t128731\t0.4049941502291527\t32139\t0.8815068071393595\t22436.776315789473
Ecoli\t11\t0.0\t0\t4633976\t4633976\t4633976\t4633976.0\t1\t1\t4315\t4633976\t0.5078274035083479\t4633976\t0.8742011180032007\t4633976.0

**Comment by dparks1134** [comment]
Hello. This file isn't meant to be human readable. The information in this file (and more!) should be available through CheckM's "qa" command where it can be displayed on screen as a table or stored in a more sensible file format.

https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

**Comment by Kirk3gaard** [comment]
Thanks for the reply. That sounds sensible.
