### ISSUE TITLE
checkm initialize inquery

### ISSUE THREAD

**Issue by camel315** [Ecogenomics/CheckM#128]
@wwood I have a question related to checkm database initialization. When I use checkm-genome, one step of checkm intialization needs to download the  checkm_data_16012015_v0.9.7.tar.gz. In case of multiple samples, I was wondering whether this step could be done only once, without doing this process in each run, for our computing nodes in the cluster has no external internet connection due to security reasons, only the head node have the connection. After I decompress manually the database, the database will be removed but could not download again.
In addition, I noticed that the latest version of checkm still require python<3.0. Will this could caused problem in download under python3.5?
Thank you.

**Comment by dparks1134** [comment]
Hello. The setup for CheckM is only meant to be performed once. This includes downloading the CheckM data. You can find installation instructions at:
https://github.com/Ecogenomics/CheckM/wiki/Installation
