### ISSUE TITLE
tree_qa fail with multiple bins placed outside Bacteria or Archaea

### ISSUE THREAD

**Issue by hexaquo** [Ecogenomics/CheckM#130]
Hi Donovan,

I have run into a problem when I run checkM on a set of somewhat redundant bins that aren't placed into one of the two domains (may be novel, partial CPR bins).

I can fix the problem if I run checkm tree, replace "UID1||" with UID1|root|" in the concatenated.tre file produced from checkm tree and then proceed with tree_qa

Will attach concatenated.tre. Let me know if I need to also send you the bins to fully reproduce the error. 

Thanks!
Craig Herbold

checkm lineage_wf genomeDir outDir -t 8 --pplacer_threads 8 -x fa

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 7 bins with 8 threads:
    Finished processing 7 of 7 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 7 bins with 8 threads:
    Finished processing 7 of 7 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 7 of 7 (100.00%) bins.
  Extracting 43 HMMs with 8 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 8 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 7 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:05:39.136 || Total: 0:05:39.136 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 7 of 7 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 1 of 7 (14.29%) bins (current: maxbin-bins.prob0.45.marker107.026).
Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/apps/checkm/1.0.7/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/apps/checkm/1.0.7/lib/python2.7/site-packages/checkm/main.py", line 1245, in parseOptions
    self.lineageSet(options)
  File "/apps/checkm/1.0.7/lib/python2.7/site-packages/checkm/main.py", line 230, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/apps/checkm/1.0.7/lib/python2.7/site-packages/checkm/treeParser.py", line 515, in getBinMarkerSets
    domainNode = self.__findDomainNode(node)
  File "/apps/checkm/1.0.7/lib/python2.7/site-packages/checkm/treeParser.py", line 244, in __findDomainNode
    if curNode.label:
AttributeError: 'NoneType' object has no attribute 'label'

[concatenated.tre.gz](https://github.com/Ecogenomics/CheckM/files/1579626/concatenated.tre.gz)

**Comment by dparks1134** [comment]
Hello Craig,

This bug **may** be fixed in CheckM v1.0.8. However, this might also be a similar, but unrelated bug. If you can send me your bins I can investigate further (donovan.parks [at] gmail [dot] com).

Cheers,
Donovan

**Comment by dparks1134** [comment]
Fixed in CheckM v1.0.9.
