### ISSUE TITLE
'checkm data update' fails

### ISSUE THREAD

**Issue by jmtsuji** [Ecogenomics/CheckM#132]
Running `checkm data update` on an existing CheckM database fails with the following error:

```
*******************************************************************************
 [CheckM - data] Check for database updates. [update]
*******************************************************************************

Connecting to ACE server.

Error: failed to connect to server.

You can download the required data files manually form:
  https://data.ace.uq.edu.au/public/CheckM_databases/

Uncompress the data files to a directory of your choice,
then run 'checkm data setRoot' to specify the location
of the data files.
```

I inserted two `print` statements in the CheckM code (`manifestManager.py` try/catch statement, lines ~123-125) to debug where the error occurs. Modified code for debugging:

```
        try:
            print "sourceManifestLocation: " + sourceManifestLocation
            print "sourceManifestName: " + sourceManifestName
            s_man = urllib2.urlopen(sourceManifestLocation + "/" + sourceManifestName, None, self.timeout)
            source = sourceManifestLocation + "/"
```

Output:
```
sourceManifestLocation: https://data.ace.uq.edu.au/public/CheckM_databases/
sourceManifestName: .dmanifest
```

This implies that CheckM attempts to download https://data.ace.uq.edu.au/public/CheckM_databases/.dmanifest to compare database versions with the local database. However, the above URL does not work on my machine. Running `wget https://data.ace.uq.edu.au/public/CheckM_databases/.dmanifest` generates a `404 Not Found` error. I can successfully download other files in https://data.ace.uq.edu.au/public/CheckM_databases, however, implying that this is not a firewall issue.

Is the URL pointing to the wrong location for the .dmanifest file when `checkm data update` is run?

**Comment by dparks1134** [comment]
That latest version of CheckM v1.0.10 removes this functionality as users have been having difficulties. This data can be downloaded directly and CheckM configured to use it:
https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

**Comment by jmtsuji** [comment]
Good to know -- thanks for the quick response.
