### ISSUE TITLE
can't run checkm tetra 

### ISSUE THREAD

**Issue by novitch** [Ecogenomics/CheckM#133]
Hello,
I'm in trouble with checkm tetra. 
I want to run checkm outliers to identify outliers sequences in my bins but if I'm correct I need to run checkm tetra

I tried different ways:
checkm tetra [fasta file] [output file] -t 8
checkm tetra [directory of fasta files] [output file] -t 8

Here is the log of my error:

*******************************************************************************
 [CheckM - tetra] Calculating tetranucleotide signature of sequences.
*******************************************************************************

  Determining tetranucleotide signature of each sequence.

Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/mnt/gpfs/pt2/ama/CheckM/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/lib/python2.7/site-packages/checkm/main.py", line 1289, in parseOptions
    self.tetraSignatures(options)
  File "/usr/lib/python2.7/site-packages/checkm/main.py", line 914, in tetraSignatures
    tetraSig.calculate(options.seq_file, options.output_file)
  File "/usr/lib/python2.7/site-packages/checkm/genomicSignatures.py", line 157, in calculate
    workerQueue = mp.Queue()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

Can you help me please? I'm using ...::: CheckM v1.0.7 :::...

Thanks,

**Comment by dparks1134** [comment]
Hello. The error "Permission denied" suggest your operating system doesn't like what CheckM is trying to do. The most likely cause of this would be trying to create a file where you don't have permission to do so. If you are looking to identify contamination in your genomes, you might be interested in our companion tool RefineM:
https://github.com/dparks1134/RefineM

**Comment by novitch** [comment]
Ok, I am pretty sure that I have all the permissions in the folder I have created, but I'm wondering if checkM is trying to create temp files in a place that I don't know with no right. Anyway, I will try your new pipeline, if you think it is more adapted. Thanks,

**Comment by dparks1134** [comment]
Very odd. The "checkm tetra" command doesn't make use of any temporary files.

**Comment by dparks1134** [comment]
Closed due to inactivity.
