### ISSUE TITLE
checkM tree_qa newick trees in wrong format

### ISSUE THREAD

**Issue by celiosantosjr** [Ecogenomics/CheckM#134]
I am running checkM tree and tree_qa to obtain an idea of the taxa insertion high of my bins. But, when I run the commands all works and generate files that I cannot use in any tree rendering software. They all say the format is wrong. Reading in the internet, I discovered that the format really is wrong but the changes suggested by them:

perl -pe "s/;/\+/g" tree_tax.nwk | perl -pe "s/\+\n/;\n/g" > tree_tax.fixed.nwk

Still does not work, since the taxa names do not appear in the final tree. Thank you in advance.

**Comment by dparks1134** [comment]
What specifically is wrong with the current format? I view the trees in Dendroscope.

**Comment by dparks1134** [comment]
Closed due to inactivity.
