### ISSUE TITLE
Interpreting Contamination Percentage in lineage_wf

### ISSUE THREAD

**Issue by lowandrew** [Ecogenomics/CheckM#135]
Hello,

I've been using CheckM on some simulated data to try and get a handle on how well it's detecting contamination in _E. coli_, and I'm not sure exactly how to interpret the contamination percentage. I've been creating read mixes of different _E. coli_ serotypes with known levels of contamination (between 1 and 20 percent) and assembling with SPAdes, and using CheckM on the resulting assembly to check for contamination. In every case some level of contamination is reported, but it's generally very low (less than 1.5 percent), with many hovering around 0.3 percent, which is the same level that I get when I put in a RefSeq genome such as O157 Sakai (NC\_002695.1).

Given that I'm getting roughly the same levels for both contaminated and clean data, my question is if you have any sort of hard cutoff for contamination percentage where we can definitively call a sample contaminated, or if it's more up to interpretation and perhaps lineage-specific - in Table 3 of your paper it says anything under 5 percent can be considered low contamination; if we had to have some sort of cutoff, would that perhaps be good?

Hopefully that all makes sense, let me know if you need any clarification.

Thanks!

**Comment by dparks1134** [comment]
How complete are the genomes? I would expect that if the genomes you are assembling contains the complete genome of the E.coli serotype PLUS additional contigs that are contamination, then CheckM should be reporting this with reasonable accuracy (say, +/-3%). On the other hand, if the E.coli serotype is largely incomplete and/or the contamination isn't actually assembling into contigs, then the picture is far less clear. In particular, not that an assembly that represents <50% of a genome with contamination will be underreported by CheckM. This is a known limitation and is discussed in the Supp. Material of the CheckM manuscript and this blog post:
https://www.microbe.net/2017/12/13/why-genome-completeness-and-contamination-estimates-are-more-complicated-than-you-think/

**Comment by lowandrew** [comment]
Thanks for the quick response! The genomes are all showing a completeness of >99.5 percent, so the accuracy should be pretty good.  

This brings me back to the question of what to use as a cutoff for saying something is definitively contaminated. For example, when I mix serotype O157 with serotype O83, I get a contamination level of ~12 percent, which seems high enough that I can confidently say that sample is contaminated. On the other hand, a mix of serotype O111 and O139 at the same contamination level gets me a contamination level of only 1.5 percent, at which point I'm not sure whether or not I can say the sample is certainly contaminated, since this level is within the margin of error.

**Comment by dparks1134** [comment]
Very interesting. In general, I think of the CheckM estimates as a measure of the degree of contamination and not giving a binary yes/no answer to if there is contamination. At 1.5% estimated contamination, I would generally interpret this as very low or possibly no contamination. I would then look at what marker genes were identified multiple times and if I had multiple similar genomes see if the duplicated marker genes likely represent real gene duplication (given confidence that the genome is actually free of  contamination).

That said, your case sounds more like a verification of the CheckM approach. It is not at all clear to me why a mix of O157 and O83 would result in reasonable contamination estimates, while a mix of O111 and O139 would not. Can you verify that the resulting assembly from SPAdes has the level of contamination you are expecting? Is it possible that in the O111+O139 case the assembly is poor and the data that did assembly really is largely contamination free?

**Comment by lowandrew** [comment]
The assembly for the O111+O139 mix is actually a fair bit better than the assembly for the O157+O83 mix in terms of assembly metrics. I think I've mostly figured out what's going on - it looks like O157 and O83 are a fair bit more diverged than O111 and O39, and so the single-copy genes are for the most part the exact same in O111 and O39, enabling that mix to escape detection, while for O157 and O83 the single-copy genes are diverged enough that multiple copies show up in the assembly.

Thanks again!
