### ISSUE TITLE
Install up-to-date checkm via anaconda

### ISSUE THREAD

**Issue by snayfach** [Ecogenomics/CheckM#138]
Is there any way to get the latest checkm via anaconda? Currently only 1.0.7  is available which contains bugs:

```
$ conda list checkm
# packages in environment at /path/to/my/env:
#
checkm-genome             1.0.7                    py27_0    bioconda
```

Thanks,
Stephen

**Comment by dparks1134** [comment]
Hello Stephen. I don't use Anaconda and am pleasantly surprised to hear there is a CheckM package. Is there a way to determine who the maintainer of this package is and see if they can update it? Seems likely they make use of CheckM and would also be interested in using the latest version.

**Comment by mbargull** [comment]
Is on its way 😉: https://github.com/bioconda/bioconda-recipes/pull/7816

**Comment by snayfach** [comment]
Thanks, Marcel!

**Comment by dparks1134** [comment]
Great. Thanks Marcel!
