### ISSUE TITLE
LICENSE.txt missing

### ISSUE THREAD

**Issue by mbargull** [Ecogenomics/CheckM#139]
The readme reference a missing license file:
https://github.com/Ecogenomics/CheckM/blame/v1.0.11/README.md#L10
> Copyright © 2014 Donovan Parks, Connor Skennerton, Michael Imelfort. See LICENSE.txt for further details.

**Comment by dparks1134** [comment]
Thanks for pointing this out. License information has been added.

**Comment by mbargull** [comment]
Great, thanks!
