### ISSUE TITLE
Should use setuptools

### ISSUE THREAD

**Issue by mbargull** [Ecogenomics/CheckM#140]
CheckM uses `pkg_resources`, which is part of `setuptools`, to load resources:
https://github.com/Ecogenomics/CheckM/blob/v1.0.11/checkm/checkmData.py#L25.
Hence it should
* use `setuptools.setup`
  https://github.com/Ecogenomics/CheckM/blob/v1.0.11/setup.py#L1
  ```diff
  -from distutils.core import setup
  +from setuptools import setup
  ```
* require `setuptools` as an install requirement
  https://github.com/Ecogenomics/CheckM/blob/v1.0.11/setup.py#L24
  ```diff
  +        "setuptools",
  ```

**Comment by dparks1134** [comment]
Changed starting with v1.0.15.
