### ISSUE TITLE
checkm tree issue

### ISSUE THREAD

**Issue by qianjia** [Ecogenomics/CheckM#141]
Hello,

I run checkm test, it ended up with some errors like below

![1](https://user-images.githubusercontent.com/18143321/36536103-0bbd4aa6-17cc-11e8-9636-97c9185c490a.png)
Indeed, there is no file "concatenated.pplacer.json" in the corresponding directory

![2](https://user-images.githubusercontent.com/18143321/36536350-f2705fe2-17cc-11e8-95b9-6635aa461a9a.png)

I also tried my own dataset, add the -r flag since my RAM is 16 GB, while it turned out the same problem

![3](https://user-images.githubusercontent.com/18143321/36536721-4345eb20-17ce-11e8-99ff-d4f05c4b2f13.png)

Thanks for your time.

Best,
Jia

**Comment by dparks1134** [comment]
This usually indicates your system ran out of memory. You can find the system requirements at:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements

**Comment by qianjia** [comment]
Thanks for your reply, even if I set the --reduced_tree flag, it turned out the same problem (my RAM is 16GB). I have no idea why. Otherwise, is there any way to process the data in batches instead of all at once? Thanks.

**Comment by dparks1134** [comment]
Can you verify that you aren't running out of memory? Running the genomes one at a time instead of all 17 at once will have a very marginal impact on the amount of required memory.

**Comment by qianjia** [comment]
I think you are right, It ran out of memory. Appreciate your help.
