### ISSUE TITLE
Error trying to run "checkm" command

### ISSUE THREAD

**Issue by HTrew** [Ecogenomics/CheckM#142]
Hi,

I am having a problem getting started with CheckM. I am currently using a server that runs Ubuntu 16.04.3 LTS. I followed the instructions for installation [here](https://github.com/Ecogenomics/CheckM/wiki/Installation) (first installing HMMER, prodigal and pplacer (using conda) and then installing numpy and checkm using pip). 

However when I run the command "checkm" I get the following error:
  File "/usr/local/bin/checkm", line 58
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'

I'd really appreciate any help with this, thanks very much in advance!
Hannah

**Comment by dparks1134** [comment]
Hello Hannah,

CheckM must be run with Python 2.x. This error suggest you are using Python 3.x.

Cheers,
Donovan

**Comment by HTrew** [comment]
Hi Donovan,


Thanks very much for getting back to me. I have tried running the command "checkm" in a Python 2.7.14 environment (set according to the instructions here: https://conda.io/docs/user-guide/tasks/manage-python.html), however I get the same error message as before. Really sorry if I'm doing something stupid here, but it would be great to be able to use your program!


Thanks again,

Hannah

Managing Python — Conda documentation<https://conda.io/docs/user-guide/tasks/manage-python.html>
conda.io
Conda treats Python the same as any other package, so it is easy to manage and update multiple installations. Anaconda supports Python 2.7, 3.4, 3.5 and 3.6.



________________________________

**Comment by dparks1134** [comment]
Hello Hannah. Can you type "python -V" into your console to confirm that you are using Python 2.x and let me know the exact version you are using? It is likely that Python 3.x is still being run. I'm not familiar with Conda, but likely you need to explicitly indicate which version of Python you wish to use if you have multiple versions installed.

**Comment by HTrew** [comment]
Hi Donovan,


On logging in my system runs Python 3.6.4, but after changing the python environment using the conda instructions, the version of Python then switches to 2.7.14. However the error message from running "checkm" remains the same.


I've attached a screenshot to show you what I get. Maybe this is not the best way to alter Python environments...? I'm afraid I'm not particularly comfortable with Python!


Thanks again for your help on this,

Hannah



________________________________

**Comment by dparks1134** [comment]
I'm not sure what to recommend. My best guess is that CheckM was install into your Python 3.x installation and is still using Python 3.x. Your error message is very, very indicative of this being the issue. Perhaps try making Python 2.x the active version and then installing (or re-installing) CheckM.

**Comment by HTrew** [comment]
Thanks very much, looks like I'll have to get to grips with these Python environments.

Really appreciate your help!

Hannah

________________________________

**Comment by pbordron** [comment]
The conda recipe was updated and solve this issue

Philippe

**Comment by Buuntu** [comment]
I'm still getting this issue.  Do I still have to run it with python 2.*?
