### ISSUE TITLE
Taxonomic-specific Workflow for CheckM

### ISSUE THREAD

**Issue by 473021677** [Ecogenomics/CheckM#143]
Hello everyone. I am using CheckM to evaluate the completeness and contamiantion of the genomes with the taxonomic-specific workflow.  But I cann't get the species-specific marker sets using the command such as "checkm taxon_set <rank> <taxon> <marker file>". It report the errors such as "Unrecognized taxon: Acidithiobacillusferrooxidans (in rank species):" of "checkm: error: unrecognized arguments: Acidithiobacillus.ms" when I import the command "checkm taxon_set species Acidithiobacillus ferrooxidans Acidithiobacillus.ms". I don't know why?

**Comment by dparks1134** [comment]
Hello,

You can issue the command as follows:
> checkm taxonomy_wf species "Acidithiobacillus ferrooxidans" <your_bins> <output_dir>

Note the quotes around Acidithiobacillus ferrooxidans. This indicates that you want the two words Acidithiobacillus and ferrooxidans to be treated as a single command line parameter to the program. 

Cheers,
Donovan
