### ISSUE TITLE
checkm coverage misreporting contig length

### ISSUE THREAD

**Issue by cmfield** [Ecogenomics/CheckM#146]
For contigs longer than 1,966,020bp, checkm coverage reports that length rather than their actual length as seen in the tabular output.

**Comment by dparks1134** [comment]
I believe this is the longest outstanding issue for CheckM at over 4 years. Not great! :(

This issue has not been reported by others and I do not believe it to be a general issue. For the NCBI Assembly GCF_003697165.2, CheckM reports the genome size as 5,034,834 in agreement with the size reported at NCBI:
https://www.ncbi.nlm.nih.gov/assembly/GCF_003697165.2/

![e_coli_checkm_qa2](https://user-images.githubusercontent.com/3688336/162625311-17632ca9-24bd-411b-89e9-39ce084d73d8.png)
