### ISSUE TITLE
Error finding data folder

### ISSUE THREAD

**Issue by micromania2** [Ecogenomics/CheckM#147]
Hi, 

I am entering the following command...

checkm lineage_wf -t 32 -x fa /ngs/switchgrass_Jan2018/raw/switchgrass_bin /ngs/switchgrass_Jan2018/raw/switchgrass_bin_checkm

and getting the following error. As you can see it has joined the two folder paths together. 

IOError: [Errno 2] No such file or directory: u'/ngs/switchgrass_Jan2018/raw/ngs/switchgrass_Jan2018/raw/checkm_data/hmms/phylo.hmm'

In addition, this is not the path where I set my data folder. Is there  a way to reset my data folder path?

Thanks!

**Comment by dparks1134** [comment]
Hello. You can set the path with: `checkm data setRoot`.
