### ISSUE TITLE
hmmer.analyze.txt missing during lineage_wf

### ISSUE THREAD

**Issue by thatcatlooksstrong** [Ecogenomics/CheckM#149]
Hello,

I am trying to calculate coverage and contamination for a folder of bins. I am sending commands to a server that runs on Redhat (Linux)

I used the command
 checkm lineage_wf -x fa /[path]/SAGBINS  /[path]/SAGBINS/results
Where the bins are .fa (fasta) format.

I got the output: [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/results/bins/bin1/hmmer.analyze.txt'
[Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/results/bins/bin3/hmmer.analyze.txt'
[Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/results/bins/bin2/hmmer.analyze.txt'

And got told that no marker genes were found.
I tested the command with a folder of bins I was previously able to get completion estimates for, and got the same result.

I checked and Hmmer is installed on the server. I did not change the settings.

**Comment by dparks1134** [comment]
Hello. For the set of bins that worked previously for you, are you still getting the expected result or are is the same error occurring? Which version of HMMER is on the system?

**Comment by thatcatlooksstrong** [comment]
I am getting data on contig length but not for completeness (all values are zero).

hmmpfam -h returns version 2.3
hmmsearch -h returns version 2.3 as well.

However, the program files folder says the version of hmmer is 3.1.
I am unsure what is causing it to revert to an older version.

**Comment by dparks1134** [comment]
CheckM uses the version of HMMER you have on your system path. This needs to be >=3.1b1.

**Comment by thatcatlooksstrong** [comment]
I checked and HMMER seems to be in my path (I added the entire program files folder to my path). The problem is that it calls up a previous iteration.

This is part of the error I get:

 Finished processing 1 of 3 (33.33%) bins.
> FATAL: No such option "f".
> Usage: hmmfetch [-options] <hmmfile> <HMM name>
> Available options are:
>   -h   : print short usage and version info, then exit
>   -n   : interpret <HMM name> instead as an HMM number (0..nhmm-1)
> 
> 
> FATAL: No such option "--index".
> Usage: hmmfetch [-options] <hmmfile> <HMM name>
> Available options are:
>   -h   : print short usage and version info, then exit
>   -n   : interpret <HMM name> instead as an HMM number (0..nhmm-1)
> 
> 
> FATAL: No such option "--domtblout".
> Usage: hmmsearch [-options] <hmmfile> <sequence file or database>
>   Available options are:
>    -h        : help; print brief help on version and usage
>    -A <n>    : sets alignment output limit to <n> best domain alignments
>    -E <x>    : sets E value cutoff (globE) to <= x
>    -T <x>    : sets T bit threshold (globT) to >= x
>    -Z <n>    : sets Z (# seqs) for E-value calculation
> 
>     Finished processing 2 of 3 (66.67%) bins.
> FATAL: No such option "f".
> Usage: hmmfetch [-options] <hmmfile> <HMM name>
> Available options are:
>   -h   : print short usage and version info, then exit
>   -n   : interpret <HMM name> instead as an HMM number (0..nhmm-1)
> 
> 
> FATAL: No such option "--index".
> Usage: hmmfetch [-options] <hmmfile> <HMM name>
> Available options are:
>   -h   : print short usage and version info, then exit
>   -n   : interpret <HMM name> instead as an HMM number (0..nhmm-1)
> 
> 
> FATAL: No such option "--domtblout".
> Usage: hmmsearch [-options] <hmmfile> <sequence file or database>
>   Available options are:
>    -h        : help; print brief help on version and usage
>    -A <n>    : sets alignment output limit to <n> best domain alignments
>    -E <x>    : sets E value cutoff (globE) to <= x
>    -T <x>    : sets T bit threshold (globT) to >= x
>    -Z <n>    : sets Z (# seqs) for E-value calculation
> 
>     Finished processing 3 of 3 (100.00%) bins.
>   Saving HMM info to file.
> 
>   { Current stage: 0:00:00.788 || Total: 0:00:44.169 }
> 
>   Parsing HMM hits to marker genes:
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin1/hmmer.analyze.txt'
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin3/hmmer.analyze.txt'
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin2/hmmer.analyze.txt'
> 
>   Aligning marker genes with multiple hits in a single bin:
>     Finished processing 3 of 3 (100.00%) bins.
> 
>   { Current stage: 0:00:00.084 || Total: 0:00:44.254 }
> 
>   Calculating genome statistics for 3 bins with 1 threads:
>     Finished processing 3 of 3 (100.00%) bins.
> 
>   { Current stage: 0:00:00.191 || Total: 0:00:44.446 }
> 
> *******************************************************************************
>  [CheckM - qa] Tabulating genome statistics.
> *******************************************************************************
> 
>   Calculating AAI between multi-copy marker genes.
> 
>   Reading HMM info from file.
>   Parsing HMM hits to marker genes:
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin1/hmmer.analyze.txt'
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin3/hmmer.analyze.txt'
> [Errno 2] No such file or directory: '/data/process/Kecen/SAGBINS/whatiscoverage/bins/bin2/hmmer.analyze.txt'
> 
> 
> ---------------------------------------------------------------------------------------------------------------------------------------------------
>   Bin Id   Marker lineage   # genomes   # markers   # marker sets   0    1   2   3   4   5+   Completeness   Contamination   Strain heterogeneity  
> ---------------------------------------------------------------------------------------------------------------------------------------------------
>   bin3      root (UID1)        5656         56            24        56   0   0   0   0   0        0.00            0.00               0.00          
>   bin2      root (UID1)        5656         56            24        56   0   0   0   0   0        0.00            0.00               0.00          
>   bin1      root (UID1)        5656         56            24        56   0   0   0   0   0        0.00            0.00               0.00          
> ---------------------------------------------------------------------------------------------------------------------------------------------------
> 
>   { Current stage: 0:00:00.029 || Total: 0:00:44.476 }
> [kecenz@sylvan-geomicro1 Kecen]$ hmmfetch -h
> hmmfetch -- retrieve specific HMM from an HMM database
> HMMER 2.3 (May 2003)
> Copyright (C) 1992-2003 HHMI/Washington University School of Medicine
> Freely distributed under the GNU General Public License (GPL)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Usage: hmmfetch [-options] <hmmfile> <HMM name>
> Available options are:
>   -h   : print short usage and version info, then exit
>   -n   : interpret <HMM name> instead as an HMM number (0..nhmm-1)
> 
>

**Comment by thatcatlooksstrong** [comment]
Calling up phmmer, hmmlogo, hmmpgmd, hmmpress, hmmscan, hmmsim, hmmstat, jackhmmer, makehmmerdb, nhmmer, and nhmmscan on the terminal turns up version 3.1.

Calling up hmmeralign, hmmbuild, hmmconvert, hmmemit, hmmerfetch, hmmsearch turns up version 2.3.

**Comment by dparks1134** [comment]
CheckM is certainly failing if hmmsearch v2.3 is being used. CheckM just calls the version of your path.
