### ISSUE TITLE
Extract the marker genes set as a protein fasta

### ISSUE THREAD

**Issue by caonetto** [Ecogenomics/CheckM#154]
Is it possible to extract the marker genes from a bin as a fasta containing only the identified marker gene sequences?

**Comment by dparks1134** [comment]
Yes. You can get these with output option 9 of the "checkm qa" command:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

**Comment by caonetto** [comment]
Hi Donovan,
Thanks for your reply, but where is the output stored? 
In the instruction it says,
**Assess bins for contamination and completeness.

> checkm qa <marker file> <output folder>
Required parameters:

marker_file: marker file specified during analyze command
analyze_folder: folder specified during analyze command**

So first I need to run the analyze command and then specify the market set file e.g. Bacteria.ms, and choose the analyze output folder?
If so, where is the fasta file located at the end? I cannot seem to find it.

Thanks for your help.

**Comment by dparks1134** [comment]
It is written to stdout or can be redirected to a file with the `--file` flag.

**Comment by dparks1134** [comment]
Closed due to inactivity.
