### ISSUE TITLE
checkm merger

### ISSUE THREAD

**Issue by chloelulu** [Ecogenomics/CheckM#156]
Hi,
I have used checkm merger function produced the merger.tsv file. I have also looked at the paper published 'Recovery of nearly 8,000 metagenome-assembled genomes substantially expands the tree of life'. Something confused for me. 
As in the paper you listed, 'The ‘merge’ method of CheckM v.1.0.6 was used to identify pairs of bins where the completeness increased by ≥10% and the contamination increased by ≤1% when merged into a single bin'. 
But based on my analysis, see attached. I have seen one bin can be suggested to be merged to three or four bins. May I have some suggestions from you how to choose the merger bins? Does that mean can one bin be merged with two or three separately? 
Thanks so much.
[merger.xlsx](https://github.com/Ecogenomics/CheckM/files/2041940/merger.xlsx)

**Comment by dparks1134** [comment]
That results would indicate that such a merger is possible given the criteria you provided to the 'merge' method. I'm not sure it is advisable to merge so many bins together though. Merging bins in general needs to be done with considerable care since an incorrect merger will result in a chimeric bin.

**Comment by dparks1134** [comment]
You could run the bin through RefineM to check if it looks like it might be chimeric.

https://github.com/dparks1134/RefineM

**Comment by dparks1134** [comment]
You can install RefineM into your home directory, but it is probably best to request it be install globally on your system the same way CheckM is.

**Comment by chloelulu** [comment]
Hi, 
Always failed. I think it could be the problem of pip version. I am using python 2.7. I
pip install refinem
Traceback (most recent call last):
  File "/home/luyang/anaconda3/envs/python2/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal.
Then I rerun 'pip2 install refinem'
I got the error as the file attached. I do not have the sudo right. May I know how to deal with it?
Thanks so much.
[refinem_error.txt](https://github.com/Ecogenomics/CheckM/files/2050415/refinem_error.txt)

**Comment by dparks1134** [comment]
Hello. I'm not that familiar with pip, but I believe you need to request that you want things installed in your home directory. Perhaps the following will be useful:
https://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip

**Comment by chloelulu** [comment]
I am gonna breakdown. I have tried 'pip2 install --target=/home/RefineM/ refinem ' for the whole afternoon. I still got the error. A lot if files were downloaded into the directory. Error file was in the attachment.I do not know how to do now. :(
[refinem_error2.txt](https://github.com/Ecogenomics/CheckM/files/2051105/refinem_error2.txt)

**Comment by dparks1134** [comment]
Can your sys admin install RefineM?
