### ISSUE TITLE
checkm outliers command error

### ISSUE THREAD

**Issue by Handymanalan** [Ecogenomics/CheckM#160]
Hi everyone,

I am having trouble to execute the "checkm outliers" command.

I tried this command (checkm outliers ./output ./bins tetra.tsv outliers.tsv) but it gives me this error message:
**[Error] No bins found. Check the extension (-x) used to identify bins.**

Then I tried "checkm outliers ./output ./bins -x fasta tetra.tsv outliers.tsv"
**[Error] Missing gene feature files (genes.gff). This plot if not compatible with the --genes option.**

The files are all in the folder generated by the lineage_wf command.

Could anyone please help me with this error?

Cheers and many thanks

Alan

**Comment by dparks1134** [comment]
Closed as redundant with issue #84.
