### ISSUE TITLE
Contamination 

### ISSUE THREAD

**Issue by quliping** [Ecogenomics/CheckM#165]
This is the first time I've ever used the software. So I don't know what do these numbers in the "Contamination" column mean? For example, bin 6 , does that mean the contamination is 2154.89%? Why is it more than 100%? Or, are these figures not percentages?
![qq 20180809112827](https://user-images.githubusercontent.com/39583607/43876465-ba141d44-9bc7-11e8-983d-7a4f977e803a.png)

**Comment by dparks1134** [comment]
Hello. The number is a percentage. A value >100% means the single copy marker genes were identified many times. On the first row, you can see that 56 of the marker genes were identified >=5 times. As such, the estimated contamination is >100%. It would appear this bin  is actually a mix of 5 or more genomes. In fact, the ~2000% contamination suggests there are around 20 organisms worth of marker genes in this bin (these might be 20 distinct genomes or a odd mixture of several dozen partial genomes).

**Comment by Devadas07** [comment]
what conclusion can draw from these results 
![Capture](https://user-images.githubusercontent.com/43874330/56903385-d49c0700-6ab9-11e9-9187-e412f25379e8.JPG)

**Comment by dparks1134** [comment]
I'd conclude all these genomes are close to complete with little to no contamination.

**Comment by Devadas07** [comment]
thanks for ur quick response dparks 
one of my senior asked me to remove these two genomes synechoccus_sp.JA_3_3Ab and synechoccus_sp.JA_2_3Ba_2_13 from my genomes list for firther studies and he says these two are contaminated and may i know what is the difference between P_Cyanobateria (UID2143) and K_bacteria (UID1453).
![Capture2](https://user-images.githubusercontent.com/43874330/56940774-11094a80-6b2e-11e9-9759-94f4d7ed3a9c.JPG)

**Comment by dparks1134** [comment]
UID2143 and UID1453 indicate the node in the CheckM reference tree which was used to establish the set of marker genes used to evaluate the quality of the genome. The k__Bacteria indicates this node is above any named phyla. The p__Cyanobacteria indicates it is above any named Cyanobacteria class. The exact number of marker genes in the marker sets is given in the # markers column. These genes are organized into co-located marker sets (see the CheckM manuscript for details). I'm not sure the exact nature of your project, but these results suggest the synechoccus_sp.JA_3_3Ab and synechoccus_sp.JA_2_3Ba_2_13 genomes are 100% complete with little to no contamination.

**Comment by Devadas07** [comment]
thanks for ur response dparks 
little contamination means should i take this contamination into consideration or not. what are the upper and lower limits of contaminations.
and can u suuggest me how sholud i remove these contaminations.

**Comment by dparks1134** [comment]
Not sure I can provide much insight here. It depends on both your application and the source of the genomes. If these are isolate genomes, low levels (say <2%) of reported contamination is likely just inaccuracies in the CheckM estimates. If these are metagenome-assembled genomes, the situation is unclear. You can look to use MAGpurify, RefineM, or ACDC to remove contamination.

**Comment by Devadas07** [comment]
thanks, u so much for this valuable information sir.
I am running checkm to find % of contamination for further analysis of cyanobacterial genomes. if any contamination found I want to discard for further analysis. actually, I have taken these genomes from NCBI FTP site. I am working on comparative studies of cyanobacterial species for pan-genome analysis.

**Comment by DongYuan5177** [comment]
Hello! what conclusion can draw from my results？
![checkM](https://github.com/Ecogenomics/CheckM/assets/26022889/aac2be11-38a1-49f4-b20b-e487bd72e028)
