### ISSUE TITLE
Unable to install checkm

### ISSUE THREAD

**Issue by khuch123** [Ecogenomics/CheckM#167]
I have python 3.6 where checkm is installed
But it is a python2 requiring software
So when I install pip install numpy it says it is already there in bin of python 3.6
So is with checkm

Please help and also there is always an error of phylo.hmm
How to install this file and set path

Please help at earliest

**Comment by dparks1134** [comment]
CheckM required Python 2 and all dependencies must be install under Python 2. I recommend installing numpy and the rest of the SciPy stack first:
https://www.scipy.org/install.html
