### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'bVerbose

### ISSUE THREAD

**Issue by varunshamanna** [Ecogenomics/CheckM#168]
when i try to run check with lineage workflow i get this error
$ checkm lineage_wf -t 5 -x fasta /media/varunshamanna/HOLYSMOKES/Mtech\ Project/SRR7343999/Binning/maxbin/abyss_maxbin_out /home/varunshamanna/Mtech\ Project/checkm_out/maxbin_checkm/

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 2 bins with 5 threads:
  [Error] Input file does not exists: /home/varunshamanna/Mtech Project/checkm_out/maxbin_checkm/bins/abyss_maxbin_out.001/genes.gff.4

  [Error] Input file does not exists: /home/varunshamanna/Mtech Project/checkm_out/maxbin_checkm/bins/abyss_maxbin_out.002/genes.gff.4

  Saving HMM info to file.

  Calculating genome statistics for 2 bins with 5 threads:
    Finished processing 2 of 2 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/bin/checkm", line 709, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1253, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/usr/local/lib/python2.7/dist-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1213, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'

**Comment by dparks1134** [comment]
Can you confirm that you are using the latest version of CheckM (v1.0.11)?

**Comment by dparks1134** [comment]
Closed due to inactivity.

**Comment by varunshamanna** [comment]
Dear sir,
I am using the latest version of checkm. Sorry for the late reply.

Varun Shamanna
M.Tech Bioinformatics,
RV College of Engineering
varunshamanna4@gmail.com
8123341361

**Comment by dparks1134** [comment]
How did you install CheckM? Through pip or directly from the Github repository? Installation through pip is recommended.

**Comment by varunshamanna** [comment]
I installed it through pip.

Varun Shamanna
M.Tech Bioinformatics,
RV College of Engineering
varunshamanna4@gmail.com
8123341361

**Comment by dparks1134** [comment]
Afraid I don't have a good suggestion. CheckM v1.0.11 works on my system and is used by a number of other people without issue. I've looked through the code and can't see why it would be failing as reported. Sorry I can't be on more help.

**Comment by dparks1134** [comment]
Actually I can see that someone else has reported the same issue. I will release v1.0.12 later today that will hopefully address this. It must be specific to a given Python version or system setup since it doesn't appear to impact most users or myself. Anyway, please let me know if v1.0.12 doesn't fix the problem.

**Comment by varunshamanna** [comment]
Sure sir thank you

Varun Shamanna
M.Tech Bioinformatics,
RV College of Engineering
varunshamanna4@gmail.com
8123341361
