### ISSUE TITLE
problem installing CheckM

### ISSUE THREAD

**Issue by jfroula** [Ecogenomics/CheckM#169]
I think there might be some problem with the checkm installation.  I tried
the following commands in a docker container that was created by `docker run -it --endpoint=/bin/bash ubuntu:latest` . 

Commands

```
apt-get update && apt-get install -y wget gcc unzip   
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh   
bash ./Miniconda2-latest-Linux-x86_64.sh -b    
export PATH=/root/miniconda2/bin:$PATH   
pip install numpy   
pip install checkm-genome   
```

The error:  

```
configure: error: zlib development files not found

    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    FAILED.  This error must be resolved in order to build HTSlib successfully.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-T5njCQ/pysam/setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-install-T5njCQ/pysam/setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/root/miniconda2/lib/python2.7/subprocess.py", line 216, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/root/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/root/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
```

**Comment by dparks1134** [comment]
Hello. CheckM uses pysam as a 3rd party dependency. The error looks specific to this software. I would suggest trying to install pysam separately first and to report any issues with its installation to the good folks that maintain pysam.
https://pysam.readthedocs.io/en/latest/

**Comment by jfroula** [comment]
I can install pysam fine with `conda install pysam` but `pip install checkm-genome` still fails at pysam with different error, i.e. it says I need zlib1g-dev and when I install it `apt-get install -y zlib1g-dev` it complains about another library, and so on.  I got to an error that I didn't understand and gave up....so I'm not sure problem is with pysam??? but some conflict with pysam and checkm.

**Comment by jfroula** [comment]
Anyways, I can wait to see if anyone else has an installation problem.  If not then it must be my end and you can forget it....thanks

**Comment by jfroula** [comment]
So If I run `conda install pysam` and  then `pip install checkm-genome` I get error.  
However, 
if I run `conda install -y -c bioconda pysam=0.15.0`  then checkm installs fine.

**Comment by dparks1134** [comment]
Thanks for letting me know. I'm not familiar with conda, but seems odd you would need to specify 0.15.0 as this is the latest version. Glad it works though.
