### ISSUE TITLE
Guppy

### ISSUE THREAD

**Issue by dburkhardt** [Ecogenomics/CheckM#17]
I downloaded and installed CheckM using pip as directed on this wiki, but when I run the 'checkm tree' command or execute 'checkm test' I get the following error:

[Error] Make sure guppy is on your system path.

  Controlled exit resulting from an unrecoverable error or warning.

I don't know what guppy is or why it wasn't installed when I ran the pip installer. Can you please direct me?

Thanks!
Dan

**Comment by dparks1134** [comment]
I've update the CheckM documentation along with the error message provided when guppy is missing in order to make it clear that it is part of the pplacer package.
