### ISSUE TITLE
understanding HMMER alignement file output

### ISSUE THREAD

**Issue by bernt-matthias** [Ecogenomics/CheckM#170]
there are multiple tools with the `--ali` option that generate HMMER alignment file for each bin: 

- tree generating bins/binX/hmmer.tree.txt
- analyze generating bins/binX/hmmer.analyze.txt
- lineage_wf generating both files
- taxonomy_wf  generating

Can you explain me the difference between the two files. 

Clearly the workflows generate both files, because tree and analyze are called. Can you tell me which of the two is actually meant by the --ali option or is it both?

**Comment by dparks1134** [comment]
The hmmer.tree.txt file is the alignment of the genes used to insert your genome into the CheckM reference tree. These genes are uses solely for this purpose. The hmmer.analyze.txt contains the alignment of the genes used to assess the completeness and contamination of your genomes.
