### ISSUE TITLE
checkm fully automatic mode

### ISSUE THREAD

**Issue by bernt-matthias** [Ecogenomics/CheckM#171]
Hi, 

currently I try to wrap checkm for Galaxy. This needs to call the command lines completely automatic, i.e. no user interaction is possible. 

I have seen that sometime checkm asks question to the user: e.g. if I add `--gene` but provide nucleotide sequences. 

``` 
Expected all files to contain sequences in amino acid space.
File bin_folder/0.fna appears to contain nucleotide sequences.
Do all files contain only amino acid sequences? [y/N]
```

Is it possible to switch off all user interaction, e.g. by an additional command line flag? A message to stderr would still be great.

**Comment by dparks1134** [comment]
Hello. There is currently no mechanism for disabling all prompts. I will endevour to do this for the next release of CheckM. I'd be happy to accept a pull request if you have an immediate need for this feature.

**Comment by bernt-matthias** [comment]
Thanks for the response. 

As a workaround I call `echo | checkm` which triggers the default answer. Might be sufficient for the moment. 

In the best case a solution would just print a message to stderr and continue, trusting the user blindly.

**Comment by bernt-matthias** [comment]
I have another question. For the Galaxy tools I would need some small test data (Galaxy enforces automatic tests). For the tools that have bam or sequence input, like coverage I'm currently strunggling to think of useful (small) test sets. Maybe you have some test data that you use for testing that I could use?

**Comment by dparks1134** [comment]
Hello. I'd suggest using an E. coli genome. If you need a BAM file you could cut the genome up into pieces and map it back against itself. This isn't really a test of correct function, but would at least show the command is running without issue.

**Comment by dparks1134** [comment]
Hello. CheckM has the "test" method now that runs an E. coli genome through the standard CheckM workflow. Results of this test will be written to a log file starting with v1.0.15 which I plan to release later today. As suggested, I also trust the user to provide data in the correct format and simply issue a warning if a sequence file appears to contain incorrect data.

**Comment by pimarin** [comment]
Hello, 
I'm interesting to embed checkM in a galaxy workflow but It seem to be absent from tool shed. Nexs about a dev or it need it ?

**Comment by bernt-matthias** [comment]
Hi @pimarin I was working on an automatic generation of the checkm wrappers, but never finished it. The current state is at https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/checkm .. feel free to continue from there. Would be great to have this in the IUC repo.
