### ISSUE TITLE
Mismatch in taxonomy for members of the order o__Erysipelotrichales

### ISSUE THREAD

**Issue by ShaiberAlon** [Ecogenomics/CheckM#172]
Hi,

I recently ran CheckM on a collection of genomes that belong to the order `Erysipelotrichales`, and while the order is assigned correctly, checkM assigns these genomes to the class `c__Mollicutes` and phylum `p__Tenericutes`. But the order `Erysipelotrichales` belongs to the sub-class `Erysipelotrichi` (class `Bacilli`) in `Firmicutes` (see for example https://en.wikipedia.org/wiki/Erysipelotrichia).

For example, my genomes included [Erysipelothrix tonsillarum](https://en.wikipedia.org/wiki/Erysipelothrix), [eggerthia catenaformis](https://en.wikipedia.org/wiki/Eggerthia_catenaformis), [Solobacterium moorei](https://en.wikipedia.org/wiki/Solobacterium_moorei), and more (all are firmicutes, but were assigned to tenericutes by CheckM). To further test this, I used some ribosomal proteins and computed a phylogenetic tree, which also confirmed that these all fall within the Firmicutes.

I was using checkM version `v1.0.6`, which I now see that it is far behind the latest release, but I'm not sure if that matters since it seems to me like the problem might be in the database.

Thank you very much!

**Comment by dparks1134** [comment]
Hello. If you look at the reference tree for CheckM you will see that the Erysipelotrichales fall in the Mollicutes. This isn't to say this is correct (in fact, I don't think it is), but it is the phylogenetic relationship that results from the phylogenetic marker genes and inference method used by CheckM. CheckM is not meant to be a method for assigning taxonomic attributions. There are a number of incongruencies between the NCBI taxonomy and the inferred CheckM reference tree. The CheckM reference tree also contains genomes selected for the purposes of evaluating genome quality and not establishing taxonomic assignments. 

You might find the GTDB (http://gtdb.ecogenomic.org/) and GTDB-Tk (https://github.com/Ecogenomics/GTDBTk) useful if you are looking for an automated way to obtained taxonomic assignments. Eventually we hope to update CheckM to use the GTDB taxonomy.

**Comment by ShaiberAlon** [comment]
Hi Donovan,

Thank you very much for your quick response, and for the information. I will definitely look into using GTDB.
