### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by apeltzer** [Ecogenomics/CheckM#173]
As Python2.X is considered legacy starting soon and after a period of a couple of years, people are now switching over to Python 3.X:

https://wiki.python.org/moin/Python2orPython3#Which_version_should_I_use.3F 

Maybe you could check which parts are missing to get full Python3 Support?

**Comment by dparks1134** [comment]
This is now being actively worked on. I plan to move the official CheckM release over to Python 3 in the next week.
