### ISSUE TITLE
Package maintenance and requirements

### ISSUE THREAD

**Issue by vinisalazar** [Ecogenomics/CheckM#177]
Hi,

is this package being actively maintained? I was able to install through the Bioconda distribution but I noticed a couple of faults in the `README` instructions and also that it is lacking a `requirements.txt` file enabling installation with the `python setup.py install`. Also, the Bioconda distribution install with Python 3.6 but the package seems to be compatible with Python 2.7, with things like print functions without parentheses going on.

If the repo is being actively maintained I would be happy to potentially contribute with PRs to improve packaging. Otherwise, I won't bother.

Regards,

V

**Comment by dparks1134** [comment]
Hello. It is still being maintained and would welcome any contributions.

**Comment by vinisalazar** [comment]
Great. I hope to submit them soon.
