### ISSUE TITLE
Mac installation instructions + Python 3 compatibility

### ISSUE THREAD

**Issue by vinisalazar** [Ecogenomics/CheckM#178]
Hi,

in #177 I mentioned my concerns regarding packaging, and I thought I should specify them more thoroughly. They boil down to two main ones:

**1. OS X compatibility**  
In the [wiki's system requirements section](https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements) you mention CheckM is designed for Linux. However, it is perfectly possible to run it on a Mac. The hindrance here is installing `pplacer` and pplacer's dependency, `guppy`. It is a bit of a pain to install `pplacer` on a Mac but it does have a [Darwin OS older release](https://github.com/matsen/pplacer/releases/tag/v1.1.alpha17) which works perfectly fine. I'm preparing a PR with install instructions, which also involves the next concern:  

**2. Compatibility with Python 3 and Conda recipe**  
From my experience, the cleanest and preferred way of installation for Python packages with multiple dependencies (like CheckM) is to use `conda`. The [`conda` CheckM installation available at the moment](https://anaconda.org/bioconda/checkm-genome) installs Python 3 by default, and like #173 and #174 suggested, it would indeed be good to work towards Python 3 compatibility. Implementing such compatibility and updating the Conda recipe to include all adequate dependencies, such as `pplacer`, `HMMER` and `prodigal` (all have `conda install` wrappers, and also PySam which for me triggered an error similar to #175) would greatly improve the installation process for the end user. I am afraid I'm a bit unexperienced in editing conda recipes, but I'd be happy to write adequate install instructions for a conda installation in both systems (Linux and OS X) in agreement with my previous concern.

Thank you for any assistance you can provide,

V

**Comment by vinisalazar** [comment]
Update:
I just ran `checkm test` on a Python3 refactored branch, with a `conda` env, on a Mac. All 5 steps passed!

**Comment by dparks1134** [comment]
I'm glad to hear CheckM can be made to run under Python 3. I do have some hesitations moving CheckM to Python 3 as many labs already have CheckM successfully running under Python 2. Do the changes required for Python 3 break compatibility with Python 2?

**Comment by vinisalazar** [comment]
Dear @dparks1134, sorry for the delay.

Apparently it doesn't... It passed all 5 steps in environments with both Python 2.7 and Python 3.6.

I am having some trouble, however, in reproducing the Python 3 environment. I had to make some changes to the directory in which the code is installed (when running `python setup.py install`), other than the source code itself. ATM I am debugging to get the refactored branch to work on an environment created with the following configuration:

`conda create -n checkm-dev

**Comment by vinisalazar** [comment]
Dear @dparks1134, sorry for the delay.

Apparently it doesn't... It passed all 5 steps in environments with both Python 2.7 and Python 3.6.

I am having some trouble, however, in reproducing the Python 3 environment. I had to make some changes to the directory in which the code is installed (when running `python setup.py install`), other than the source code itself. ATM I'm listing the changes needed when creating a new environment, running some more tests, and debugging the install.

Would you be so kind as to create a new branch on the original fork so I can start submitting PRs for your appreciation? Clearly it wouldn't be a good idea to push them directly to the master branch.

**Comment by vinisalazar** [comment]
Regarding concern .2, I have installed checkm-genome with conda on a Linux machine and the environment comes with Python 2.7... so the conda recipe for the Linux distro should be good. The Mac distro needs to be updated, though.

**Comment by dparks1134** [comment]
Hello. I've created a `dev` branch for accepting PRs and moving towards a Python 2.7 / 3.x compatible version of CheckM.

**Comment by jolespin** [comment]
Are there any updates on this?  I have a pipeline that is dependent on CheckM but the other tools I need in the pipeline are Python 3 only..

**Comment by dparks1134** [comment]
CheckM v2 is in development which will be native Python 3. This isn't expected to be complete before the end of the year though.

**Comment by jolespin** [comment]
Is there a devel I can try out with the `python3` version?  The only part of `checkm` my pipeline uses is the `analyze` and `ssu_finder` parts.  Looking forward to the official release :)

**Comment by vinisalazar** [comment]
Hi @jolespin, I ended up leaving the refactor on hold for the past months, but I check if the python3_dev branch of this repo works

**Comment by jolespin** [comment]
```
-bash-4.1$ source activate checkm3_env
(checkm3_env) -bash-4.1$ pip install git+https://github.com/Ecogenomics/CheckM/tree/python3_dev
Collecting git+https://github.com/Ecogenomics/CheckM/tree/python3_dev
  Cloning https://github.com/Ecogenomics/CheckM/tree/python3_dev to /local/ifs3_scratch/METAGENOMICS/jespinoz/TMPDIR/pip-req-build-uqrf69p9
  Running command git clone -q https://github.com/Ecogenomics/CheckM/tree/python3_dev /local/ifs3_scratch/METAGENOMICS/jespinoz/TMPDIR/pip-req-build-uqrf69p9
  fatal: repository 'https://github.com/Ecogenomics/CheckM/tree/python3_dev/' not found
ERROR: Command "git clone -q https://github.com/Ecogenomics/CheckM/tree/python3_dev /local/ifs3_scratch/METAGENOMICS/jespinoz/TMPDIR/pip-req-build-uqrf69p9" failed with error code 128 in None
```

I'll try cloning it another way.
