### ISSUE TITLE
Added "number of threads" argument to test command

### ISSUE THREAD

**Issue by vinisalazar** [Ecogenomics/CheckM#180]
It would be useful to add a "number of threads" argument to the test command, so tests can be ran faster.

At the time of writing this. `test_parser` arguments are located in lines 673-678 of [`/bin/checkm`](/bin/checkm). Maybe a "number of threads" argument can fit in there, like in some of the other scripts?

**Comment by dparks1134** [comment]
CheckM runs multiple genomes in parallel when multiple threads are indicated. Since the test case only considers a single genome using multiple threads will not speed up the result.
