### ISSUE TITLE
Contributing guidelines (and creating a CONTRIBUTING file)

### ISSUE THREAD

**Issue by vinisalazar** [Ecogenomics/CheckM#181]
Dear CheckM development team,

you might have noticed that I have been opening quite a few issues here. I am currently starting a research project which will make heavy use of CheckM. Therefore, I am interested in contributing, and have made these issues to record what I am planning/working on. I have a fork with a few commits and would be happy to start making PRs to the original repo.

In #177, Dr. @dparks1134 mentioned that you would "welcome any contributions." I apologise, but this is a bit vague, so I would like to kindly ask if you have any guidelines regarding contributions, and go as far as suggesting the addition of a `CONTRIBUTING` file for future references.

Bw,

Vini

**Comment by dparks1134** [comment]
Hello Vini,

The CheckM development team is just myself. I plan to release CheckM version 2 late in the new year. I do welcome contributions to the current release and would be happy to add a `CONTRIBUTING` file. There are no official guidelines for contributing as you are the first one to express a substantial interest in this regard.

Cheers,
Donovan

**Comment by vinisalazar** [comment]
That is great to hear.

happy holidays,
V
