### ISSUE TITLE
CheckM exit normally when output dir is not empty

### ISSUE THREAD

**Issue by nigiord** [Ecogenomics/CheckM#182]
Hi there,

I understand that CheckM refuses to work when the result directory is not empty to avoid overwriting previous results, but I noticed that it does not raise any error: it just gives a warning in the log and exits normally (code 0). This is bad practice as it does not allow other softs to know something went wrong and that they should not expect to find checkM result files (or worse, that the results files are old files that have not been updated!).

https://github.com/Ecogenomics/CheckM/blob/master/checkm/common.py#L64-L74

A way to fix this would be to replace `sys.exit()` by `sys.exit(1)` at L74, or better, to raise an Exception instead of using the `sys.exit()` function.

It would also be useful to add a `--force-overwrite` option that bypasses `checkEmptyDir()` at the beginning of the workflow, so checkM can more easily be implemented inside a bigger pipeline.

Cheers,
Nils

**Comment by dparks1134** [comment]
Hello Nils,

Failed commands should now exit with error code 1 in v1.0.13. I also added a `--force-overwrite` flag to the tree command.

Cheers,
Donovan

**Comment by nigiord** [comment]
Awesome, thank you!

Nils
