### ISSUE TITLE
pplacer only uses one thread/core

### ISSUE THREAD

**Issue by franciscozorrilla** [Ecogenomics/CheckM#186]
Hey Donovan,

I am running the following jobscript on my HPC cluster:

```
#!/usr/bin/env bash
#SBATCH -A SNIC2018-3-18
#SBATCH -N 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 20
#SBATCH -C MEM64|MEM128
#SBATCH -t 2-00:00:00

checkm lineage_wf -x fa -t 20 --pplacer_threads 20 bins OUTDIR
```

When I check htop, it looks like pplacer is only running on one thread/core even though I used the `--pplacer_threads 20` parameter:

![image](https://user-images.githubusercontent.com/35606471/51183238-ed006100-18d0-11e9-804c-fc37a734ef31.png)

Is this normal?

Best wishes,
Francisco

**Comment by dparks1134** [comment]
Only some steps in pplacer are multithreaded so this is normal for some steps.

**Comment by franciscozorrilla** [comment]
Ah great, good to know
