### ISSUE TITLE
use CheckM to find redundancy

### ISSUE THREAD

**Issue by lalalagartija** [Ecogenomics/CheckM#189]
Hi, I am concerned that my bins are a little overestimated then I would like to assess redundancy in my bins. I read that CheckM can be used for that. How do I get the estimates of redundancy in my bins ?

Thank you very much in advance,

**Comment by dparks1134** [comment]
Hello. CheckM can be used to estimate the completeness and contamination (aka redundancy). The CheckM wiki provides information on how to run the software:
https://github.com/Ecogenomics/CheckM/wiki

**Comment by lalalagartija** [comment]
Thank you very much. I was not sure what you ment with contamination and heterogeneity.
