### ISSUE TITLE
Error : pplacer seems not to work 

### ISSUE THREAD

**Issue by lalalagartija** [Ecogenomics/CheckM#191]
Hi, 
I'm trying to use checkm lineage_wf and it fails to use pplacer with this error message : Make sure pplacer is in your path (which it is). I do not understand where the problem comes from. I have pplacer version v1.1.alpha19-0-g807f6f3, prodigal version v2.6.3 and hmmsearch version 3.1b2. 

Thank you very much for your help

**Comment by dparks1134** [comment]
Hello,

pplacer needs to be on your system path and executable by calling
"pplacer". I'm not sure what else to suggest since this error is generated
by trying to find pplacer on your path and failing to locate it.

Cheers,
Donovan

**Comment by lalalagartija** [comment]
Thank you. it was as simple as that. I had an alias of pplacer instead of having it in the path. 
Cheers,
