### ISSUE TITLE
bin_qa_plot needs storage/bin_stats_ext.tsv?

### ISSUE THREAD

**Issue by sipesk** [Ecogenomics/CheckM#192]
Hello,

I downloaded checkm on my home directory and when I try to run 
$ checkm bin_qa_plot ./outputfolder ./binfolder ./plotfolder

 I get 
[Error] Input file does not exists:  ./outputfolder/storage/bin_stats_ext.tsv

The prompt says to put 
 out_folder           
  bin_folder            
  plot_folder 

in the command. my bins are in .fna.

Any help would be appreciated.

Thanks,
Katie Sipes

**Comment by dparks1134** [comment]
Hello Katie. Is `outputfolder` a directory containing CheckM results for the genomes in `binfolder`? The error message would suggest this isn't the case.
