### ISSUE TITLE
Install issues/dependencies pplacer OCaml

### ISSUE THREAD

**Issue by uloeber** [Ecogenomics/CheckM#194]
Hi all,
I tried to install checkM on our cluster and failed. One of the admins was investigating the issues and replied:

> I think this means that you need Python 2 (this is an old style “print”
> statement).
> 
> I just looked at the list of dependencies and noticed that it requires
> pplacer, which has only recently been removed from Guix as it depends on
> an old version of OCaml (4.01) which is known to have an unfixed
> security vulnerability.  It could not be built with a newer version of
> OCaml.
> 
> See also https://github.com/matsen/pplacer/issues/359 and
> https://github.com/matsen/pplacer/issues/354.

Can you somehow investigate and fix these issues? This would be very nice!

Best wishes,
Ulrike

**Comment by dparks1134** [comment]
Hello. CheckM requires Python 2. I don't maintain pplacer, but binaries for Linux can be downloaded directly so there is no need to compile it from source:
https://matsen.fhcrc.org/pplacer/
