### ISSUE TITLE
checkm thread creation failed

### ISSUE THREAD

**Issue by johanneswerner** [Ecogenomics/CheckM#195]
I am running `checkm` as part of metawrap. I have been describing the issue also in the metawrap repository, see the issue [here](https://github.com/bxlab/metaWRAP/issues/157). 

This is the error I am getting

```bash
(...)
*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 136 bins with 1 threads:
Fatal exception (source file esl_threads.c, line 129):
thread creation failed
```

And it does not make any difference if I take one or more threads (with the difference that more thread creations fail if I use multiple threads). 

I have been trying with version 1.0.12 and 1.0.13. 

Any ideas? I was already wondering if this has something to do with the multithreading module. If you need any other information, please let me know.

- Ubuntu 16.04.2 LTS
- Python 2.7.15
- conda 4.6.11

**Comment by ursky** [comment]
Interesting how you mentioned in the other post that this only happens in some bin sets. Can you post the problematic binsABC set so I can try to reproduce this? Also, it might be worth bringing this up with the CheckM team @dparks1134.

**Comment by johanneswerner** [comment]
I have the feeling it has nothing to do with the dataset. 

I am currently testing with another dataset. I reinstalled the conda environment for metawrap. It seems to be working if I run it with one thread - which is not great but at least it seems to be working. I will continue testing with my other two datasets in the next days and keep you updated. 

I wonder if some cental Python package dependency (maybe the `multiprocessing` module) are not available in the correct version.

**Comment by dparks1134** [comment]
I believe `esl_threads.c` is part of HMMER so perhaps the problem lies there.

**Comment by johanneswerner** [comment]
@dparks1134 Thank you for your insight. Actually, `esl_threads.c` is not part of HMMER but of Easel (https://github.com/EddyRivasLab/easel/blob/master/esl_threads.c), however Easel does not seem to be a dependency of `metawrap` or `hmmer`. I checked my conda environment and there is no such file.

Any ideas?

**Comment by ursky** [comment]
Can you try to install Easel (`conda install -c bioconda easel `) to see what happens?

**Comment by johanneswerner** [comment]
@ursky I already tried that and the same problem remains. 

I find it particularly interesting that this does not happen at the beginning: 

```
------------------------------------------------------------------------------------------------------------------------                                                            [187/6837]
-----                                         Running CheckM on binsA bins                                         -----
------------------------------------------------------------------------------------------------------------------------


*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 202 bins with 36 threads:
    Finished processing 202 of 202 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 202 bins with 36 threads:
    Finished processing 202 of 202 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 202 of 202 (100.00%) bins.
  Extracting 43 HMMs with 36 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 36 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 202 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:22:44.938 || Total: 0:22:44.938 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 202 of 202 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 202 of 202 (100.00%) bins (current: bin.129).   

  Marker set written to: binsA.checkm/lineage.ms

  { Current stage: 0:01:00.995 || Total: 0:23:45.934 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 202 bins with 36 threads:
Fatal exception (source file esl_threads.c, line 129):
(...)
# and then all other treads also fail
```

When I am running `checkm` as part of `metawrap` with multiple threads, it always breaks at this point: 

```
 [CheckM - analyze] Identifying marker genes in bins.
```

not before (but multithreading is also used before (see first code segment in this comment). 

I have already rebuilt my conda environment. I am not sure what else I could try out.

Thank you @ursky and @dparks1134 for helping me sorting this out.

**Comment by ursky** [comment]
Can you please try to run CheckM manually to confirm this has nothing to do with metaWRAP itself?

MetaWRAP deploys CheckM like so: `checkm lineage_wf -x fa $bin_set ${bin_set}.checkm -t $threads --tmpdir ${bin_set}.tmp --pplacer_threads $p_threads`. So try running `checkm lineage_wf -x fa binsABC binsABC_out.checkm -t 24 --pplacer_threads 8`.

**Comment by johanneswerner** [comment]
I tried to reproduce the issue from `checkm` but it runs without any problems. So after that, I rerun the binning refinement step from `metawrap` with two threads, but it seems I cannot reproduce the issue. 

For now, it is working, I really don't know why or what has changed. I will close the issue now. @ursky and @dparks1134 Thank you a lot for your help with all of that, I really have no idea why the issue occured.
