### ISSUE TITLE
checkM in pyhton3

### ISSUE THREAD

**Issue by mstambou** [Ecogenomics/CheckM#198]
hi all,

is there a checkM implementation in python3?

**Comment by dparks1134** [comment]
Afraid not. CheckM v2 will be native Python 3, but this isn't expect to be ready until around the end of the year.

**Comment by mstambou** [comment]
that's okay no worries. Ill be switching back and forth between 2 and 3 for now. On another note, if I want to do a taxonomic assignment using the least common ancestors approach for my bins is: checkm lineage_wf the best function for this task?

**Comment by dparks1134** [comment]
CheckM is not intended to provide taxonomic assignments. I would suggest using the GTDB-Tk for this task: https://github.com/Ecogenomics/GTDBTk.

**Comment by mstambou** [comment]
I see. However upon using checkm tree_qa function I was getting some sort of a taxonomic assignment to my bins, do you think this information is not accurate?

**Comment by dparks1134** [comment]
It isn't ideal since it doesn't contain a lot of lineages proposed in the last couple years, and the taxonomy used by CheckM isn't perfectly congruent with the CheckM reference tree. These issues are handled by the GTDB (http://gtdb.ecogenomic.org/).
