### ISSUE TITLE
Error  running checkm lineage_wf

### ISSUE THREAD

**Issue by wangjianing0618** [Ecogenomics/CheckM#199]
Greetings,
I've been recently started to use CheckM o evaluate the bins from my metagenomic data but I'm getting stuck in the first step of lineage_wf. When I ran command Line：

 checkm lineage_wf -t 4 -x fa metabat/bins metabat/checkm

I got' the following error:

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/lilab/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/lilab/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 1252, in parseOptions
    self.tree(options)
  File "/home/lilab/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 120, in tree
    if not options.force_overwrite:
AttributeError: 'Namespace' object has no attribute 'force_overwrite'

Thank you very much. Looking forward to your help.

Jianing Wang

**Comment by wangjianing0618** [comment]
![Selection_007](https://user-images.githubusercontent.com/51053888/58446177-4061a600-8132-11e9-97a3-c68d874558c0.png)

**Comment by dparks1134** [comment]
I believe this is an old bug. Can you please confirm you are using the latest version of CheckM?

**Comment by wangjianing0618** [comment]
Oh...Thank you very much! You gave me great help.
