### ISSUE TITLE
CheckM and pplacer correctly installed and in PATH but checkm not running: [Errno 2] No such file or directory: 'ffn_checkM/.../hmmer.tree.txt'/[Error] Make sure pplacer is on your system path.

### ISSUE THREAD

**Issue by efr3m** [Ecogenomics/CheckM#20]
I installed ChcekM and ppler as reported in the isntructions.
I updated the CheckM db manaully and changed the `checkm data setRoot ` succsesfully.

However, when I run the test I got the follwong errors: 

    sudo checkm test ~/checkm_test_result # I have to run in sudo otherwise does not work
   *******************************************************************************
    [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
    *******************************************************************************
     [Step 1]: Verifying tree command.
    *******************************************************************************
     [CheckM - tree] Placing bins in reference genome tree.
    *******************************************************************************
    Identifying marker genes in 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.
    FATAL: No such option "--domtblout".
    Usage: hmmsearch [-options] <hmmfile> <sequence file or database>
    Available options are:
       -h        : help; print brief help on version and usage
       -A <n>    : sets alignment output limit to <n> best domain alignments
       -E <x>    : sets E value cutoff (globE) to <= x
       -T <x>    : sets T bit threshold (globT) to >= x
       -Z <n>    : sets Z (# seqs) for E-value calculation
     Finished processing 1 of 1 (100.00%) bins.
      Saving HMM info to file.
      Calculating genome statistics for 1 bins with 1 threads:
      Finished processing 1 of 1 (100.00%) bins.
     Extracting marker genes to align.
     Parsing HMM hits to marker genes:
    [Errno 2] No such file or directory: u'/home/xxx/checkm_test_result/results/bins/637000110/hmmer.tree.txt'

    Extracting 43 HMMs with 1 threads:
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000025ad370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000e5c370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000024e0370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000cd0370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000002270370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000001acb370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000001629370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000d62370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x000000000216b370 ***
     Aborted
     *** Error in `hmmfetch': double free or corruption (out): 0x0000000001a44370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000001fa5370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000c03370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000c63370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x000000000224f370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000002545370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x000000000201f370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000014c9370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000a0d370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000021f9370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000024be370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000000f31370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000001f9f370 ***
    ....... # it repeats this message few times more
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x0000000001e4b370 ***
    Aborted
    *** Error in `hmmfetch': double free or corruption (out): 0x00000000025dc370 ***
    Aborted
    Finished extracting 43 of 43 (100.00%) HMMs.
    Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
    [Error] Make sure pplacer is on your system path.
    Controlled exit resulting from an unrecoverable error or warning

    echo $PATH
    /usr/local/lib/partitionfinder-master/programs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/lib/Prodigal-2.6.1:/usr/local/lib/prokka-1.10/bin:/usr/local/lib:/usr/local/lib/get_homologues-x86_64-20141112:/usr/local/lib/rnammer-1.2:/usr/local/lib/pplacer-v1.1:/usr/local/lib/pplacer-v1.1/scripts:/usr/local/lib/CheckM-master

Do you know what I am doing wrong?

**Comment by dparks1134** [comment]
Hello,

CheckM requires HMMER >=3.1b1. It appears you only have rnammer on your path. Can you confirm that HMMER >= 3.1.b1 is installed and on the path. You can check the version number with <code> hmmsearch -h</code>.

Cheers,
Donovan

**Comment by efr3m** [comment]
Thanks for your answer. I have in my PATH hmmser 2.4i.
I will try to get the 3.1 version and see if it works.

    hmmsearch -h
    hmmsearch - search a sequence database with a profile HMM
    HMMER 2.4i (December 2006)
    Copyright (C) 1992-2006 HHMI Janelia Farm
    Freely distributed under the GNU General Public License (GPL)
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by efr3m** [comment]
You were completely right!
With hmmer 3.1b1 in the paths everything went perfect.
Thanks very much!
