### ISSUE TITLE
 k_Bacteria (UID203) & f__Rhizobiaceae (UID3564); how to set marker genes?

### ISSUE THREAD

**Issue by limin321** [Ecogenomics/CheckM#200]
my nanopore sequence data are all agrobacterium tumefaciens, just sequenced on two different dates. for both genomes I use following command,
$ checkm lineage_wf -f CheckM1.txt -t 4 -x fasta bins/ bins/SCG2/

How come the first date output include f__Rhizobiaceae (UID3564) with completeness >= 80%; while second date output use  k_Bacteria (UID203) with completeness less than 10%; when I blast against with each other, they are pretty close. 

Can anyone have similar experience and help me solve this problem? 

I want to use f__Rhizobiaceae (UID3564) instead of  k_Bacteria (UID203).

Thank you very much.

**Comment by dparks1134** [comment]
Hello. These results are pretty surprising. I wouldn't expect a genome with >80% of f__Rhizobiaceae markers to have <10% of the bacterial set. You can use the taxonomy_wf if you want to force CheckM to use a specific marker set.

**Comment by limin321** [comment]
> Hello. These results are pretty surprising. I wouldn't expect a genome with >80% of f__Rhizobiaceae markers to have <10% of the bacterial set. You can use the taxonomy_wf if you want to force CheckM to use a specific marker set.

Hi Parks,
Thank you so much for the immediate reply. I just ran: checkm tree_qa -o 1 -f output.txt out_put/

Bin Id     # unique markers (of 43)   # multi-copy   Taxonomy                                                                                                                           
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  assembly              8                    0         k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Rhizobiaceae;g__Agrobacterium;s__Agrobacterium_tumefaciens  

it is able to tell it is agrobacteria tumefacien. when run checkm lineage_set, why it uses k_Bacteria set, not s_Agrobacterium tumefaciens? 

When I use the same checkm command line to run my old agrobacterium sample, the program use f__Rhizobiaceae; it feels like ''checkm' somehow detected some difference between these two samples , thus use different marker gene set. the weird thing is all my 6 out of 7 strains from the second date sequence all use k_Bacteria; one use f__Rhizobiaceae but with 11.68% completeness. While all my old sequence genome with >80% completeness using f__Rhizobiaceae.  Would you have any better idea for this weird thing?  Thank you very much.

**Comment by limin321** [comment]
> Hello. These results are pretty surprising. I wouldn't expect a genome with >80% of f__Rhizobiaceae markers to have <10% of the bacterial set. You can use the taxonomy_wf if you want to force CheckM to use a specific marker set.

--------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id      Marker lineage    # genomes   # markers   # marker sets    0    1    2   3   4   5+   Completeness   Contamination   Strain heterogeneity  
---------------------------------------------------------------------------------------------------------------------------------------------------------
  assembly   Rhizobiaceae (4)       85         515           225        463   52   0   0   0   0        8.31            0.00               0.00          
---------------------------------------------------------------------------------------------------------------------------------------------------------

I ran checkm qa Rhizobiaceae.ms output_taxon ; still the completeness is still very low, 8.31 %. Does anyone has any thoughts?

**Comment by dparks1134** [comment]
This looks like a gene calling error to me. Are you nanopore genomes corrected in some fashion for the known indel issues with this sequencing platform?

**Comment by limin321** [comment]
yes. the sequence center did basecalling for me. the old data they use
guppy v2.0.5, the new data use 3.0.3HAC. is this what you ask? what does
gene calling mean?

I don't really understand your question. would you please explain it a
little bit more?
Thank you for your help. I really appreciate that.

**Comment by dparks1134** [comment]
The first step of CheckM is to run Prodigal to identified proteins. My understanding is that Nanopore data can have indel issues that result in poor identification of proteins, including missing start and stop codons. Perhaps the depth of your sequencing corrects for all this, but the extremely poor CheckM results is suggestive of proteins not being correctly identified by Prodigal and thus missed by CheckM. If you just run Prodigal to identify genes, does it find the number of proteins you would expect?
