### ISSUE TITLE
Error when running checkm lineage_wf

### ISSUE THREAD

**Issue by jeagull** [Ecogenomics/CheckM#202]
Dear all
I am trying to run checkm lineage_wf but I get this error when I try:
![スクリーンショット 2019-06-10 15 49 16](https://user-images.githubusercontent.com/13218402/59177706-d0bed280-8b97-11e9-9450-293a9b43e6c0.png)

Do you have any suggestions on what I should do?

Thank you very much in advance.

Ryohei

**Comment by dparks1134** [comment]
Hello. Best guess would be that CheckM is not able to find HMMER. Does CheckM run correctly if you give it a single genome for testing purposes? It would be good to narrow the issue down to a general CheckM issue or an issue with one of the input genomes.

**Comment by jeagull** [comment]
dparks1134, thanks for your reply.
I have tried checkm with one genome and I get the same issue.
I confirmed that I have met the requirements for installation. (hmmer, prodigal, and pplacer are all up to date)
Do you have any idea what's the problem?

**Comment by dparks1134** [comment]
Hello. It looks like you system doesn't have enough memory. I recommend a 64 Gb machine for general use or 16 Gb if you want to use the reduced tree (--reduced_tree). My testing suggest the reduced tree is fine, though I must admit I always use the full tree.

**Comment by jeagull** [comment]
Thanks for your comment. I have tried the --reduced_tree option, but I still get the same result. Does it mean I will have to increase the memory of the system?
And also, how would I be able to solve the lowest error ("No such file or directory: 'out/storage/tree/concatenated.tre'")?

**Comment by dparks1134** [comment]
How much memory does your machine have? With the reduced tree you still need at least 16 Gb and perhaps more if you are doing lots of genomes at once.

**Comment by jeagull** [comment]
I checked it now but it seems to have enough memory?
![スクリーンショット 2019-06-12 14 06 48](https://user-images.githubusercontent.com/13218402/59324791-69319000-8d1b-11e9-9ad3-e78099f0395d.png)
