### ISSUE TITLE
checkm should not always require write permissions for the database-folder

### ISSUE THREAD

**Issue by jvollme** [Ecogenomics/CheckM#207]
The database of checkm is not updated very often. In a multiuser environment it should not be rquired that every user has his own version of the database, but everyone should just acess a centrally deposited version of the database (e.g. under ```/opt/db/checkm```. 
However, checkm absolutely requires write permissions for each user to that folder. As an admin, i would prefer giving them read-access only. 
I do not understand why write acess is required if the database remains mostly unchanged anyway? And IF there ever is an official db-update for checkm, i could still install that globally for all users as admin
Would it be possible to remove this requirement?

**Comment by jvollme** [comment]
It is more of a wish list feature, not a serious issue. Maybe that could be an option sometime in future releases of v2 then? Glad to hear there will be a v2. Very much looking forward to it!

BTW (while we are on the topic of possible wish-lists for furture releases), will the v2 version eventually have an option to manually update or extend the official database (for taxonomic placement as well as bin-assessment)? I have noticed that checkm lineage_wf tends to classify saccharibacter as dehaloccocoides due to lack of representative saccaribacter markers in the database.

cheers,
John

**Comment by dparks1134** [comment]
CheckM v1 supports using a custom-defined set of HMMs to assess quality. This only works if you have a set of genomes you wish to process with the same marker genes though. I hope to improve on this, but the major aim will be a framework that we can provided updated marker sets for in a practical manner. The method used in CheckM v1 is too computationally intensive and requires only high-quality genomes be used which has proven problematic for providing new marker sets.
