### ISSUE TITLE
how to open correctly concatenated.tre file?

### ISSUE THREAD

**Issue by sashulkaSh** [Ecogenomics/CheckM#208]
hello

i run "checkm tree" with my ONE genome. MEGA6 and MEGA X couldn't open file concatenated.tre.

 programm TreeView X could open file, but it is not readable :
<img width="960" alt="Снимок" src="https://user-images.githubusercontent.com/44047620/61108079-9f456980-a4ab-11e9-961a-b2409675e764.PNG">

i try to open this file using R-script 

_library(ape)
setwd("~/Documents/obsh")
tree <- read.tree(file="concatenated.tre")
plot(tree))_

and  the result was also terrible: 

![image](https://user-images.githubusercontent.com/44047620/61108280-1da20b80-a4ac-11e9-96d5-84f77df9c55b.png)

so, how to open correctly concatenated.tre file?

**Comment by dparks1134** [comment]
I generally use Dendroscope.

**Comment by sashulkaSh** [comment]
> I generally use Dendroscope.

thank you!
