### ISSUE TITLE
Summary report output file from lineage workflow?

### ISSUE THREAD

**Issue by nixon444** [Ecogenomics/CheckM#209]
Hi Donovan,

Sorry if I have missed something from existing comments / issues, but is there no way of getting the completeness / contamination table that checkm pronts out after using the "qa" or "lineage_wf" commands as a .txt or .tsv file (or similar)? I am struggling to find a way to do this, and the current solution of screen-grabbing and manually entering results into a spreadsheet has gotten too laborious for the number of samples I am working with. If there is a flag I can use in either afforementioned commands, please could you give me an example command so I can adapt? If there is no way of doing any of this, something to add to a future version?

Cheers!

**Comment by dparks1134** [comment]
Yes - results can be written to file. Take a look at the `--file` and `--tab_table` flags.

**Comment by nixon444** [comment]
Thanks!
