### ISSUE TITLE
CheckM crashes while doing "[CheckM - analyze] Identifying marker genes in bins" and "[CheckM - qa] Tabulating genome statistics"

### ISSUE THREAD

**Issue by efr3m** [Ecogenomics/CheckM#21]
I analyzid few genome without any problem.
I then moved to a bigger dataset (48 genomes) amd the program crashed at the above mentioned steps. I guess tehre is a sort of problem with the ID of my seq, but I cannot figure out what.

    checkm taxonomy_wf family Bacillaceae -x faa comparative/ comparative_checkm
    
    *******************************************************************************
     [CheckM - taxon_set] Generate taxonomic-specific marker set.
    *******************************************************************************

      Marker set for Bacillaceae contains 418 marker genes arranged in 155 sets.
        Marker set inferred from 162 reference genomes.
     Marker set for Bacillales contains 319 marker genes arranged in 134 sets.
        Marker set inferred from 331 reference genomes.
      Marker set for Bacilli contains 250 marker genes arranged in 136 sets.
        Marker set inferred from 821 reference genomes.
      Marker set for Firmicutes contains 172 marker genes arranged in 99 sets.
        Marker set inferred from 1349 reference genomes.
      Marker set for Bacteria contains 104 marker genes arranged in 58 sets.
        Marker set inferred from 5449 reference genomes.

      Marker set written to: comparative_checkm/Bacillaceae.ms

      { Current stage: 0:00:04.462 || Total: 0:00:04.462 }

    *******************************************************************************
     [CheckM - analyze] Identifying marker genes in bins.
    *******************************************************************************

      Identifying marker genes in 48 bins with 1 threads:
        Finished processing 48 of 48 (100.00%) bins.
      Saving HMM info to file.

      { Current stage: 0:19:46.139 || Total: 0:19:50.602 }

      Parsing HMM hits to marker genes:
        Finished parsing hits for 48 of 48 (100.00%) bins.
      Aligning marker genes with multiple hits in a single bin:
        Finished processing 48 of 48 (100.00%) bins.

      { Current stage: 0:00:02.475 || Total: 0:19:53.077 }

      Calculating genome statistics for 48 bins with 1 threads:
    Process Process-6:ssing 0 of 48 (0.00%) bins.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python2.7/dist-packages/checkm/binStatistics.py", line 114, in __processBin
        codingDensity, translationTable, numORFs = self.calculateCodingDensity(binDir, genomeSize,     scaffoldStats)
      File "/usr/local/lib/python2.7/dist-packages/checkm/binStatistics.py", line 232, in     calculateCodingDensity
        codingBasePairs = self.__calculateCodingBases(aaGenes, seqStats)
      File "/usr/local/lib/python2.7/dist-packages/checkm/binStatistics.py", line 247, in __calculateCodingBases
        seqStats[scaffoldId]['# ORFs'] = seqStats[scaffoldId].get('# ORFs', 0) + 1
    KeyError: 'Prodigal_Seq_432'

      { Current stage: 0:00:00.263 || Total: 0:19:53.341 }

    *******************************************************************************
     [CheckM - qa] Tabulating genome statistics.
    *******************************************************************************

      Calculating AAI between multi-copy marker genes.

      Reading HMM info from file.
      Parsing HMM hits to marker genes:
        Finished parsing hits for 1 of 48 (2.08%) bins.
    Unexpected error: <type 'exceptions.KeyError'>
    Traceback (most recent call last):
      File "/usr/local/bin/checkm", line 717, in <module>
        checkmParser.parseOptions(args)
      File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1214, in parseOptions
        self.qa(options)
      File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 393, in qa
        bSkipOrfCorrection=options.bSkipOrfCorrection
      File "/usr/local/lib/python2.7/dist-packages/checkm/resultsParser.py", line 65, in analyseResults
        self.parseBinHits(outDir, hmmTableFile, bSkipOrfCorrection, bIgnoreThresholds,    evalueThreshold, lengthThreshold, binStats, seqStats)
      File "/usr/local/lib/python2.7/dist-packages/checkm/resultsParser.py", line 98, in parseBinHits
        resultsManager = ResultsManager(binId, self.models[binId], bIgnoreThresholds,     evalueThreshold, lengthThreshold, binStats[binId], seqStats[binId])
    KeyError: 'NC017196

**Comment by dparks1134** [comment]
Hello,

If you are providing CheckM with genes in amino acid space, you need to pass the <code>--genes</code> flag. By default, CheckM assume a genome in nucleotide space.

Cheers,
Donovan

**Comment by efr3m** [comment]
Right.
Sorry, I overlooked this flag.

Thanks very much!
