### ISSUE TITLE
Strain heterogeneity relative to contamination

### ISSUE THREAD

**Issue by YiJessePi** [Ecogenomics/CheckM#212]
Hi,
Thanks for the very useful tool!
I'm using checkM statistics to estimate contamination and strain heterogeneity. If I recall correctly it seems that the strain heterogeneity is calculated out of the contaminated sets of marker genes. So the strain heterogeneity should be taken into account in the context of contamination.
(For example- low contamination levels with high heterogeneity means that we have  low contamination in strain levels and should be preferred about a case with high contamination with low strain heterogeneity).
1. Is there any suggestion for any measurement that take both into account>
2. Is there a way to get the fraction of marker genes that are have multi-copies and suspected as contaminated?

Best!

**Comment by dparks1134** [comment]
Hello,

1. Not that I know of.
2. The primary output table of CheckM indicates the number of marker genes identified 0, 1, 2, .., 5+ times:
https://github.com/Ecogenomics/CheckM/wiki/Reported-Statistics#qa

Cheers,
Donovan
