### ISSUE TITLE
checkm database update?

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [Ecogenomics/CheckM#219]
Hi,

I saw on another issue (#99) that you were working on a database update, but had been stymied due to the random quality of genomes being added to public databases. Any luck since then? The current CheckM database is a bit old (2015).

I am happy to wait for CheckM2 as well. Any ETA for its release/publication?

Thanks for all your hard work on this.

**Comment by dparks1134** [comment]
Hello. I do not plan to release an updated database for CheckM v1. The challenge is that CheckM v1 assumes the genomes used to establish the marker sets are of high quality. With the majority of new novelty being MAGs or high-throughput, draft isolates, a new strategy is needed to make use of these genomes for calculating marker sets. This will be the main enhancement of CheckM v2. I am planning to do this, but progress has been slow. Earliest release would be end of this year.

**Comment by jdwinkler-lanzatech** [comment]
Yes, I've had a similar problem trying to use MAGs for, well, anything, so makes perfect sense. I'll keep an eye out for the new release.
