### ISSUE TITLE
 ERROR: No bins found. Check the extension (-x) used to identify bins.

### ISSUE THREAD

**Issue by cssulliv** [Ecogenomics/CheckM#221]
Hi,

So I am have been attempting to analyze my bins using the lineage_wf workflow using the script below

`checkm lineage_wf -t 15 -x fa /home/cssulliv/pelagibacter_lts/001_2011Samples/01_RAWDATA/11_CheckM/NitroMAGs_1362A_B_round2_refined  /home/cssulliv/pelagibacter_lts/001_2011Samples/01_RAWDATA/11_CheckM`

But I keep getting this error

`INFO: [CheckM - tree] Placing bins in reference genome tree.`
`[2019-08-27 20:19:41] ERROR: No bins found. Check the extension (-x) used to identify bins.`

I use the absolute path for both bin and output directories and have tried using -x .fa but still get the same error. 

Do you have any suggestion on how I can go about fixing the error?

Best,
C

**Comment by bingbingl7828** [comment]
Hi, 

I have the same problem in my current job, I would like to ask how did you solve this problem?

Best,
L

**Comment by YeGuoZJU** [comment]
> Figured it out! :)

How to solve it? I also get the same error

**Comment by liying-lan** [comment]
How to solve it? I also get the same error
