### ISSUE TITLE
Forcing all bins to be classified as "root"

### ISSUE THREAD

**Issue by ursky** [Ecogenomics/CheckM#224]
Is it possible to force CheckM to skip the taxonomic estimation step and treat all bins as being unclassified/root? It is important for me to evaluate all the bins with the same set of single marker genes. Is this possible?

**Comment by dparks1134** [comment]
Take a look at the `taxonomy_wf`. This allows genomes to be evaluated with a fixed taxonomic marker set (e.g., bacterial or archaeal).

**Comment by ursky** [comment]
Thanks, Donovan. I tried running `checkm taxonomy_wf -x fa life root bins bins.checkm`, but it does not work: `IOError: [Errno 2] No such file or directory: 'bins.checkm/root.ms'`. Is there a way to run with the root universal markers without specifying Bacteria/Arcahaea?

**Comment by ursky** [comment]
Edit: I found the solution. The highest-order taxonomy name is "Prokaryote", not "root". So the correct command that works is actually `checkm taxonomy_wf -x fa life Prokaryote bins bins.checkm`.

**Comment by ursky** [comment]
Thanks, I am fully aware. However I need this for an application where I can rapidly re-calculate the metrics of bins as they change/merge/split. A proper CheckM run will be run at the end. 

I have another question if you don't mind. I am trying to reproduce the completion and contamination metrics produced by CheckM from the original file `marker_gene_stats.tsv`, however I am having a really hard time - the numbers are close, but off in many cases. My approach is to go over the genes identified in each bin and compare them to the full marker gene set from the "Prokaryotes" lineage:

```
marker_set = [set(['PF01000.21', 'PF00416.17', 'PF01193.19', 'PF00411.14']), set(['PF00297.17', 'PF00276.15', 'PF00252.13', 'PF00237.14', 'PF00831.18', 'PF00203.16', 'PF00366.15', 'PF00181.18', 'PF00573.17', 'PF00189.15', 'PF03947.13']), set(['PF04997.7', 'PF04983.13', 'PF04560.15', 'PF04565.11', 'PF00562.23', 'PF00623.15', 'PF05000.12', 'PF04563.10', 'PF04561.9']), set(['PF00410.14', 'PF00281.14', 'PF00673.16', 'PF03719.10', 'PF00333.15', 'PF00861.17', 'PF00347.18', 'PF00238.14']), set(['PF00177.16', 'PF00164.20']), set(['PF00687.16', 'PF00298.14', 'PF03946.9']), set(['PF00572.13', 'PF00380.14']), set(['TIGR00392']), set(['PF01509.13']), set(['PF00162.14']), set(['PF00466.15']), set(['TIGR00468']), set(['PF13184.1']), set(['PF02978.14']), set(['PF11987.3']), set(['TIGR00967']), set(['PF00338.17']), set(['PF00318.15']), set(['PF03484.10']), set(['TIGR00755']), set(['TIGR00344']), set(['PF08459.6']), set(['TIGR00329']), set(['PF00312.17'])]
```

Could you point me in the direction of the formula you use to calculate completion and contamination from this information? What happens if one of the 24 sets is partially complete, or partially contaminated?

This is my crude code to attempt to calculate the metrics, but like I said, the values are somewhat off from the ones produced by CheckM:
```
#!/usr/bin/env python2

import sys
import numpy as np

marker_set = [set(['PF01000.21', 'PF00416.17', 'PF01193.19', 'PF00411.14']), set(['PF00297.17', 'PF00276.15', 'PF00252.13', 'PF00237.14', 'PF00831.18', 'PF00203.16', 'PF00366.15', 'PF00181.18', 'PF00573.17', 'PF00189.15', 'PF03947.13']), set(['PF04997.7', 'PF04983.13', 'PF04560.15', 'PF04565.11', 'PF00562.23', 'PF00623.15', 'PF05000.12', 'PF04563.10', 'PF04561.9']), set(['PF00410.14', 'PF00281.14', 'PF00673.16', 'PF03719.10', 'PF00333.15', 'PF00861.17', 'PF00347.18', 'PF00238.14']), set(['PF00177.16', 'PF00164.20']), set(['PF00687.16', 'PF00298.14', 'PF03946.9']), set(['PF00572.13', 'PF00380.14']), set(['TIGR00392']), set(['PF01509.13']), set(['PF00162.14']), set(['PF00466.15']), set(['TIGR00468']), set(['PF13184.1']), set(['PF02978.14']), set(['PF11987.3']), set(['TIGR00967']), set(['PF00338.17']), set(['PF00318.15']), set(['PF03484.10']), set(['TIGR00755']), set(['TIGR00344']), set(['PF08459.6']), set(['TIGR00329']), set(['PF00312.17'])]


markers = {}
for i,marker in enumerate(marker_set):
	for gene in marker:
		markers[gene]=i

max_tally = [0] * 24
for gene in markers:
	max_tally[markers[gene]]+=1


for line in open("metabat2_bins.checkm/storage/marker_gene_stats.tsv"):
	bin_name = line.split()[0]
	data = " ".join(line.strip().split()[1:])
	data=eval(data)

	genes = []
	marker_tally = [0] * 24
	for contig in data:
		for gene in data[contig]:
			marker = markers[gene]
			marker_tally[marker]+=1
			genes.append(gene)

	comp=0
	cont=0
	for i,n in enumerate(max_tally):
		if marker_tally[i]!=0:
			comp+=1
		if marker_tally[i]>n:
			cont+=marker_tally[i]-n

	print "\t".join([ bin_name, str(100.0*comp/24)[:5], str(100.0*cont/24)[:5] ])
```

**Comment by dparks1134** [comment]
The formula's used by CheckM are in the Genome Research ms: https://www.ncbi.nlm.nih.gov/pubmed/25977477
