### ISSUE TITLE
Missed marker that is actually not missing

### ISSUE THREAD

**Issue by deoliveira86** [Ecogenomics/CheckM#225]
Hello,

I used checkM to evaluate the completeness of a closed bacterial genome and after following the Taxonomy-specific workflow I got some interesting results. The bin_qa_plot tells me that two house-keeping genes are missing and one is marked as "contamination" (results below).

```
Gammaproteobacteria (2) 1167 280 178 2 277 1 0 0 0 98.88 0.56 0.00
```

Looking closely to the reference genome I could confirm that the "contamination" gene is a true duplication on the gammaproteobacteria genome I've been working. One of the missing housekeeping gene is indeed missing, however the other not. I annotated the genome with prokka and I could see that this gene in question is there, and more surprisingly even the similarity searches performed by checkM identified a match between the profile-HMM TIGR00611 and my target bacteria with significant full sequence and best 1 domain evalues (check below).  

```
MIKGPHBK_01696       -            616 TIGR00611            TIGR00611    365   3.4e-09   33.8   1.6   1   2   1.4e-07   5.7e-05   19.9   0.0     1    82     1    86     1   111 0.75 DNA replication and repair protein RecF

MIKGPHBK_01696       -            616 TIGR00611            TIGR00611    365   3.4e-09   33.8   1.6   2   2   3.4e-05     0.014   12.1   0.1   274   325   521   573   502   587 0.81 DNA replication and repair protein RecF
 ```

Is there an explanation for this checkM behaviour? Why this specific gene was not marked as present during the checkM qa step? I played around with different e-values in the qa execution, used the flag `--ignore_thresholds`, however I could not "force" the checkM to mark this gene as present. Maybe this is a naive question, however I'm curious to understand how the evaluation of the markers is performed in the software.

Best,
André

Additional Information:
CheckM version used in the analysis: `1.0.18`

**Comment by deoliveira86** [comment]
Hello Donavan,

I don't know what is the exact noise cutoff value, but when I ran hmmsearch invoking the `-cut_nc` using the TIGR00611.hmm against my reference no hit was reported.So, I am assuming that is the reason this gene was not marked as present in my final bin_qa_plot report.

Thanks for the help,
André

**Comment by BlueGirl15** [comment]
I got the same issue with checkm, I have got 58 genes missing from a genome but they are all shown to produce hits in the hmmer_analysis.txt file. What could be the reason for this?

**Comment by dparks1134** [comment]
Hi. CheckM looks for the best HMM hit for each gene. A gene can have similarity to many HMM models, but only the best matching model is ultimately used to annotate the gene.

**Comment by BlueGirl15** [comment]
![image](https://user-images.githubusercontent.com/61807957/76347647-5a453180-62dd-11ea-81d1-5755d1e121b4.png)
![image](https://user-images.githubusercontent.com/61807957/76347776-8660b280-62dd-11ea-9bde-f97f8d996f7a.png)

In the above case, the first hit seems to have lower E-value and higher bit score for the given CDS. There are no other hits for the CDS. But still, why is the upper gene shown to be missing? I would very much appreciate your response.

**Comment by dparks1134** [comment]
Hi. There could be a few reasons. Is the bitscore above the -cut_nc threshold for this TIGRfam HMM? Is TIGR00132 a marker gene for your genome (CheckM only reports expected marker genes, not all genes)? If you can email me the genome you are processing, the CheckM version you are using, and the commands you are running I can explore a bit further?

**Comment by dparks1134** [comment]
Just checked and the noise cutoff for TIGR00132 is 399.35:
http://tigrfams.jcvi.org/cgi-bin/HmmReportPage.cgi?acc=TIGR00132

I believe the bit score being report here is only 219.0. If so, it will not be reported by CheckM. That is, your gene shows sequence similarity to this HMM model, but not enough to actually assign it to TIGR00132 and annotate it as such.
