### ISSUE TITLE
Access denied to download pre-calculated CheckM data

### ISSUE THREAD

**Issue by parikhhi** [Ecogenomics/CheckM#226]
Hi, 
I am unable to download the pre-calculated data files at the following URL - 
https://data.ace.uq.edu.au/public/CheckM_databases/

Any alternate ways to access the files? 

Thanks.

**Comment by dparks1134** [comment]
Hi. Unfortunately, our servers are down at the moment. It is a long weekend in Australia, but we hope to have them back up in the next few days. Apologies for the inconvenience.

**Comment by parikhhi** [comment]
No worries. Thanks for the update.

**Comment by franciscozorrilla** [comment]
Hi, I was having the same issue but I was able to recover the database from my previous cluster. 
As described here #228 I have uploaded the database to google drive if you need it urgently, although I am not sure if it is the latest version.
https://drive.google.com/file/d/1iTtPwt3N_0jA-cmcExapsB28D2sPOI1n/view?usp=sharing

Hope it helps. 
Best wishes, FZ

**Comment by parikhhi** [comment]
This is extremely helpful! Thanks. 
Hope the servers are back online (soon ... ) to access the latest version.  
Cheers, HP

**Comment by dparks1134** [comment]
Servers are back up.
