### ISSUE TITLE
problem when I install chekm

### ISSUE THREAD

**Issue by Huangpq2019** [Ecogenomics/CheckM#229]
I use "python setup.py install" to install the CheckM-1.0.18, and the install_log.txt can be see below.
When I use "checkm" to test checkm, it happen something wrong:
![checkm](https://user-images.githubusercontent.com/52695850/67195586-c5c05c80-f42b-11e9-81bd-1c284e18d0f8.png)
Can you help to solve this problem?
[install_log.txt](https://github.com/Ecogenomics/CheckM/files/3750061/install_log.txt)

**Comment by dparks1134** [comment]
Hello. I would recommend installing CheckM via pip:
https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

**Comment by dparks1134** [comment]
Closed due to inactivity.
