### ISSUE TITLE
CheckM fails with invalid syntax

### ISSUE THREAD

**Issue by iquasere** [Ecogenomics/CheckM#231]
Greetings

I've tried to use CheckM, installed it with conda and created an environment with python 2.7. Still, when running checkm, I always get
```
  File "/home/jsequeira/anaconda3/bin/checkm", line 107
    print "%s removed" % (filename)
                     ^
SyntaxError: invalid syntax
```
Is the conda version outdated?

**Comment by dparks1134** [comment]
Hi. This error indicates CheckM is being run with Python 3.

**Comment by iquasere** [comment]
Problem is I created an environment for Python 2.7, with
```
conda activate py2
```
running python --version
gives me
```
Python 2.7.15
```
and /home/user/anaconda3/bin/checkm gives
```
  File "/home/jsequeira/anaconda3/bin/checkm", line 107
    print "%s removed" % (filename)
                     ^
SyntaxError: invalid syntax
```
But probably anaconda is still using python 3.

**Comment by dparks1134** [comment]
This error really points to Python 3 being used as the indicated syntax is valid for Python 2, but invalid for Python 3. This type of syntax error is common. I'm not familiar with Anaconda so can't help on that front.
