### ISSUE TITLE
Checkm v1.0.18 and '--force_write'

### ISSUE THREAD

**Issue by alienzj** [Ecogenomics/CheckM#233]
Hello, CheckM team member.
I found there are no '--force_write' parameter in `checkm lineage_wf` from the CheckM v1.0.18 release, but this [commit](https://github.com/Ecogenomics/CheckM/commit/f9ad7a45bba9a45830a7c1e8967934ecdffb4e92) added `--force_write` paramerer.
```bash
$ conda list | grep checkm
checkm-genome             1.0.18                     py_0    bioconda

$ checkm lineage_wf xxx
xxx
checkm: error: unrecognized arguments: --force_overwrite
```

**Comment by dparks1134** [comment]
Hello. Thank you for bringing this to my attention. CheckM v1.0.18 is being retired on Dec. 1 when CheckM will move over to Python 3. I will look to implement the --force_overwrite feature in the Python 3 version.

**Comment by dparks1134** [comment]
Hi. Actually, I consulted the full version log and starting with v1.0.15 CheckM allows one to specify an existing directory and the --force_overwrite parameter was removed.
