### ISSUE TITLE
Using Custom Marker Genes

### ISSUE THREAD

**Issue by rotoscan** [Ecogenomics/CheckM#234]
Dear Parks,

thank you for this amazing tool. We use it a lot in our group.

I have a question regarding the usage of Custom Marker Genes (https://github.com/Ecogenomics/CheckM/wiki/Workflows#using-custom-marker-genes). Should the HMM files be generated with the amino acid or nucleotide sequences from the genes?

I digged into the installation files and I could only find hmm files generated with amino acid sequences, but I wanted to double-check.

Thanks again!

Best
Rodolfo

**Comment by dparks1134** [comment]
Hi Rodolfo,

Glad to hear you are finding CheckM useful. Custom HMMs should be generated with amino acids.

Cheers,
Donovan

**Comment by rotoscan** [comment]
Hello Donovan, 

reopening this issue because I have a doubt. I have a set of genes in 43 files. Each file has around 130 sequences in that were aligned altogether (msa format). Now I have to generate the HMM model using hmmbuild, correct? However, should I generate then 43 HMM files? Or should I run the multiple-sequence alignment on all the sequences together? 
I would appreciate any info on  how to do the process properly.

Thank a lot!

Best
Rodolfo

**Comment by dparks1134** [comment]
Hi Rodolfo. CheckM requires a single file that contains all the HMM models you wish to use for evaluating your genomes. Individual HMMs can be concatenated into a single multi-HMM file. It has been a long time since I built custom HMMs, but I believe the usual workflow is to align homologous genes -> build an HMM for each gene (i.e. 43 HMM files in your case) -> combine HMMs into a single multi-HMM file.

**Comment by rotoscan** [comment]
Hello Donovan,

Thanks a lot. It worked perfectly.

All the best
Rodolfo

**Comment by lalalagartija** [comment]
Hi ! I also want to build a custom database by just adding some markers to the original checkm database. How do I deal with the tree taxonomy and metadata ? Can I get the same lineage output if I build my custom database ?

**Comment by dparks1134** [comment]
Hi. A customer marker set can be used if desired as discussed above, but CheckM does not support extending the current reference tree or the set of markers being used. We are working on a CheckM v2 which will have regularly updated marker sets, but this is still in development.
