### ISSUE TITLE
Single-copy marker question

### ISSUE THREAD

**Issue by ursky** [Ecogenomics/CheckM#236]
Hey Donovan, I have a question about the taxon-specific marker gene sets CheckM uses. I am talking about the reference "tree" containing the optimized marker genes for different taxa. Does the marker set for a given taxon also include all the gene IDs from the higher order taxon that contains it? In other words, if we have the taxon "Archaea;Euryarchaeota;Aciduliprofundum", does it also contain _all_ the genes from "Archaea;Euryarchaeota", and likewise "Archaea". Or are there cases where, say, some "Archaea;Euryarchaeota" marker IDs will not be in Archaea;Euryarchaeota;Aciduliprofundum" (or be under a different name)? Any insight would be helpful.

**Comment by dparks1134** [comment]
Hi. There can be marker genes for "Archaea;Euryarchaeota" that are not part of the "Archaea;Euryarchaeota;Aciduliprofundum" marker set.
