### ISSUE TITLE
Extracting  complete "lineage" information for each bin from "checkm lineage_wf" command

### ISSUE THREAD

**Issue by Jigyasa3** [Ecogenomics/CheckM#241]
hey @dparks1134 

Is it possible to get information about complete lineage from` checkm lineage_wf` command?
The `lineage.ms` file lists the markers used to assign taxonomy and the taxonomic level to which the bin can be assigned to. Is it possible to get the whole hierarchical information preceding the taxonomic annotation?
For example-
My bin gets assigned to `f__Rhodocyclaceae`, I want to get phlya, class,order-level information also.

**Comment by dparks1134** [comment]
Yes. Take a look at output option 3 for the `qa` command:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa
