### ISSUE TITLE
checkm data setRoot

### ISSUE THREAD

**Issue by vsblancato** [Ecogenomics/CheckM#242]
I have installed checkM in Ubuntu 18.04.3 LTS. When i try to apply checkm data setRoot I get the following messages:
checkm data setRoot /home/victor/checkmdata
[2019-12-18 13:07:49] INFO: CheckM v1.1.1
[2019-12-18 13:07:49] INFO: checkm data setRoot /home/victor/checkmdata
[2019-12-18 13:07:49] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/home/victor/checkmdata] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/home/victor/checkmdata] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
[2019-12-18 13:07:51] ERROR: Path to the CheckM reference data must be specified.

The last ERROR is confusing me, since if i run checkm i get:
                ...::: CheckM v1.1.1 :::...

  Lineage-specific marker set:
    tree         -> Place bins in the reference genome tree
    tree_qa      -> Assess phylogenetic markers found in each bin
....

So the set root command seems to have worked since i don`t get the message indicating that i should create the CheckM data.

Any advice?
Thanks a lot.

**Comment by dparks1134** [comment]
Hi. I think this is just an erroneous error message. If CheckM runs it is finding the required reference data.

**Comment by vsblancato** [comment]
Hello,
thanks for your answer. Also checkm test worked fine.
Thanks a lot.

**Comment by dparks1134** [comment]
Fixed in v1.1.2.

**Comment by jolespin** [comment]
Where is the checkm manifest file? Alternatively, is there an environment variable I can specify if there is an existing checkm database?
