### ISSUE TITLE
completeness calculate

### ISSUE THREAD

**Issue by ucassee** [Ecogenomics/CheckM#243]
Dear developer,
       I want to know the how checkm calculate Completeness. The following is the result of ckeckm. Is Completeness calculated by `1`/`# marker sets`?
```
Bin Id	Marker lineage	# genomes	# markers	# marker sets	0	1	2	3	4	5+	Completeness	Contamination	Strain heterogeneity
B100T1B8.fasta	k__Bacteria (UID2565)	2921	143	88	19	124	0	0	0	0	84.35	0.00	0.00
B100T1L10.fasta	k__Bacteria (UID1452)	924	160	109	43	116	1	0	0	0	64.65	0.92	0.00
```

**Comment by dparks1134** [comment]
Hi. You can find the method used to calculate completness in the CheckM manuscript:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4484387/
