### ISSUE TITLE
Latest version of CheckM database

### ISSUE THREAD

**Issue by yonist** [Ecogenomics/CheckM#244]
The file that the Wiki instructed to download is from 2015. Is there a new version of it somewhere ?

https://data.ace.uq.edu.au/public/CheckM_databases/

Thanks,
Yoni

**Comment by dparks1134** [comment]
The 2015 database is the latest version.

**Comment by yonist** [comment]
Are there any instruction on how to prepare a new database?

**Comment by dparks1134** [comment]
You can specify a user defined set of marker genes as described here:
https://github.com/Ecogenomics/CheckM/wiki/Workflows#using-custom-marker-genes

There isn't a way to update the entire CheckM reference database. We are actively working on CheckM v2 which will support updating of the reference database, but this is still in early development.
