### ISSUE TITLE
Issue with matplotlib

### ISSUE THREAD

**Issue by sushanta26** [Ecogenomics/CheckM#246]
After upgrading checkm I am facing following error . please guide me if I am making any mistake.

File "/home/sdas/.linuxbrew/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/sdas/.linuxbrew/opt/python/lib/python3.7/site-packages/checkm/main.py", line 52, in <module>
    from checkm.plot.gcPlots import GcPlots
  File "/home/sdas/.linuxbrew/opt/python/lib/python3.7/site-packages/checkm/plot/gcPlots.py", line 24, in <module>
    from checkm.plot.AbstractPlot import AbstractPlot
  File "/home/sdas/.linuxbrew/opt/python/lib/python3.7/site-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
ModuleNotFoundError: No module named 'matplotlib'

**Comment by dparks1134** [comment]
Hi. You can install matplotlib with `pip3 install matplotlib`.

**Comment by sushanta26** [comment]
Hi thanks for your reply.
Matplotlib is already installed in my system.

checkm                                         pyparsing-2.4.0.dist-info
checkm_genome-1.1.2.dist-info                  pyparsing.py
cycler-0.10.0.dist-info                        pysam
cycler.py                                      pysam-0.15.2.dist-info
dateutil                                       _pytest
dendropy                                       pytest-4.6.3.dist-info
DendroPy-4.4.0.dist-info                       pytest.py
easy_install.py                                python_dateutil-2.8.0.dist-info
~heckm                                         pytz
~heckm_genome-1.0.13.dist-info                 pytz-2019.1.dist-info
importlib_metadata                             _rinterface_cffi.py
importlib_metadata-1.3.0.dist-info             rpy2
~io                                            rpy2-3.0.4.dist-info
~iopython-1.73.dist-info                       scipy
~ioSQL                                         scipy-1.3.0.dist-info
jinja2                                         setuptools
Jinja2-2.10.3.dist-info                        setuptools-41.0.1-py3.7.egg-info
kiwisolver-1.1.0.dist-info                     simplegeneric-0.8.1.dist-info
kiwisolver.cpython-37m-x86_64-linux-gnu.so     simplegeneric.py
markupsafe                                     sitecustomize.py
MarkupSafe-1.1.1.dist-info                     six-1.12.0.dist-info
matplotlib-3.1.2.dist-info                     six.py
matplotlib-3.1.2-py3.7-nspkg.pth               six.pyc
more_itertools                                 wcwidth
more_itertools-7.0.0.dist-info                 wcwidth-0.1.7.dist-info
mpl_toolkits                                   wheel
numpy                                          wheel-0.33.4-py3.7.egg-info
numpy-1.16.4.dist-info                         zipp-0.5.1.dist-info
packaging                                      zipp.py

**Comment by dparks1134** [comment]
Hi. My best guess is that matplotlib is not install for the version/instance of Python that is executing CheckM. It appears CheckM is being running by the Python 3.7 interpreter install via .linuxbrew. Is matplotlib install for this version/instance of Python?

**Comment by sushanta26** [comment]
You are right, how could I get around this ,should I uninstall checkm and install it again .

**Comment by dparks1134** [comment]
Probably the easiest solution is to install matplotlib for linuxbrew. I'm not familiar with linuxbrew so can't provide any guidance on how that might be done.

**Comment by sushanta26** [comment]
upgrading checkm showing several dependencies issues. Could you please give me some suggestion so that I can install the previous python 2.7 checkm version using pip command instead of pip3.

**Comment by sushanta26** [comment]
after installing checkm using pip3 command it shows following error ,please guide me where I am making mistake


Process Process-2:ssing 0 of 1 (0.00%) bins.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdas/.local/lib/python3.6/site-packages/checkm/markerGeneFinder.py", line 115, in __processBin
    prodigal.run(binFile, bNucORFs)
  File "/home/sdas/.local/lib/python3.6/site-packages/checkm/prodigal.py", line 104, in run
    prodigalParser = ProdigalGeneFeatureParser(gffFile)
  File "/home/sdas/.local/lib/python3.6/site-packages/checkm/prodigal.py", line 191, in __init__
    self.__parseGFF(filename)
  File "/home/sdas/.local/lib/python3.6/site-packages/checkm/prodigal.py", line 220, in __parseGFF
    start = int(lineSplit[3])
IndexError: list index out of range

[2020-01-17 19:23:39] INFO: Saving HMM info to file.
[2020-01-17 19:23:39] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2020-01-17 19:23:39] INFO: Extracting marker genes to align.
[2020-01-17 19:23:39] ERROR: Models must be parsed before identifying HMM hits.
