### ISSUE TITLE
Analyzing files with similar extensions

### ISSUE THREAD

**Issue by jimmyliu1326** [Ecogenomics/CheckM#247]
My input directory contains two files: contigs.fa and contigs.gfa. When the option -x fa is used, the tool tries to analyze both files rather than only the .fa file. Is the partial matching of file extensions intended?

**Comment by dparks1134** [comment]
Hi. Thanks for bringing this to my attention. This behaviour isn't clear. Can you get the desired result using `-x .fa` to explicitly indicate you want the period to be used to filter the files to be processed?

**Comment by jimmyliu1326** [comment]
Great! That does resolve the issue, thanks!
