### ISSUE TITLE
Checkm fail to run, though installed.

### ISSUE THREAD

**Issue by limin321** [Ecogenomics/CheckM#249]
Hi  
I download and install checkm through this link  https://hackmd.io/cMQgeGF6TOuuLJvCjQyo0Q  
when run checkm -h ,  checkm seems working. However, when I run the test data, it gave me the following error messager. 
<img width="1030" alt="Screen Shot 2020-03-23 at 3 08 38 PM" src="https://user-images.githubusercontent.com/42760669/77367832-2f64cf80-6d18-11ea-8520-3052de803173.png">

I checked the phylo.hmm file is there in the hmms folder.

Can anyone please help me with this issue.

Your help is really appreciated.

Best

**Comment by dparks1134** [comment]
I don't see an obvious issue from the error message. Can you verify that the latest version of CheckM has been install (v1.1.2) and that your machine has at least 40 GB of memory?

**Comment by limin321** [comment]
> I don't see an obvious issue from the error message. Can you verify that the latest version of CheckM has been install (v1.1.2) and that your machine has at least 40 GB of memory?

my checkm version is .::: CheckM v1.0.7 :::...
I do have more than 40 GB of memory, actually more than 1 T of memory.  but when I run checkm -h, it seems working .
<img width="656" alt="Screen Shot 2020-03-23 at 3 59 00 PM" src="https://user-images.githubusercontent.com/42760669/77370923-380cd400-6d1f-11ea-93ce-3032ec9be0db.png">

How to update my checkm version?

**Comment by dparks1134** [comment]
Are you running on OS X? I don't think the latest version of CheckM is available for OS X via Conda. Perhaps you can try installing via pip:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements

**Comment by limin321** [comment]
> I don't see an obvious issue from the error message. Can you verify that the latest version of CheckM has been install (v1.1.2) and that your machine has at least 40 GB of memory?

it is really confusing that 
<img width="778" alt="Screen Shot 2020-03-23 at 4 06 42 PM" src="https://user-images.githubusercontent.com/42760669/77371327-4dcec900-6d20-11ea-8c3f-1c4888e4af4a.png">

Then you mention "If you use Bioconda, you may find these instructions useful."  so I click the instrucitons, and installed following those instructions. However, the version by default is checkm 1.0.7.  and 
<img width="701" alt="Screen Shot 2020-03-23 at 4 09 22 PM" src="https://user-images.githubusercontent.com/42760669/77371502-ac944280-6d20-11ea-8d7b-80ea3731e411.png">

here, you point back that checkm data setRoot  doesn't need to specify a directory.  While when I ran this command, it does ask me to tell which directory I use.  Could you please help me clarify this?

**Comment by limin321** [comment]
> Are you running on OS X? I don't think the latest version of CheckM is available for OS X via Conda. Perhaps you can try installing via pip:
> https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements

yes, I do run in a mac.  Is there anyway I can just make the old version checkm 1.0.7 work in my mac? Thanks a lot.

**Comment by dparks1134** [comment]
Hi. Thanks for the feedback. The Bioconda install for CheckM and the instructions on how to install CheckM using Bioconda are done by generous individuals in our community. I'm not that familiar with Bioconda so can't directly help with installing CheckM in this manner. I'm not sure what to suggest for getting v1.0.7 working on your system. The error message suggests an issue with phylo.hmm so perhaps you can try re-installing this data file? You can also try installing CheckM using pip.

**Comment by dparks1134** [comment]
Hi. It does look like there is a Bioconda package for CheckM v1.1.2 which is cross platform. Can you `force` this version to install instead of v1.0.7?
https://anaconda.org/bioconda/checkm-genome

I think the command is something like `conda install -c bioconda checkm-genome=1.1.2`

**Comment by limin321** [comment]
> Are you running on OS X? I don't think the latest version of CheckM is available for OS X via Conda. Perhaps you can try installing via pip:
> https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements

Hi 

I am trying to install through pips now. 
<img width="794" alt="Screen Shot 2020-03-23 at 4 33 49 PM" src="https://user-images.githubusercontent.com/42760669/77372916-16fab200-6d24-11ea-9f32-ef282bfb0b44.png">

The data files in the above link is also from 2015, the same one I tried before. Is this the right data files for the new version of checkm, I just want to confirm.  Thanks a lot.


> conda install -c bioconda checkm-genome=1.1.2

Thanks.  I tried your command, then got this error message,
![image](https://user-images.githubusercontent.com/42760669/77381513-4e288d80-6d3b-11ea-9f98-75b17087ea75.png)


Then I tried pip to install, then got another error message, 
![image](https://user-images.githubusercontent.com/42760669/77381563-7617f100-6d3b-11ea-9489-2ff5b68432a0.png)


Then the interesting thing is the phylo.hmm file I printed out is in the different location (see below) as the one in the error message.
<img width="465" alt="Screen Shot 2020-03-23 at 7 23 14 PM" src="https://user-images.githubusercontent.com/42760669/77381782-efafdf00-6d3b-11ea-80c0-2d032668c788.png">

I even don't know why it is in the hidden file. 
Do you any explaination?
Thanks.

**Comment by dparks1134** [comment]
Yes, the 2015 CheckM reference data is the most recent. It does appear the issue is with CheckM correctly finding the reference data. Can you verify that the file `/Usersdklabuser/.checkm/hmms/phylo.hmm` exists and that is is not an empty file?

**Comment by limin321** [comment]
Hi
Based on the error msg of not being able to find phylo.hmm, so I copied
everything in the checkm folder downloaded to this location,
/Usersdklabuser/.checkm/hmms/
It doesn't complain about phylo.hmm anymore. However,  I got a new error
message, couldn't find pplacer,

(base) KluepfelLabMBP01:test_data dklabuser$ checkm lineage_wf -f
Checkm.txt -x fa ./bin/ ./bin/SCG2/

[2020-03-24 10:27:51] INFO: CheckM v1.1.2

[2020-03-24 10:27:51] INFO: checkm lineage_wf -f Checkm.txt -x fa ./bin/
./bin/SCG2/

[2020-03-24 10:27:51] INFO: [CheckM - tree] Placing bins in reference
genome tree.

[2020-03-24 10:27:52] INFO: Identifying marker genes in 1 bins with 1
threads:

    Finished processing 1 of 1 (100.00%) bins.

[2020-03-24 10:28:10] INFO: Saving HMM info to file.

[2020-03-24 10:28:10] INFO: Calculating genome statistics for 1 bins with 1
threads:

    Finished processing 1 of 1 (100.00%) bins.

[2020-03-24 10:28:10] INFO: Extracting marker genes to align.

[2020-03-24 10:28:10] INFO: Parsing HMM hits to marker genes:

    Finished parsing hits for 1 of 1 (100.00%) bins.

[2020-03-24 10:28:10] INFO: Extracting 43 HMMs with 1 threads:

    Finished extracting 43 of 43 (100.00%) HMMs.

[2020-03-24 10:28:10] INFO: Aligning 43 marker genes with 1 threads:

    Finished aligning 43 of 43 (100.00%) marker genes.

[2020-03-24 10:28:11] ERROR: Make sure pplacer is on your system path.


  Controlled exit resulting from an unrecoverable error or warning.

(base) KluepfelLabMBP01:test_data dklabuser$ cd ..



I had this issue yesterday, so I download pplacer from source code, and
also put it in the checkm folder, here it is.

(base) KluepfelLabMBP01:checkm dklabuser$ cd pplacer-1.1.alpha19/

(base) KluepfelLabMBP01:pplacer-1.1.alpha19 dklabuser$ ls

CHANGELOG README.md common_src myocamlbuild.ml pdprune_src tests

COPYING _tags docs opam-requirements.txt pplacer_src wercker.yml

Makefile cdd_src json_src pam_src scripts

(base) KluepfelLabMBP01:pplacer-1.1.alpha19 dklabuser$ pplacer -h

-bash: pplacer: command not found


feels like pplacer is not working. I run this command already, $ python
setup.py install

Here is the link I use,
https://matsen.github.io/pplacer/scripts.html#installing   Could you
plesase help me what I did wrong for installing pplacer?


Also, I changed my .bash_profile, so it will point to the pplacer folder
where I put, here is how it looks,




[image: Screen Shot 2020-03-24 at 10.30.30 AM.png]

Then I run source .bash_profile.

I tried all I could to make it work, and still don't know what is going
on.
Really appreciate all your patience and help.

Best,

Limin

**Comment by dparks1134** [comment]
Hi. Did you compile the pplacer source code? If so, you then need to put pplacer on your system path.

**Comment by limin321** [comment]
> Hi. Did you compile the pplacer source code? If so, you then need to put pplacer on your system path.

what do you mean by "compile the pplacer source code"?   And how to put pplacer on my system path?
I am not a computer person at all, I have been struggled so much to understand this things. Could you please explain a little bit more how should I do? Thanks a lot.

**Comment by dparks1134** [comment]
Hi. I've never compiled pplacer before so can't provide any direct help. Perhaps running CheckM through KBase would meet your needs:
https://kbase.us/applist/apps/kb_Msuite/run_checkM_lineage_wf

KBase provides access to a number of bioinformatic tools as online web services.
