### ISSUE TITLE
CheckM installation check error

### ISSUE THREAD

**Issue by nsarode** [Ecogenomics/CheckM#25]
Hi,
I don't have admin rights on our server and our IT guy installed CheckM for us. The command options show up just fine on type checkm, but when on trying the installation check test command I got the following error. It doesn't make a whole lot of sense to me, but my guess is that Python version 2.6 is one issue and have already requested an upgrade. But can you have a peek at the error message and let me know if something else is missing too (e.g. Error: Unrecognized format, trying to open hmm file /tmp/be078517-7f20-4792-9116-a243633e5715 for reading) so that I can ask our admin to install it ? 

Command used : checkm test ~/checkm_test_results

*******************************************************************************
[CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
*******************************************************************************

[Step 1]: Verifying tree command.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.
Error: Unrecognized format, trying to open hmm file /tmp/be078517-7f20-4792-9116-a243633e5715 for reading.

    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/bin/checkm", line 717, in <module>
    checkmParser.parseOptions(args)
  File "/usr/lib/python2.6/site-packages/checkm/main.py", line 1267, in parseOptions
    self.test(options)
  File "/usr/lib/python2.6/site-packages/checkm/main.py", line 1156, in test
    verifyEcoli.run(self, options.output_dir)
  File "/usr/lib/python2.6/site-packages/checkm/test/test_ecoli.py", line 64, in run
    parser.tree(options)
  File "/usr/lib/python2.6/site-packages/checkm/main.py", line 129, in tree
    markerSetParser.writeBinModels(binIdToModels, hmmModelInfoFile)
  File "/usr/lib/python2.6/site-packages/checkm/markerSets.py", line 471, in writeBinModels
    with gzip.open(filename, 'wb') as output:
AttributeError: GzipFile instance has no attribute '__exit__'

Thanks,
Neha

**Comment by nsarode** [comment]
Nevermind. Just Python issue. The test is running right now and it is at step 4 now. Can't delete this issue myself, so please close it. Sorry for the trouble.

**Comment by guillb** [comment]
Hi, 
I have the same trouble and I don't see what Python issue it could be..
Would you indicate me how you fixed this problem.
best,
Guillaume

**Comment by nsarode** [comment]
Hi Guillaume,
In my case the issue was my current python version (2.6). In the CheckM documentation, they mentioned that the python version it uses is python >= 2.7 and < 3.0 . So once the appropriate version was installed, things ran fine.

Thanks,
Neha

**Comment by guillb** [comment]
Thanks Neha for the very quick answer
Apologies, the issues looked the same than yours but I figured out that it is not.. and I think my problem is more about permission to create/access files in the tmp
I'll find out!
Thanks again
Guillaume
