### ISSUE TITLE
Logging on stderr

### ISSUE THREAD

**Issue by wwood** [Ecogenomics/CheckM#252]
Hi,

Out of habit, I've been running checkm like this, piping stdout as the output file

```
(checkm-genome-1.1.2) $ checkm lineage_wf genomes /tmp/checkm-tmp-ben -t 24 --pplacer_threads 24 --tab_table >checkm.csv
    Finished processing 16 of 16 (100.00%) bins.
    Finished processing 16 of 16 (100.00%) bins.
    Finished parsing hits for 16 of 16 (100.00%) bins.
    Finished extracting 43 of 43 (100.00%) HMMs.
    Finished aligning 43 of 43 (100.00%) marker genes.
    Finished parsing hits for 16 of 16 (100.00%) bins.
    Finished processing 16 of 16 (100.00%) bins (current: xx_genomic).
    Finished processing 16 of 16 (100.00%) bins.
    Finished parsing hits for 16 of 16 (100.00%) bins.
    Finished processing 16 of 16 (100.00%) bins.
    Finished processing 16 of 16 (100.00%) bins.
    Finished parsing hits for 16 of 16 (100.00%) bins.
```
I'm used to seeing status info but it seems all the logging is now on stdout not stderr as before. This means the output file of the above has both logging and results in it.

I guess this is fixable using `--file` or text massaging the stdout, but just wonder if the change was unintentional.

Thanks.

**Comment by dparks1134** [comment]
Hi. Sorry for the change. I'm not sure when this took place but will leave it as is moving forward.
