### ISSUE TITLE
how to create marker list for --exclude_markers

### ISSUE THREAD

**Issue by wufabai** [Ecogenomics/CheckM#254]
There are a few markers I want to exclude from the final completion/contamination evaluation. I understand from your instruction that I should use: 
checkm qa --exclude_markers MARKER_FILES
Could you provide an instruction on how to create this MARKERS_FILES?

Thank you so much and apologies if this doesn't below to this 'issues' section.

**Comment by dparks1134** [comment]
The MARKERS_FILE just lists the markers to exclude, one per line, e.g.:
```
PF01192.17
PF02092.12
PF08459.6
TIGR00344
```

Cheers,
Donovan

**Comment by wufabai** [comment]
Thank you so much Donovan!

cheers,
Fabai
