### ISSUE TITLE
checkm: error: argument sub parser_name: invalid choice: 'bin_qa_plot'

### ISSUE THREAD

**Issue by FengqingWang0712** [Ecogenomics/CheckM#256]
Dear all,
When I input the bin_qa_plot --help, there is this error appears check: error: argument sub parser_name: invalid choice: 'bin_qa_plot'.....
Why there is no bin_qa_plot in my checkm? gc_plot is working.  I'm full of appreciation if some one who would like to give some suggestions.

**Comment by dparks1134** [comment]
This plot was removed from the most recent versions of CheckM as it was a non-critical, rarely used plot that does not scale to large numbers of input genomes. This was causing confusion for individuals new to CheckM trying to create this plot with lots of genomes.

**Comment by FengqingWang0712** [comment]
> This plot was removed from the most recent versions of CheckM as it was a non-critical, rarely used plot that does not scale to large numbers of input genomes. This was causing confusion for individuals new to CheckM trying to create this plot with lots of genomes.

OK. I see. Thanks very much for your kindly reply.
