### ISSUE TITLE
Strain heterogeneity is missing

### ISSUE THREAD

**Issue by abmiguez** [Ecogenomics/CheckM#257]
Hi,
I am using the Lineage workflow to asses the quality of my MAGs. However, after execution, I cannot find the strain heterogeneity stat in any of the CheckM report files. If I undestood the tutorial, at the end of the workflow "checkm qa" is executed with default parameters that, as stated in the documentation, should report it. There is another command that I have to execute in order to get this stat? 

Best,
Aitor

**Comment by dparks1134** [comment]
Hi. The results are written to the terminal. You can run (re-run) the `qa` command and have the results written to file using the `--file` flag. I often do this in conjunction with the `--tab_table` flag.
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

**Comment by abmiguez** [comment]
Great, this is really helpful, thanks a lot!

Best,
Aitor
