### ISSUE TITLE
no output from coverage

### ISSUE THREAD

**Issue by ajcardenasb** [Ecogenomics/CheckM#259]
Hi Donovan,

I'm running the coverage option with different bam files and always get this error after processing the files:

      #total reads: 70374564
      # properly mapped reads: 32221423 (45.8%)
      # duplicate reads: 0 (0.0%)
      # secondary reads: 0 (0.0%)
      # reads failing QC: 20589812 (29.3%)
      # reads failing alignment length: 0 (0.0%)
      # reads failing edit distance: 7112751 (10.1%)
      # reads not properly paired: 7341614 (10.4%)

[2020-05-15 09:33:34] INFO: Writing coverage information to file.
[2020-05-15 09:33:34] ERROR: Error diverting stdout to file: GC1B

Do you know where the issue comes from?
Thank you in advance,
Anny

**Comment by dparks1134** [comment]
Hi Anny. I haven't seen that error message before. Can you send me the exact command you are running? Any chance you don't have permission to generate a file in the directory you are in?

**Comment by ajcardenasb** [comment]
Thanks for your quick reply! 

This is the command I'm running:
checkm coverage ~/projects/endoliths/metaGs/mags/final_bins/ GC1B ~/projects/endoliths/metaGs/binning/GC1B.bam -x fasta -t 128

And regarding permissions, I can read write and execute on that folder. 
drwxrwxr-x 3 cardena cardena  4096 Mai 15 09:19 ./
drwxrwxr-x 8 cardena cardena  4096 Mai 14 17:30 ../

Thanks,
Anny

**Comment by dparks1134** [comment]
I have verified that the `coverage` command is working in CheckM v1.1.2 using the same parameters you indicated. I also wrote the results to a file named `GC1B` just to ensure it wasn't a naming or file extension issue. Can you verify you have the latest version of CheckM? Perhaps try running the command from your home directory as a sanity check.

**Comment by ajcardenasb** [comment]
Did not have the message with the new version. 
I had installed an older version to be able to install it with conda as some libraries had conflicts during pip, but everything is fixed now.

Thanks!
