### ISSUE TITLE
Can I get the sequences of reference genomes in CheckM?

### ISSUE THREAD

**Issue by dmyang93** [Ecogenomics/CheckM#261]
I want to download the sequence files used to make reference genome tree (5656 IMG genomes)
But I cannot find how to get them.
How can I get the resource of them?
If It is stated at CheckM paper, I cannot know where it is stated.
Thank you

**Comment by dparks1134** [comment]
You can find metadata about the reference genomes in the file `/img/img_metadata.tsv` which is contained in the CheckM data files (https://data.ace.uq.edu.au/public/CheckM_databases/). You would need to download the actual genomes from IMG or NCBI.
