### ISSUE TITLE
extracting marker proteins with "checkm qa -o 9" does not work, if the input was protein sequences

### ISSUE THREAD

**Issue by jvollme** [Ecogenomics/CheckM#262]
I wanted to use checkm slighlt differentlry, only to extract the merker genes for a specific level (e.g. Bacteria) from my already ORF-called genomes. For this i want to use my total protein seqeunces as input.

So i first generated the marker gene set using "checkm taxon_set":
```
checkm taxon_set domain Bacteria checkm_taxonomy/Bacteria.ms
```

then i extracted the marker genes from protein sequences using "checkm analyze" with the "-g" option:
```
checkm analyze -g -x .faa -t 8 checkm_taxonomy/Bacteria.ms ./input ./checkm_taxonomy
```

this worked well, as i can get correct completion/contamination estimates using "checkm qa -o2".
So i tried extracting only the marker genes using "checkm qa -o 9":
```
checkm qa -o 9 -f results_qa_markers.fa -t 8 ./checkm_taxonomy/Bacteria.ms ./checkm_taxonomy
```

but the result file is empty. It DOES work when i use genome (nucleotide) fastas as input, but then the orf-calling is different from mine. I would rather like to know which of my already colled ORFS corresponds to a checkm marker gene...

How do i extract the marker genes using protein fastas as input?

**Comment by dparks1134** [comment]
This remains an issue and will not be resolved. CheckM v1 is reaching end-of-life as CheckM v2 should be ready by the end of the year.
