### ISSUE TITLE
Both discrete and continuous differences in Contamination and Completeness values 

### ISSUE THREAD

**Issue by karchern** [Ecogenomics/CheckM#264]
Hi Donovan,
I am running checkM on a couple of _Akkermansia muciniphila_ MAGs and I noticed something that I don't quite understand (See scatter with alpha = 0.1 below): There are 'discrete' completeness and contamination values that occur frequently, and they have a discrete difference between them as well. At the same time, many MAGs do not behave like this; their completeness and contamination values appear to be distributed continuously.

I'm assuming that discrete completeness and contamination values are to be expected based on how checkM works: For example, if there (x-1) marker genes of a clade found in a MAG, I expect the completeness to be ((x-1)/x)*100%.

Could you explain how these non-discrete values actually arise, algorithmically?

Thanks a lot for the software, it is extremely useful!

Cheers,
Nic

Plot:

![Rplot](https://user-images.githubusercontent.com/19149571/84593285-c17a0100-ae4b-11ea-931e-dd33566c74bc.png)

**Comment by dparks1134** [comment]
Hi,

CheckM organizes marker genes into co-located marker sets (i.e. genes that are typically found close to each other) and uses this information to inform the completeness and contamination estimates. You can find full details in the CheckM manuscript:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4484387/

I think your scatter plot is as expected. For a given marker set, there will be a discrete set of completeness and contamination values that are possible. How are you running CheckM? If you are using the `lineage_wf` it is possible that different marker sets are being used for different genomes. You can check the CheckM output to see what marker set was selected for each genome.

Cheers,
Donovan

**Comment by karchern** [comment]
Thanks, that makes sense!
