### ISSUE TITLE
Update lineage specific markers within the CPR / Patescibacteria

### ISSUE THREAD

**Issue by alexcritschristoph** [Ecogenomics/CheckM#266]
Hi Donovan,

I suspect you are aware of this issue but I wanted to ask. Currently CheckM underestimates completeness of many genomes from  the CPR/Patescibacteria which lack many SGCs found in most bacterial lineages. E.g. in the data from GTDB shown attached, it becomes clear that CheckM completeness is a definite underestimate. This concept has been explored and reported on previously, e.g. https://www.nature.com/articles/ncomms13219#MOESM779

I was wondering are there plans to update the set of expected marker genes found for this lineage in checkM? Now for the most part it does not seem to recognize these genomes as any specific lineage at all.

Thanks,
Alex
![Screenshot from 2020-07-01 10-52-17](https://user-images.githubusercontent.com/5387541/86276599-014e2180-bb8a-11ea-8e69-09e046ceb11e.png)
![Screenshot from 2020-07-01 10-52-04](https://user-images.githubusercontent.com/5387541/86276603-01e6b800-bb8a-11ea-9c0e-7f11b6dd659c.png)

**Comment by dparks1134** [comment]
Hi Alex. Thank you for your message and very nice analysis. Yes, we are aware that patescibacterial genomes aren't well represented by the "universal" bacterial marker set. A CheckM v2 is in active development which will address this limitation and allow for more rapid incorporation of the latest genomes by being built on top of the GTDB. This is almost certainly a few months away though. In the meantime, if you have an immediate need for more sensible marker-based quality estimates for patescibacterial genomes you can provide your own marker set or specify specific markers from the bacterial set to be excluded.

**Comment by alexcritschristoph** [comment]
Thank you Donovan, that makes sense. Very exciting to hear that a CheckM v2 is in development.
