### ISSUE TITLE
unexpected IO error

### ISSUE THREAD

**Issue by TonyMane** [Ecogenomics/CheckM#267]
Greetings, I am trying to install CheckM. I thought I had lined up all the dependencies, but ran into an unexpected error when running a simple test on two complete genomes (see attached). :+1: 
[checkm.txt](https://github.com/Ecogenomics/CheckM/files/4900994/checkm.txt)

I installed checkm using pip (pip3 install checkm-genome).
Installed pplacer, hmmscan, prodigal, and added their locations to my .bashrc profile.
The two genomes i was using for comparison are NZ_CP011070.1 and NC_010085.1 (also attached in pyani_tests.tar.gz) '
[pyani_tests.tar.gz](https://github.com/Ecogenomics/CheckM/files/4901018/pyani_tests.tar.gz)

Any suggestions are welcome.

**Comment by dparks1134** [comment]
Hi. Best guess is that you are running out of memory. CheckM requires around 40 GB though there is a mode for reducing this to 16 GB:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
