### ISSUE TITLE
Where is completeness and contamination reported?

### ISSUE THREAD

**Issue by makrez** [Ecogenomics/CheckM#268]
This is a very simple question (which probably doesn't even belong here), but I couldn't find the answer:

Where is completeness and contamination reported?

I ran the command `checkm lineage_wf` and I get this on stdout:

```
------------------------------------------------------------------------------------------------------------------------------------------------------------------$
  Bin Id                  Marker lineage           # genomes   # markers   # marker sets    0     1     2   3   4   5+   Completeness   Contamination   Strain het$
------------------------------------------------------------------------------------------------------------------------------------------------------------------$
  SRR3241868.1   f__Enterobacteriaceae (UID5162)       88         1207          328        105   1100   2   0   0   0       93.33            0.08		0.$
------------------------------------------------------------------------------------------------------------------------------------------------------------------$
```
However, I couldn't find this information anywhere in a file.

**Comment by dparks1134** [comment]
The output is to standard out be default. If you wish to redirect it to a table you can use the --file flat. You may wish to use this with the --tab_table flag in order to get a table that is easier to use in a spreadsheet or parse later.

**Comment by makrez** [comment]
Thank you very much for your answer. Sorry, this is probably documented somewhere and more research from my side would have solved this without opening an issue. However, I do believe that saving the output should probably be the default behaviour, given that most people then filter the bins according to completeness and contamination.
