### ISSUE TITLE
Command "bin_qa_plot" is missing 

### ISSUE THREAD

**Issue by jarjarsound** [Ecogenomics/CheckM#269]
I tried v1.1.2 (installed via bioconda) and v1.1.3 (installed via pip3), but the command bin_qa_plot is missing for some reasons. Could you advise on that? Thank you very much!
![Untitled](https://user-images.githubusercontent.com/38936438/88258875-bc825a00-ccf3-11ea-9d98-85daaf93fc33.png)

**Comment by dparks1134** [comment]
Hi. Unfortunately, the `bin_qa_plot` command was removed as part of the port to Python 3 (v1.1.0) as a practical matter of reducing maintenance.

**Comment by jarjarsound** [comment]
Ah, I see. Thank you for answering! you might want to update the documentation as well.

**Comment by dparks1134** [comment]
Thanks - I'll update the documentation today.
