### ISSUE TITLE
DATA_CONFIG file permissions requirements

### ISSUE THREAD

**Issue by vphan13** [Ecogenomics/CheckM#270]
Can the path to the DATA_CONFIG file be set/or changed as option?  In a multi-user environment where software such as python (and checkm) are installed on an nfs share, users have access to run checkm but no write access to the install directory.  

When running checkm it checks for the current user invoking the command and writes changes the dataroot path in the DATA_CONFIG file to _/home/<user>/.checkm_.  It does not matter if this path is already set to a location where the user has write access, checkm checks for write permission to the DATA_CONFIG file and errors out if it does not have write access.  

Symlinking the DATA_CONFIG file seems to be a hacky workaround.  

If setRoot has not been run, the dataRoot path in DATA_CONFIG file is set to /home/<user>/.checkm
After running setRoot the dataRoot path is changed to where the data files are located.  

In our environment python is installed under 
/usr/local/packages/python-<version>/bin/
checkm installed via pip is install under /usr/local/packages/python-<version>/bin
The default DATA_CONFIG directory is located under 
/usr/local/packages/python-<version>/lib/python<version>/site-packages/checkm/

**Comment by najoshi** [comment]
I am having the same issues trying to run checkM on my cluster (I am also the installer). But I can't even set the data root dir... when I try to set it I get this error message:

> It seems that the CheckM data folder has not been set yet or has been removed. Please run 'checkm data setRoot'.
> Traceback (most recent call last):
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/checkmData.py", line 87, in checkPermissions
>     open(self.configFile, 'a')
> OSError: [Errno 30] Read-only file system: '/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/DATA_CONFIG'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/software/checkm/1.1.2/lssc0-linux/bin/checkm", line 4, in <module>
>     __import__('pkg_resources').run_script('checkm-genome==1.1.2', 'checkm')
>   File "/afs/.genomecenter.ucdavis.edu/software/anaconda3/4.5.12/lssc0-linux/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/afs/.genomecenter.ucdavis.edu/software/anaconda3/4.5.12/lssc0-linux/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
>     exec(code, namespace, namespace)
>   File "/afs/genomecenter.ucdavis.edu/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/EGG-INFO/scripts/checkm", line 36, in <module>
>     from checkm import main
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/main.py", line 25, in <module>
>     from checkm.defaultValues import DefaultValues
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/defaultValues.py", line 26, in <module>
>     class DefaultValues():
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/defaultValues.py", line 29, in DefaultValues
>     __DBM = DBManager()
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/checkmData.py", line 120, in __init__
>     if not self.setRoot():
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/checkmData.py", line 142, in setRoot
>     if not self.config.checkPermissions():
>   File "/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/checkmData.py", line 88, in checkPermissions
>     except (IOError, e):
> NameError: name 'e' is not defined

Any help would be highly appreciated.

- Nik.

**Comment by vphan13** [comment]
Seems pretty clear. . .

OSError: [Errno 30] _Read-only file system_: '/software/checkm/1.1.2/lssc0-linux/lib/python3.6/site-packages/checkm_genome-1.1.2-py3.6.egg/checkm/DATA_CONFIG'  

If python is installed on an nfs share, make sure its not mounted READ ONLY.  
Symlink the DATA_CONFIG file to a location that is RW. . when you run checkm with no options it should bring up a list of options. Make sure this is the case before trying to run the setRoot option.  The symlink option is working for us, but its far from optimal

For whatever reason, the checkm command checks if the DATA_CONFIG  file is RW, even if you set the dataRoot path in the file to a RW location manually (which is what the setRoot option does), the file itself has to be RW.

**Comment by najoshi** [comment]
Yeah, I understand that problem... but we shouldn't have to symlink the file at all. Also, all of our software is mounted read-only for the users. Also, doesn't explain why I'm having the error afterwards. I might just change the code itself.

**Comment by douglasgscofield** [comment]
We have this same issue.  We would still like to provide CheckM in a module that is read-only for the users.  It would be nice to be able to `checkm data setRoot` the 'standard' 2015_01_16 data for the users, with that providing a read-only copy of the data as a default data set, but that isn't possible either.

**Comment by fullama** [comment]
if its of any use: i had an issue where i had to have the checkm_db in a different location on one of our servers (I/O issues)
I added 2 lines to the end of the `__init_` function of `DBConfig` in `checkmData.py` to have a different path if an env variable (`CHECKM_DATA_CONFIG`) was set:

```python
    def __init__(self):
        self.logger = logging.getLogger()
        self.configFile = os.path.abspath(resource_filename('checkm', 'DATA_CONFIG'))
        self.values = self.getConfig()
        if os.environ.get('CHECKM_DATA_CONFIG'):
            self.values["dataRoot"] = os.environ.get('CHECKM_DATA_CONFIG')
```

**Comment by dparks1134** [comment]
Hi,

Starting with CheckM v1.1.6 the CHECKM_DATA_PATH environmental variable can be used to indicate the path to the CheckM reference data:
https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data

Cheers,
Donovan
