### ISSUE TITLE
Help reading the output of checkm... What are the .pkl.gz files on the storage?

### ISSUE THREAD

**Issue by RicardoGCCR** [Ecogenomics/CheckM#275]
Hi, 
I am exploring checkm, but I need some help interpreting the output. 
I run: 
checkm lineage_wf -t 8 -x fasta . ./checkm

I have the following questions:
- Of all files produced, which one will be a summary for the lineage of my contigs? Is there any table that indicate the closest lineage for each scaffold or contig? 
- will the above usage produce any output plots?
- what are the .pkl.gz files on the storage folder?

Thanks, 
Ricardo

**Comment by dparks1134** [comment]
Hi. CheckM does not produce a file indicating the lineage of each contig. Each genome is placed in a reference tree and a taxonomic classification assigned to the genome. I do not recommend using these taxonomic assignments in general though as they are only meant to establish the best marker set to use for assessing completeness and contamination. There are separate commands for producing various plots (see: https://github.com/Ecogenomics/CheckM/wiki). The *.pkl.gz files contain information needed between different CheckM commands and aren't meant to be used by researchers.

**Comment by RicardoGCCR** [comment]
Thank you dparks1134!
It is all clear now.
Best regards,
Ricardo

**Comment by RicardoGCCR** [comment]
Thank you dparks1134!
It is all clear now.
Best regards,
Ricardo

**Comment by RicardoGCCR** [comment]
Thank you dparks1134!
It is all clear now.
Best regards,
Ricardo

**Comment by RicardoGCCR** [comment]
Thank you dparks1134!
It is all clear now.
Best regards,
Ricardo
