### ISSUE TITLE
Checkm issue due to error message on pplacer (ERROR: Make sure pplacer is on your system path)

### ISSUE THREAD

**Issue by mikela-virus** [Ecogenomics/CheckM#276]
Dear all, 

I am a new user of CheckM, I just installed it on my ubuntu for windows, following all the instructions and the dependencies stated in the manual. I launched the check tool and it started the analysis, sticking at some point because of pplacer not in my system path. 

To install the pplacer I followed step-by-step the all the indications contained at this link https://matsen.github.io/pplacer/compiling.html as you can also see below. I can install with no problem all the dependencies except (I suppose) the ocaml, which downward gives me problems with the pplacer. Indeed, if I try to call the program pplacer on the command line like 
pplacer -h

I get nothing.

Could you kindly help me to understand and solve this problem? Please consider that I do not have any prior knowledge about ocaml, so I would be grateful if you can provide foolproof instructions.

Following I am reporting all the commands I used for the installation and their related outcome. 

Thank you in advance  

root@xxx:/home/user# apt-get install -y \
>   camlp4-extra \
>   gawk \
>   libgsl0-dev \
>   libsqlite3-dev \
>   libz-dev \
>   m4 \
>   make \
>   ocaml \
>   patch
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'camlp4' instead of 'camlp4-extra'
Note, selecting 'libgsl-dev' instead of 'libgsl0-dev'
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
gawk is already the newest version (1:4.1.4+dfsg-1build1).
m4 is already the newest version (1.4.18-1).
make is already the newest version (4.1-9.1ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
camlp4 is already the newest version (4.05+1-2).
libgsl-dev is already the newest version (2.4+dfsg-6).
ocaml is already the newest version (4.05.0-10ubuntu1).
libsqlite3-dev is already the newest version (3.22.0-1ubuntu0.4).
patch is already the newest version (2.7.6-2ubuntu1.1).
patch set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 169 not upgraded.
root@xxx:/home/user# command -v ocamlc && ( ocamlc -version | grep -q 3.12.1 ) || opam switch install 3.12.1
/usr/bin/ocamlc
[WARNING] Running as root is not recommended
[ERROR] There already is an installed switch named 3.12.1
root@xxx:/home/user#
root@xxx:/home/user# opam init
[WARNING] Running as root is not recommended

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /root/.opam/opam-init/init.sh && . /root/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) y
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they
are loaded. Set that up? [y/N] y
root@xxx:/home/user#
root@xxx:/home/user# cd pplacer-1.1.alpha17/
root@xxx:/home/user/pplacer-1.1.alpha17# cat opam-requirements.txt | xargs opam install -y
[WARNING] Running as root is not recommended
[ERROR] Package sqlite3 has no version 1.6.3.
root@xxx:/home/user/pplacer-1.1.alpha17# make
if [ ! -e bin ]; then mkdir bin; fi
make pplacer.native
make[1]: Entering directory '/home/user/pplacer-1.1.alpha17'
ocamlbuild pplacer.native
make[1]: ocamlbuild: Command not found
Makefile:20: recipe for target 'pplacer.native' failed
make[1]: *** [pplacer.native] Error 127
make[1]: Leaving directory '/home/user/pplacer-1.1.alpha17'
Makefile:14: recipe for target 'pplacer' failed
make: *** [pplacer] Error 2

**Comment by dparks1134** [comment]
Perhaps it is easier to run CheckM through KBase so you don't need to install it on your local system: https://kbase.us/applist/apps/kb_Msuite/run_checkM_lineage_wf/release?gclid=Cj0KCQjw1qL6BRCmARIsADV9Jtavg29ra5iJf1OjR80Y6RDqZi7IY7KzIe1oCo7eSNg41gBpJwH8eyQaAq2FEALw_wcB

**Comment by mikela-virus** [comment]
Thanks a lot! Indeed it's very useful and much easier. 
I started my analysis through kbase, even though I would like to install the check, maybe I try using a docker. 
Stay safe and healthy
