### ISSUE TITLE
Checkm data setRoot problem

### ISSUE THREAD

**Issue by BSteel93** [Ecogenomics/CheckM#277]
Hi,

Apologies if this is a commonly reported issue, or if I'm just doing something simple wrong (I'm a bit of a bioinformatics newby).

I am currently processing metagenomic data on a shared VM, and had previously installed and used CheckM successfully without any errors. I had installed CheckM onto the base environment but decided to uninstall it and reinstall it into a dedicated conda environment. I am currently trying to use CheckM as part of the BinSanity binning pipeline, and have installed all packages and dependencies (via pip) according to the BinSanity/CheckM installations instructions in a conda environment. However, when I try to specify the directory for the checkm data using the following command:

_sudo checkm data setRoot /xxx/xxx/checkm_data_

I get the following output:

_It seems that the CheckM data folder has not been set yet or has been removed. Please run 'checkm data setRoot'.

Path [/home/ubuntu/.checkm] exists but you do not have permission to write to this folder._

I'm not really sure what's happening here and any help would be greatly appreciated. I think the problem may be related to the fact that I installed checkm previously into the 'base' environment'.

Kind regards,
Bruce

**Comment by dparks1134** [comment]
Hi,

Starting with CheckM v1.1.6 the CHECKM_DATA_PATH environmental variable can be used to indicate the path to the CheckM reference data:
https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data

Cheers,
Donovan
