### ISSUE TITLE
Using CPR Marker Set

### ISSUE THREAD

**Issue by maria-gekenidis** [Ecogenomics/CheckM#278]
Dear developers

I have tried using the CPR marker set in order to get other estimates of contamination and completeness for all my bins generated with metabat2. When following the instructions, that is, running only the steps `checkm analyze` and `checkm qa`, I get tables in which contamination and completeness are estimated. However, I get the following for the other columns:
1) 'Marker lineage: N/A (0)
2) '# genomes: -1
3) '# marker sets: 1

Is this the expected output or has something gone wrong? In case this is how it should look I think a note on this in the description (https://github.com/Ecogenomics/CheckM/wiki/Workflows#using-cpr-marker-set) might help avoiding confusion.

Thank you very much for your feedback!

**Comment by dparks1134** [comment]
Hi. The output is as expected. I've updated the wiki as suggested. Thanks.
