### ISSUE TITLE
Estimating contamination and genome completeness version 1.1.2 vs 1.0.5

### ISSUE THREAD

**Issue by cssulliv** [Ecogenomics/CheckM#279]
Hi,

I am currently using checkM v1.1.2 to analyze the quality of recovered genomes belonging to a specific phylum from 2 metagenomic samples. A previous study had already recovered similar genomes from the same 2 metagenomic samples and were assessed using checkM v1.0.5 back in 2017. 

I would like to know if checkM's algorithm for estimating % completion, % contamination and strain heterogeneity from running checkm qa in version 1.1.2 is similar to that of version 1.0.5? If there aren't major changes with how those metrics are calculated between the two versions I am hoping to be able to compare my recovered genomes to the 2017 genomes using the qa metrics I've listed above.

Thank you in advance for your help. :)

**Comment by dparks1134** [comment]
Hi. There are no substantive changes between v1.0.5 and 1.1.2. The results *may* not be 100% identical since CheckM (namely the pplacer step) is not deterministic, but this is independent of the CheckM version used.

**Comment by cssulliv** [comment]
Thank you so much for clarifying.
