### ISSUE TITLE
Does the lineage_wf include checkm tree_qa?

### ISSUE THREAD

**Issue by smb20200615** [Ecogenomics/CheckM#281]
In the tutorial you mention the steps:

(M) > checkm tree bin folder output folder
(R) > checkm tree_qa output folder
(M) > checkm lineage_set output folder marker file
(M) > checkm analyze marker file bin folder output folder
(M) > checkm qa marker file output folder

For convenience, the above workflow can be executed in a single step:

> checkm lineage_wf bin folder output folder

I just checked my log file and I don't see the checkm tree_qa step. Is that not included in the lineage_wf?

**Comment by dparks1134** [comment]
Hi. You are correct. The lineage_wf does not run tree_qa.
