### ISSUE TITLE
Get details of marker genes for genomes

### ISSUE THREAD

**Issue by domenico-simone** [Ecogenomics/CheckM#284]
Hi,

I am probably missing some obvious info but I can't find a way to get details about marker genes found in a genome analyzed with the `lineage_wf` workflow, _ie_: 

- How do I get to know which markers were found one time, which ones were found two times etc?
- How do I get the genome coordinates of these markers in a text file? I understand I could get them with the `marker_plot` but I am interested in a text output.

Thank you,

Domenico

**Comment by dparks1134** [comment]
Hi. The `qa` command can be used to produce different output tables:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#qa

I think you are after `table 4` and maybe `table 5`.
