### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JChristopherEllis** [Ecogenomics/CheckM#286]
Hi,

I am trying to run 
checkm bin_qa_plot ./checkm_lineage_dir ./bin_dir ./output dir 

but I get the following error for the checkM directory KeyError: 'P1-S1_bin_1'.

Should this be a file? It is a directory saved by checkM lineage.

Best,
Chris

**Comment by dparks1134** [comment]
Hi. The `bin_qa_plot` is no longer being supported and has been removed from recent release of CheckM. That said, the KeyError is likely related to your set of input files.
