### ISSUE TITLE
what is the mean of checkm lineage_wf results in the columns after "# marker sets" with the number (0       1       2       3       4       5+)

### ISSUE THREAD

**Issue by li0604** [Ecogenomics/CheckM#287]
Hi, everyone. would you mind give me a help?
I want to know the mean of checkm lineage_wf results in the columns after "# marker sets" with the number (0       1       2       3       4       5+). What is the function of these six columns?  The script and results were showed as following.
 Thanks a lot.

![image](https://user-images.githubusercontent.com/54136123/110797897-962a2280-82b4-11eb-9e1a-802d2e10f8ff.png)

**Comment by dparks1134** [comment]
Hi. These indicate the number of marker genes that were identified 0, 1, ..., 5+ times.

**Comment by li0604** [comment]
Thank you, professor. 
I have noticed that some numbers are up to 200 in column named "1", as we all know, the markers of bacteria are 120 proteins, is that means the markers of bacteria in checkM are more than 120?

**Comment by dparks1134** [comment]
The number of marker genes depends on where the genome is placed in the CheckM reference tree. A genome very similar to a well studied species might have hundreds of marker genes (i.e. the core gene set of E. coli or B. subtilis).

**Comment by li0604** [comment]
You are so kind! Thanks for your help and it is very useful for me to learn further about this software.

**Comment by Mass23** [comment]
Dear Dr. Parks,

A somewhat related question.

I was wondering if there was any way to get the 0, 1, 2, 3, 4 and 5+ counts of the number of "marker sets" found in the genome (that are used to compute the estimated completeness/contamination if I am not mistaken), instead of the counts for the "marker genes"?

Best regards,

Massimo

**Comment by dparks1134** [comment]
Hi. Unfortunately, there isn't any direct way to get this. It is also a bit ill-defined since one can find only a subset of the genes that make up a particular marker set.
