### ISSUE TITLE
checkM hangs with reduced_tree option

### ISSUE THREAD

**Issue by stilianoslouca** [Ecogenomics/CheckM#288]
In some situations checkM lineage_wf hangs indefinitely at the analyze step ("Identifying marker genes in bins."), even when using relatively high-quality genomes from NCBI RefSeq. The reported issue only happens when using the option --reduced_tree, but regardless of whether an AA fasta is provided (with option --genes) or a DNA fasta is provided.

**Details**
The problem manifests inside function setLineageSpecificSelectedMarkerSet, defined at line 95 of file markerSets.py.  It seems that checkM gets caught in some sort of infinite while loop (the one define on line 102).
Using checkM 1.1.3 with python 3.7 on MacOS 10.13.6, 128 GB RAM.

The issue can be reproduced on my end using the attached fasta (placed unzipped inside the directory "input_DNA") and the command:
`checkm lineage_wf --quiet --reduced_tree --tab_table -x fasta --file summary.tsv input_DNA output_DNA`

[GCF_000752275.1.fasta.gz](https://github.com/Ecogenomics/CheckM/files/6145811/GCF_000752275.1.fasta.gz)

**Comment by Biofarmer** [comment]
I also meet this case for some of my genomes from NCBI RefSeq by checkm lineage_wf with --reduced_tree option. It hangs indefinitely at the analyze step ("Identifying marker genes in bins."). May I ask why this only happens to some genomes? My version is 1.0.12.

**Comment by dparks1134** [comment]
Hi. I'm not sure why this happens. It seems to be exclusive to the --reduced_tree option. We are currently working on CheckM version 2, but in the meantime can you run CheckM without the reduced tree flag?

**Comment by Biofarmer** [comment]
Yes, I just tried without reduced tree flag, it works for analyze step. It is a bit strange that some genomes from NCBI RefSeq worked fine with reduced tree flag, but some are not (hangs at the analyze step). May I ask whether the results are comparable with or without reduced tree flag, as I have checked part of genomes with reduced tree flag?

**Comment by dparks1134** [comment]
From my testing the results are very comparable. That said, I'd recommend using the full tree unless you don't have the resources to run this since this has undergone more testing.

**Comment by Biofarmer** [comment]
That's great they are very comparable. Thanks.
