### ISSUE TITLE
Parsable output please

### ISSUE THREAD

**Issue by xapple** [Ecogenomics/CheckM#29]
So the most interesting statistics outputed by CheckM are the following:

    -----------------------------------------------------------------------------------------------------------------------------------------------------------
      Bin Id       Marker lineage      # genomes   # markers   # marker sets   0    1    2   3   4   5+   Completeness   Contamination   Strain heterogeneity
    -----------------------------------------------------------------------------------------------------------------------------------------------------------
      contigs   k__Bacteria (UID203)      5449        104            58        70   33   1   0   0   0       40.17            1.72              100.00
    -----------------------------------------------------------------------------------------------------------------------------------------------------------

The first thing is, why is this not included in a file somewhere ? I had to run it a couple times before figuring out that I should save the `stdout` to a file if I wanted to keep these statistics.

Then, it would make sense to have this easily parsable so that any pipeline can use these values for making graphs or anything else. But you have space delimited fields, with spaces in them ! The text ` (UID203)` in this example is part of the Marker lineage but is itself separated by a space. Which makes a simple approach fail:

    def checkm_stats(self):
         """The various statistics produced by checkm in a dictionary"""
        keys = OrderedDict((
            ("bin_id", str),
            ("lineage", str),
            ("genomes", int),
            ("markers", int),
            ("marker_sets", int),
            ("0", int), ("1", int), ("2", int), ("3", int), ("4", int), ("5+", int),
            ("completeness", float),
            ("contamination", float),
            ("heterogeneity", float)))
        values = list(self.checkm.p.stdout)[3].split()
        return {k: keys[k](values[i]) for i,k in enumerate(keys)}

Could you please think about making some more sound decisions when designing the main output of your program ?

**Comment by ctSkennerton** [comment]
There is an option called `--tab_table` that will produce a tab separated table without the fancy formatting for easy parsing

**Comment by xapple** [comment]
OK, that's good. It should probably be the default ?

**Comment by dparks1134** [comment]
Just to follow-up. There is also a <code>-f</code> flag to write the table (and only the table) to file. CheckM produces many different outputs with the <code>tree_qa</code> and <code>qa</code> commands which can be run after the complete lineage or taxonomic workflow.
