### ISSUE TITLE
CheckM marker sets

### ISSUE THREAD

**Issue by ohickl** [Ecogenomics/CheckM#293]
Hi,
I have two questions regarding the `taxon_marker_sets.tsv` file:

1. There are two species which contain empty sets in the `marker_sets` field: _Prevotella melaninogenic_ and _Clostridium acetobutylicum_. Is there a reason for this?
2. In the `checkm.hmm` profiles theres quite a few profiles (I counted 1493) that are nowhere in the `taxon_marker_sets.tsv` and/or `tigrfam2pfam.tsv`, even when using the `tigrfam2pfam.tsv` file to convert between IDs. Why is that? I do find 13 of them in `genome_tree.metadata.tsv` though and these are also found in the `tigrfam2pfam.tsv`.

Thanks for all the great work!

Best 
Oskar

**Comment by dparks1134** [comment]
Hi Oskar,

The `taxon_marker_set.tsv` and `checkm.hmm` files aren't designed to be manually inspected. What information are you trying to obtain? The `taxon_marker_set.tsv` file does contain information for both _Prevotella melaninogenica_ (not additional `a`) and _Clostridium acetobutylicum_ (see below).   Is the `checkm.hmm` file the results of running the `lineage_wf`? This will have marker sets for internal nodes that are not related to specific taxa. 

Cheers,
Donovan

```
species Prevotella melaninogenica       Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Prevotellaceae;Prevotella;melaninogenica       2       1041    226     [set(['PF05188.12', 'PF00550.20',....
species Clostridium acetobutylicum      Bacteria;Firmicutes;Clostridia;Clostridiales;Peptostreptococcaceae;Clostridium;acetobutylicum   3       1498    243     [set(['PF04297.9', 'PF01192.17', ....
```

**Comment by ohickl** [comment]
Hey, sorry for the very late answer.
I am parsing the marker sets manually to use them independently.
For the two taxa, I was referring to this:
Prevotella melaninogenica: `[...set(['PF03330.13']), set([]), set(['PF13643.1’])…]`
Clostridium acetobutylicum: `[...set(['PF07905.6']), set([]), set(['PF01435.13'])…]`

> marker sets for internal nodes that are not related to specific taxa

That'll be the reason for the 'missing' ones, thanks!

**Comment by dparks1134** [comment]
Hi. I'm not sure at this point to be honest. These marker sets were put together several years ago. My best guess is that I filtered out a marker gene that was single copy and ubiquitous, but found to often be misidentified using the Pfam HMMs.

**Comment by ohickl** [comment]
Ok, thanks again!
