### ISSUE TITLE
Meaning of checkM completeness

### ISSUE THREAD

**Issue by shmenolin** [Ecogenomics/CheckM#294]
I am just curious how checkM measures the completeness score. I thought higher the number of marker genes, higher would be the completeness. But recently I observed instances where this did not seem to occur. For instance, while comparing first report to second report:
![image](https://user-images.githubusercontent.com/61807957/115169485-20bc2980-a08c-11eb-957e-c039a1ce6c87.png)

![image](https://user-images.githubusercontent.com/61807957/115169504-2ade2800-a08c-11eb-8137-f16bfef2df22.png)

Both the genomes are from same genus with same number of identity of marker sets and marker genes. But the second one has a slightly higher completeness than the first one even when the number of genes missed in the second are higher than the first one.

**Comment by dparks1134** [comment]
Hi. CheckM organizes marker genes into marker sets in order to account for co-located genes. Details can be found in:

CheckM: assessing the quality of microbial genomes recovered from isolates, single cells, and metagenomes
https://genome.cshlp.org/content/25/7/1043.short
