### ISSUE TITLE
adding it to Galaxy?

### ISSUE THREAD

**Issue by ajkarloss** [Ecogenomics/CheckM#295]
Do you have plans to add CheckM to galaxy? so its easy to install and use?

**Comment by dparks1134** [comment]
No plans to add it to Galaxy. You can find CheckM on KBase though:
https://kbase.us/applist/apps/kb_Msuite/run_checkM_lineage_wf/release?gclid=Cj0KCQjwsqmEBhDiARIsANV8H3YOEoFaM38j-0lDrJW7PUYaabDL5MjOTH5ePXOPjhR-ceEMxyOyZkYaAlCoEALw_wcB

**Comment by ajkarloss** [comment]
Is it ok, if I try to add it to Galaxy? Not 100% sure. But I can try.

**Comment by ajkarloss** [comment]
Thanks for the reply.
