### ISSUE TITLE
About coding base of Prodigal.py 

### ISSUE THREAD

**Issue by kyuinHwang** [Ecogenomics/CheckM#297]
Hi,

Can you check the last line of Prodigal.py?
**_return np.sum(self.codingBaseMasks[seqId][start:end])_**

I think it produces a little error since ignoring the lastCodingBase of each contig (or scaffold).
If it is true, it will be better to replace "end" as "end+1" or fix the line 227.

Thank you

**Comment by dparks1134** [comment]
Hi. I think the code is correct based on the comment `Calculate number of coding bases in sequence between [start, end).` I'm guessing this is a 0 vs 1 indexing issue as the contig coordinates come from a GFF file that uses 1-based indexing.

**Comment by kyuinHwang** [comment]
**Thank you for answer!**

I understand about this occurs by 0 vs 1 indexing issue.
However, I still hard to understand **why the different rule is applied for only the last gene of contig**?
I enclosed a simple example below,

===============================================
if 1-based indexing gff file given like below,
_contig gene start end
contig1 gene1 1 3
contig1 gene2 5 7_
## here I exclude accessary information of gff files like as annotation tools or type of gene, strand, ... 

I expected 6 coding bases from this gff file (or single contig) but in the prodigal.py
genes = [(1,3), (5,7)] ## in line 226 ## it is simply modifed since dictionary used in original code 
lastCodingBase = 7 ## in line 227
then,
codingBaseMask = [0,1,1,1,0,1,1] ## by line 234-236 ## Expected [0,1,1,1,0,1,1,1] but np.zeros(7) make shorter result
then,
np.sum(codingBaseMask[0:7]) of line 251 resulting 5 instead of 6 I expected.
===============================================

I'm just asking because I detected a little different result between own coded script and checkM, so I hope you don't feel unpleasant by this bug reporting.

**Comment by dparks1134** [comment]
Hi. Thank you for the detailed example and I agree with the analysis. I've pushed a fix to this to the master branch which will be included in the next CheckM release. Efforts in regards to CheckM are primarily focused on version 2 at this point which will use a new code base.

**Comment by kyuinHwang** [comment]
**Thank you all the time for your hard work for the research community!**
