### ISSUE TITLE
marker sets in fasta format?

### ISSUE THREAD

**Issue by xfengnefx** [Ecogenomics/CheckM#299]
Hi,

I probably missed something, are the marker gene sets come with the checkM available in fasta format somewhere? I am aware that qa with -o 9 will output the protein sequences from a specified analysis, but I hope to check up on the raw marker sets.

Thank you!

**Comment by dparks1134** [comment]
Hi,

You can use `checkm qa -o4 ./checkm_lineage_wf/lineage.ms ./checkm_lineage_wf -f qa4.tsv` to get the marker set used by each genome. CheckM uses TIGRFAM and Pfam HMMs. You can visit these resources to get the HMMs and additional information about these protein families.

Cheers,
Donovan

**Comment by xfengnefx** [comment]
Thanks for the quick response! Will check out the sources.
