### ISSUE TITLE
Using CheckM for one fasta file directly

### ISSUE THREAD

**Issue by ajkarloss** [Ecogenomics/CheckM#300]
Is it possible/combination of options to run checksum for one sequence without mentioning a folder where the genomes are stored?

F. ex. 
checkm lineage_wf -x fa GCF_000196035.1_ASM19603v1_genomic.fa Output/

**Comment by dparks1134** [comment]
Hi. Sorry, this isn't currently supported.

**Comment by ajkarloss** [comment]
Ok, Thanks. Any quick tips if I want to modify the code to support this? I want to add this tool to our local galaxy. People want to use it for single genomes.

**Comment by dparks1134** [comment]
Not sure about modifying the code. Do you have the ability to move the genome into a temporary directory so you can point CheckM to a single genome?

**Comment by ajkarloss** [comment]
Also, when I install checkm in macbook using conda, it installs older version of the code which does not ported to python 3+

**Comment by ajkarloss** [comment]
Thanks.
