### ISSUE TITLE
input file type

### ISSUE THREAD

**Issue by yeoeunyun** [Ecogenomics/CheckM#302]
Hi.

I want to use CheckM to check and remove high-quality bacterial sequences in my genomic fasta file. (because my fasta file should not be including bacterial sequences.)

I wonder is CheckM acceptable only bin file, not simple fasta file for input? especially ```lineage_wf``` option.

Best
Yun

**Comment by dparks1134** [comment]
CheckM expects genomes (isolate, MAG, or SAG) as input.

**Comment by yeoeunyun** [comment]
@dparks1134 

Hi Parks. Thank you for your answer.

So you mean that CheckM doesn't accept contig-level fasta file as input?

**Comment by dparks1134** [comment]
CheckM expects the contigs/scaffolds in a FASTA file to be from a MAG, SAG, or isolate. It then estimates the quality of this genome. The output of CheckM doesn't make sense if you provide it with a FASTA file containing all contigs from a metagenomic assembly.

**Comment by yeoeunyun** [comment]
@dparks1134 

I got it. Thank you for the reply :)

**Comment by Caiyulu-818** [comment]
hi, how many genomes can the checkm analyse once ?and where to change the parameter of the genomes count?
