### ISSUE TITLE
Is there a way to get taxonomy ranks from the `lineage.ms` file from `lineage_wf`? 

### ISSUE THREAD

**Issue by jolespin** [Ecogenomics/CheckM#305]
I have a completed run and I'm looking through the output directory: 
![image](https://user-images.githubusercontent.com/9061708/121738146-b2ee1600-caae-11eb-991f-25ac85f3e273.png)

Here's what the `lineage.ms` file looks like: 
![image](https://user-images.githubusercontent.com/9061708/121737682-06ac2f80-caae-11eb-90ed-45c720ba070e.png)

I'm wondering if there is a file in the `checkm database` that will allow me to go from the current taxonomy identifier to get all lower order ranks such as domain.  In particular, I want to split my bacteria and archaea so I can then run barrnap to see if there are any 16S sequences that may have assembles (though, it's unlikely since they are short reads). 

If not, I can just use GTDB-Tk (I'm running this on my dataset right now).  Was just curious if these files exist anywhere.

**Comment by dparks1134** [comment]
I don't believe CheckM produces a file which will explicitly give this information.
