### ISSUE TITLE
How to check CheckM database version?

### ISSUE THREAD

**Issue by jolespin** [Ecogenomics/CheckM#306]
I'm compiling all of my results into a publication and was including database versions for GTDB-Tk, KOFAMSCAN, and CheckV.  Is there a way to determine database version for CheckM or should I just put the access date?

**Comment by dparks1134** [comment]
There has only been one version of the CheckM reference data:
https://data.ace.uq.edu.au/public/CheckM_databases/

**Comment by jolespin** [comment]
Ok good to know.  I will close this issue.
