### ISSUE TITLE
Genome problem

### ISSUE THREAD

**Issue by Biofarmer** [Ecogenomics/CheckM#312]
Hi, I am checking the quality of 1000 genomes with checkm v1.0.12. It stops at 'Parsing HMM hits to marker genes', as below:
```
Finished parsing hits for 60 of 1000 (6.00%) bins.
checkm.hmmer.FormatError: Error processing line:
NZ_MIWO0
```
I think this is due the 'Segmentation fault' in 'Identifying marker genes in bins' step for this genome. May I ask it is due to the poor quality of genome or other reasons? Is there the way to check the quality of this genome?

Thanks
Wang

**Comment by Biofarmer** [comment]
Hi, may I ask why sometimes very few genomes are not working with CheckM, such as GCF_900450675.1 from Refseq? Thanks

**Comment by dparks1134** [comment]
In what sense do these genomes not work? Does CheckM crash?

**Comment by Biofarmer** [comment]
There was an error 'Segmentation fault' in 'Identifying marker genes in bins' step for this genome. Does it work for you?

**Comment by dparks1134** [comment]
Yes - this genome runs fine for me. You can see the CheckM estimate for this genome on the GTDB website:
https://gtdb.ecogenomic.org/genomes?gid=GCF_900450675.1

Looks like a high-quality, isolate genome.

**Comment by Biofarmer** [comment]
Thanks for checking. I just check with version 1.0.18, and it worked. Any reasons? v1.0.12 worked for all other genomes.

**Comment by dparks1134** [comment]
Strange. There hasn't been any major bug fixed in CheckM so I'm not sure why the version would matter.
