### ISSUE TITLE
Problem calculating quality

### ISSUE THREAD

**Issue by alejandrorgijon** [Ecogenomics/CheckM#314]
Hi!
I'm checking the quality of a set of publicly available genomes, but when assessing the contamination and completeness of them, none of the genomes have >50% of completeness **&** <5% contamination. I checked the .log files but no problem was reported. Could you help me with this? I wonder if it's a problem with the format of the .fna files: I checked with CheckM the quality of another set of genomes and the results were ok. I attach a picture of one of the genomes that are problematic as an example.
I'm using v 1.1.3 (latest version if I'm not wrong).

![EXAMPLE](https://user-images.githubusercontent.com/91469300/134901216-a9f0b009-999d-4733-ad95-3adc791d0082.png)

Thanks for the help!

**Comment by dparks1134** [comment]
Hi. I'd try removing the ":" and "/" in the contig names. CheckM uses a lot of 3rd party software (pplacer, HMMER) and perhaps they are munging these names in a weird way.

**Comment by alejandrorgijon** [comment]
Hi! I removed all ":", "/" and "-" from the contig names but still the contamination and completeness values are too low. Could it be a problem of paragraph spacing / line breaks?

**Comment by dparks1134** [comment]
Couldn't hurt to make sure the FASTA file is using UNIX style line breaks. I know Prodigal can have issues with different style line breaks though I've patched this in CheckM already.

**Comment by alejandrorgijon** [comment]
When I check with $file /filename/, all my .fna files are ASCII text, so I suppose that this implies that they are Unix coded. Right?
I wonder also if the sequences of the contigs need to be on the same line instead of broken into different lines within the .fna files. Could this be relevant?

**Comment by dparks1134** [comment]
Having the sequence data split over multiple lines is normal. There is a program called "fromdos" that changes line endings to Unix style.

**Comment by alejandrorgijon** [comment]
Hi!
We have figured out the problem: it was a mistake on previous steps to CheckM. The program was reading correctly all .fna files, everything is fine now. 
Thanks for all the help and the fast answers.
