### ISSUE TITLE
Sharing databases on a cluster and .dmanifest problem...

### ISSUE THREAD

**Issue by geboro** [Ecogenomics/CheckM#317]
Hello!

I'm teaching on a cluster and I'm trying to get other users to install checkM (which works I think), but then I also wanted to share the precalculated database (it doesn't seem logic to have everyone download it on their own). 

I'm having a lot of problems, since they can read and access it but then when running 
`> checkm data setRoot <checkm_data_dir>`
it generates a `.dmanifest` file per user, hence it tries to overwrite it each time a new user sets the path... could I have some input on what this file is doing? can I let everyone overwrite it? or maybe get my install version so everyone uses the same? does it ineed to be personalized?

thanks !

**Comment by dparks1134** [comment]
Hi. The individual who setup the database end of CheckM has moved on to other ventures. I'm not that familiar with the exact role of the .dmanifest file. I think it should work so long as the path is staying the same. I'd certainly try testing it out first though. Alternatively, CheckM can be install system wide for all users. I think this is how most labs are using CheckM.

**Comment by dparks1134** [comment]
Hi,

Starting with CheckM v1.1.6 the CHECKM_DATA_PATH environmental variable can be used to indicate the path to the CheckM reference data:
https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data

Cheers,
Donovan
