### ISSUE TITLE
Contamination is not in precentage?

### ISSUE THREAD

**Issue by ZeweiSong** [Ecogenomics/CheckM#318]
Hi,

After following the linear_wf, I got the qa result. But I found that in the column of Contamination, somoe number can be larger than 100. 

What does this number mean? And how can we convert it to the percentage?

Thanks!

Zewei

![图片](https://user-images.githubusercontent.com/7750107/146679969-8158901a-f988-417c-b885-81c80e90722e.png)

**Comment by dparks1134** [comment]
Contamination is a percentage it is just not bounded to 100%. Full details on the contamination calculation used by CheckM can be found in the CheckM manuscript.
