### ISSUE TITLE
Prodigal output parsing problem

### ISSUE THREAD

**Issue by dturaev** [Ecogenomics/CheckM#32]
Hi, the prodigal output format seems to have changed between versions 2.60 and 2.61/2.62. The new output can't be parsed.

Example of old output line:
```
# Model Data: version=Prodigal.v2.60;run_type=Single;model="Ab initio";gc_cont=35.88;transl_table=11;uses_sd=1
```
New output line:
```
# Model Data: gc_cont=35.88;transl_table=4;uses_sd=1
```

The error is:
```
  File "/apps/python/lib/python2.7/site-packages/checkm/prodigal.py", line 178, in __parseGFF
    self.translationTable = line.split(';')[4]
IndexError: list index out of range
```

Also, another small request: In the file "checkm", please change the line
```
versionFile = open(os.path.join(binDir, '..', 'checkm', 'VERSION'))
```
to
```
import checkm; versionFile = open(os.path.join(checkm.__path__[0], 'VERSION'))
```
or something similar, this would be more stable.

**Comment by dparks1134** [comment]
Hello dturaev,

Thank you for bringing this to my attention. This issue has been resolved in CheckM v1.0.3.

Cheers,
Donovan
