### ISSUE TITLE
Make the -f option output default and add flag options for positional arguments

### ISSUE THREAD

**Issue by tarunaaggarwal** [Ecogenomics/CheckM#320]
Hello - I'm a new CheckM user and am very grateful for the existence of this program. I hope you won't mind, but I have two suggestions that may help future consumers of CheckM when using it in their work.

1. It took me a few times to run CheckM before I realized that I should use the `-f` option to get a table that displays the completion stats. I kept digging around in the output folders of the lineage workflow, but I had no luck finding that summary table. The completion summary is the main table most users want to see after running checkM so they can get an overview of what their data look like. Is it please possible to make this table a default that gets outputted in the main results directory? OR at the least, make the purpose of the `-f` option explicit in the manual front and center with an example table. 

2. Would it please be possible to add options for the positional arguments such as `bins_dir`, `output_dir`, etc? It would be helpful from a user perspective to have commands like `-b bins_dir -o output_dir -p plots_dir` rather than `bins_dir output_dir  plots_dir`. The former will rid the user of the burden of having to remember the order of the positional arguments. 

Thank you again for writing CheckM! 
Taruna

**Comment by dparks1134** [comment]
Hi,

Thank you for the suggestions. CheckM v1 is no longer in active development. A new version of CheckM is in develop and should be released later this year.

Cheers,
Donovan
