### ISSUE TITLE
inverse_transformed deprecated

### ISSUE THREAD

**Issue by Gr1m3y** [Ecogenomics/CheckM#323]
I was attempting to run marker_plot and ran into an issue `AttributeError: 'BBox' has no attribute 'inverse_transformed'`. I believe this issue is because inverse_transformed has been deprecated (see [here](https://matplotlib.org/3.3.3/api/api_changes.html#bboxbase-inverse-transformed)). Only the required positional arguments were provided to inverse_transformed.

**Comment by opplatek** [comment]
You will either have to downgrade to Matplotlib<3.3 (I believe that's when it was deprecated) or just made tiny adjustments in `AbstractPlot.py`. Change `bboxi = bbox.inverse_transformed(self.fig.transFigure)` to `bboxi = bbox.transformed(self.fig.transFigure.inverted())` on lines 81, 88, 106, and 124 (CheckM v1.1.3).

**Comment by Gr1m3y** [comment]
Thank you! Solved the problem perfectly!
