### ISSUE TITLE
Coverage not matching contig names

### ISSUE THREAD

**Issue by ttubb** [Ecogenomics/CheckM#325]
Hello,

i am having issues with the CheckM "coverage" functionality. In the output file i see zero coverage for all bins, only unbinned contigs are covered. Upon closer investigation i noticed that contig names were not consistent. CheckM seems to pull complete fasta headers from the .BAM-files, so contigs are named like
`>k145_1520 flag=1 multi=629.1253 len=6219`.
Meanwhile, from the .fasta-files of MAG bins it will only pull the actual contig name assigned by metabat (e.g. `>k145_1520`, everything up to the space). Thus, CheckM reports these as two different contigs: `>k145_1520` of bin#1 with 0 coverage and `>k145_1520 flag=1 multi=629.1253 len=6219` (unbinned) with the proper counts.

Are my input files somehow malformed? Is it a bug? I am thankful for any pointers.

Cheers,
Tom

  

My latest try was using CheckM v1.1.3 with the following command:
```
checkm coverage \
	--threads 24 \
	--extension .fa \
	/mnt/checkm_abundance/bins_w_new_contignames \
	/mnt/checkm_abundance/checkm_coverage.tsv \
	/mnt/data/renamed_bam/1a.bam \
	/mnt/data/renamed_bam/1b.bam \
	/mnt/data/renamed_bam/1c.bam \
	/mnt/data/renamed_bam/2a.bam \
	/mnt/data/renamed_bam/2b.bam \
	/mnt/data/renamed_bam/2c.bam \
	/mnt/data/renamed_bam/3a.bam \
	/mnt/data/renamed_bam/3b.bam \
	/mnt/data/renamed_bam/3c.bam
```

**Comment by dparks1134** [comment]
Hi. This sounds like it could be a bug. I'd recommend you look at CoverM for calculating coverage profiles:
https://github.com/wwood/CoverM

CoverM has a lot more options for how coverage is calculated and is purpose built for this task.

**Comment by ttubb** [comment]
Thank you for the very fast response. Unfortunately, CoverM seems to suffer from the same exact problem. For anyone else searching: There is [a fix in the development version of CoverM](https://github.com/wwood/CoverM/issues/86). Alas, the current dev version will not process my full dataset without crashing.
