### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/.checkm/hmms/phylo.hmm'

### ISSUE THREAD

**Issue by yazhinia** [Ecogenomics/CheckM#328]
Hello,
       I installed CheckM through conda in a non-default directory and followed exactly the same steps given on the wiki page. Even though the phylo.hmm file exist in the downloaded path, the program only searches in the default directory. How to give a custom path for the program.

Thanks very much for the help.

**Comment by dparks1134** [comment]
Hi,

This suggest CheckM is not able to identify the location of the CheckM reference data. You can set the path to this data using the CHECKM_DATA_PATH environmental variable:
https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data

Cheers,
Donovan
