### ISSUE TITLE
Convert "checkm.results" to a easier analysis table

### ISSUE THREAD

**Issue by B-1991-ing** [Ecogenomics/CheckM#334]
Dear CheckM support team,

I directly got one table as shown below from the VAMB snakemake workflow. How could I transfer it into a more easier format? I want to mainly extract three columns - "Bin Id", "Completeness" and "Contamination".

**screenshot of the table "checkm.results"**
<img width="1332" alt="Screenshot 2022-04-29 at 16 41 52" src="https://user-images.githubusercontent.com/54441633/165967334-b0df914e-fe1f-43de-8e76-aa49ba6672f3.png">

Best,

Bing

**Comment by dparks1134** [comment]
Hi,

I'm not familiar with the options provided by VAMB, but CheckM does have a `--tab_table` flag that produces output tables as standard TSV files.

Cheers,
Donovan

**Comment by B-1991-ing** [comment]
Hi Donovan,

Thank you very much for your reply. 

In the VAMB workflow, the checkM is already integrated into the VAMB software or workflow.

Is the **checkm.results** shown as "SQL" format? Could I only use the "--tab_table" to only transform it to standard TSV?

screenshot of the table "**checkm.results**"
![](https://user-images.githubusercontent.com/54441633/165967334-b0df914e-fe1f-43de-8e76-aa49ba6672f3.png)

Best

Bing

**Comment by dparks1134** [comment]
Hi Bing,

Sorry, there is no way to use CheckM or any other software I know of to convert the table in the format you currently have it. I'd suggest contact the VAMB authors and raising this concern. Perhaps they can modify VAMB to produce the CheckM table in a format that is easier to use.

Cheers,
Donovan

**Comment by B-1991-ing** [comment]
Hi Donovan,

Thank you very much for your suggestion. I'll first try myself to use python pandas to parse "**checkm.results**". And also contact the VAMB team to report my problem.

Have a nice weekend.

Best,

Bing
