### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by lfenske-93** [Ecogenomics/CheckM#336]
Hi,

I'm trying to run checkm in the latest version, but it doesn't work.
The commands are the same as I used before, however I get with:

` checkm lineage_wf checkm_000/SAMD00013503.contigs.fa.gz checkm_000/ -x .gz`

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

And if I try it with an unpacked file:

`IndexError: list index out of range`

Unfortunately, the log file does not give any hints about further errors...
I installed checkm with conda and everything seems to be up to date.

Greetings,
Linda

**Comment by dparks1134** [comment]
Hi Linda. Sorry for the very slow reply. Has this issue been resolved?

**Comment by lfenske-93** [comment]
Hi (:

Yes, everything works fine now. I was on vacation a few weeks and after I came back it worked without problems...I wish that was the solution to all problems. 😄
