### ISSUE TITLE
guppy: loadlocale.c:129

### ISSUE THREAD

**Issue by SilasK** [Ecogenomics/CheckM#337]
We had this strange error encountered in checkM, I have a possible solution and wanted to mention it to you. 

https://github.com/metagenome-atlas/atlas/issues/525

**Comment by SilasK** [comment]
We encountered this error
Any idea what we can do now 

/checkm/storage/tree/concatenated.pplacer.json has no placements!"

**Comment by dparks1134** [comment]
Hi Silas,

Guppy is part of the pplacer package. I haven't run across either of the issues you've pointed out. The most common issue we see with pplacer is systems running out of RAM. 

Cheers,
Donovan
