### ISSUE TITLE
How to interpret the headers in the genes.faa file?

### ISSUE THREAD

**Issue by Laura-Alex** [Ecogenomics/CheckM#338]
Location: CheckM_results_folder/bins/particular_bin_name/genes.faa

Example:
`>S11Ck141_1266183_1 # 92 # 1255 # 1 # ID=1_1;partial=00;start_type=ATG;rbs_motif=AGGA/GGAG/GAGG;rbs_spacer=11-12bp;gc_cont=0.519`

The first part ('S11Ck141_1266183') looks like the name of an inputted contig, with the additional '_1' (or '_2', or '_16' marking the order of the CDS on the contig. I assume this order is also connected with the 'ID=1_1' part of the name (e.g. 'first contig, first CDS'). The parts afterwards appear to offer additional information (whether the CDS is partial...). 

But I am especially intrigued about the bits between the # (`# 92 # 1255 # 1 # `). I suspect they might represent, in some way, which marker gene this is, which would actually be what I want. I am trying to figure out, for bins / genomes from a particular phylum, which marker genes are shared by most of them (in order to build phylogenetic trees).

It feels like bin_stats_ext.tsv and marker_gene_stats.tsv from /storage are important for this, but I can't quite figure out how the numbers link to TIGRFAM / PFAM codes. I would really appreciate someone taking the time to explain this to me!

(Also, thank you for the software. it's very useful)

**Comment by dparks1134** [comment]
This header information is produced by Prodigal.
