### ISSUE TITLE
Extrapolate USCG sequences from samples 

### ISSUE THREAD

**Issue by ereynebeau** [Ecogenomics/CheckM#339]
I am attempting to pull identified marker gene nucleotides from my sequences.  

Context: I am designing a high throughput method to quantify prokaryote biomass, and had previously been using qPCR on the 16S rRNA gene as a proxy for cell numbers.  Of course, 16S is variable in gene copy number.  When I learned about universal single copy genes (USCG), I started searching for a way to identify highly conserved regions in my samples that are universally present in only one copy.  I'd then like to use this data to design primers for qPCR analysis.  I have access to several metagenomes, some very deep, from my study site. 

Question: Can I obtain the USCG sequences from my samples? CheckM seems like it has the information I am looking for, but I haven't been able to pull it out.  It seemed like qa output format 9 (FASTA file of marker genes) was close, but I think amino acids are essentially useless for me here. Is there a way to produce a nucleic acid FASTA? My next attempt was to add the --nt flag in the analyze command, but I'm not exactly sure how to interpret this or compare across bins.  Maybe the answer for issue #338 would help answer this. 

Ideally, I would want the nucleotide sequence for USCG X for bins 1-n, USCG Y for bins 1-n, etc. Of course I don't expect this to be laid out so cleanly, but do you think extrapolating this information is possible, and how would you go about it?

**Comment by dparks1134** [comment]
Hi,

I don't believe there is a way to get the nucleotide sequences for the genes used by CheckM. Perhaps something like this would meet your requirements:
https://academic.oup.com/bioinformatics/article/37/15/2081/6124302

Cheers,
Donovan
