### ISSUE TITLE
Continue/Update Option

### ISSUE THREAD

**Issue by hunter-cameron** [Ecogenomics/CheckM#34]
I think it would be useful to have a feature (probably as a command line option) to allow users to add new genomes to the genome bins directory of past CheckM analyses and then rerun CheckM in "update" mode where only the new files are processed and all output files are updated to reflect the additions.

We have a continually growing database of several hundred bacterial genomes that we like to keep up-to-date CheckM analyses for and it consumes a fair bit of unnecessary computation time to run the full analysis over when we add a few new genomes.

**Comment by dparks1134** [comment]
Hey Cameron,

Which results are you after that require all genomes to be processed at once? I always imagine people just running new genomes separately. The CheckM results for a given genome are independent of the other genomes being processed.

**Comment by hunter-cameron** [comment]
Hi,

It's completely a convenience function aimed at being able to update the output files so that I could run the qa and plotting commands on the whole dataset to get complete summary files. 

I figured CheckM would look in the storage directory and read in already processed files in order to generate the plots/summary output. And I figured these storage files are generated fresh each time I run CheckM such that the most recent one overwrites older ones. I'm basing this off the .tsv files in the storage directory. I can't tell if information is being calculated from them or if everything is being done from scratch for each genome when I run summary commands and then the concatenated result is being given to me.  

Anyway, I imagined that if I ran CheckM on 100 genomes and then later ran CheckM again using the same output directories on one more genome, that the output from the single genome would overwrite the output from the 100 and I would effectively lose the analysis on them. Is this the case or does CheckM read/store the data in such a way that running an analysis like that would give me 101 genomes (what I want it to do) instead of 1?

**Comment by dparks1134** [comment]
No, it will not update the processed genomes so you have results for 101. Actually, the *lineage_wf* command will refuse to run if you provide it with an existing directory so previous results are not overwritten. 

I agree some sort of *update* command would be useful, but this is unlikely to happen in the short term. I suggest just processing new genomes to a new output directory. This wouldn't help with generating plots, but it is easy enough to concatenate tables together.
