### ISSUE TITLE
The positions of marker genes are shown in the hundreds of bp

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [Ecogenomics/CheckM#340]
Hi,

I ran the test genome bin (637000110.fna), the fna file that was used to unit test the CheckM.

I did a checkm qa, output format 8, to output the positions of the marker genes.

![image](https://user-images.githubusercontent.com/63221307/173980573-14ac6171-47d7-4ee4-ac1e-3d86484dcec1.png)

However, I found that the positions of marker genes are always in the hundreds of bp, which cannot be right, since the genome  had 4.65 million bp.

What is the problem?

**Comment by dparks1134** [comment]
Hi. The start and end position are relative to the gene and not the genome.
