### ISSUE TITLE
pplacer never ends

### ISSUE THREAD

**Issue by lucaz88** [Ecogenomics/CheckM#341]
Hi,
I started to run checkm, either directly or through drep, on a cluster computer via the command sbatch but every time the process stops when placing bins in the genome tree and eventually the task gets cancelled due to time limit:

> [2022-06-20 03:01:56] INFO: Reading marker alignment files.
> [2022-06-20 03:01:56] INFO: Concatenating alignments.
> [2022-06-20 03:01:56] INFO: Placing 201 bins into the genome tree with pplacer (be patient).
> slurmstepd: error: *** JOB 2116389 ON n412-060 CANCELLED AT 2022-06-20T04:59:37 DUE TO TIME LIMIT ***

If I check with `top` there is no process running. However, if I run the same commands in local or login node of the cluster it successfully finishes in a few minutes!
Any idea why? Does the pplacer step needs ftp access (as I know that this is not possible in our computational nodes)?

This is an example of the checkm command I am running:

`checkm lineage_wf all_bins/ checkm/ -f checkm/results.tsv -t 88 --pplacer_threads 88 -x fa --tab_table`

Thanks in advance for any input!

**Comment by dparks1134** [comment]
Hi,

`pplacer` has a number of interesting "features". We've noticed that it can be problematic to run it with more than 64 CPUs. No real idea why, just something that we have observed. I'd suggest trying it with 64 CPUs and see if this solves the issue.

Cheers,
Donovan

**Comment by lucaz88** [comment]
Ahahaaa :)
Setting cores to 60 worked indeed! 
Thanks a lot Donovan!
