### ISSUE TITLE
URL for reference data not working

### ISSUE THREAD

**Issue by yakshiUPR** [Ecogenomics/CheckM#342]
Hi, 

I just finished installing CheckM, and I saw that I have to download the reference data using the following URL:
https://data.ace.uq.edu.au/public/CheckM_databases/

However, when I try to open it, its not working at least for me. 
I ended up getting on this webpage, which I figured its related to CheckM, but I can't find the reference data there either. Is there an updated URL? Or is it working, but somehow not for me? 

Thanks, 
Yakshi

**Comment by dparks1134** [comment]
Hi Yakshi,

The URL is indeed down. I've asked our sys admin to look into the issue. Hopefully it will be back up after the weekend.

Cheers,
Donovan

**Comment by dparks1134** [comment]
Hi. The issue with the URL has been resolved.
