### ISSUE TITLE
Completeness analysis by checkm

### ISSUE THREAD

**Issue by ramnageena11** [Ecogenomics/CheckM#344]
I want to use checkm for assessing the completeness of assembly generated by Metagenome (nanopore reads). I could not find the scripts to run for analysis. Pls help what combination i should use? i found this in help......
checkm
              {data,tree,tree_qa,lineage_set,taxon_list,taxon_set,analyze,qa,lineage_wf,taxonomy_wf,gc_plot,coding_plot,tetra_plot,dist_plot,gc_bias_plot,nx_plot,len_hist,marker_plot,unbinned,coverage,tetra,profile,ssu_finder,merge,outliers,modify,unique,test}

**Comment by ramnageena11** [comment]
hi pls suggest.
thanks

**Comment by dparks1134** [comment]
Here is the wiki that indicates how to run CheckM:
https://github.com/Ecogenomics/CheckM/wiki
