### ISSUE TITLE
error with checkM test

### ISSUE THREAD

**Issue by ysevel** [Ecogenomics/CheckM#345]
I tried the checkm test commad and got the following error:

sh: line 1: 395425 Killed                  pplacer -j 1 -c /home/genouest/cnrs_umr6553/ysevellec/checkm_data/genome_tree/genome_tree_reduced.refpkg -o /groups/geh/analysis/checkm_test/results/storage/tree/concatenated.pplacer.json /groups/geh/analysis/checkm_test/results/storage/tree/concatenated.fasta > /groups/geh/analysis/checkm_test/results/storage/tree/pplacer.out
Uncaught exception: Sys_error("/groups/geh/analysis/checkm_test/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/groups/geh/analysis/checkm_test/results/storage/tree/concatenated.pplacer.json: No such file or directory")

I'm quite confused that the program killed the job as it cannot find its own output file. anything I'm missing?

Best regards,

**Comment by themudo** [comment]
I am getting a similar error, after installing checkM with conda. I am running CheckM v1.2.0 on Ubuntu installed through wsl on a WIndows 10 machine. I as trying to run the lineage workflow with about 400 genomes.

**Comment by themudo** [comment]
> I am getting a similar error, after installing checkM with conda. I am running CheckM v1.2.0 on Ubuntu installed through wsl on a Windows 10 machine. I as trying to run the lineage workflow with about 400 genomes.

I seem to have solved my issue by running the workflow with the --reduced_tree option.

**Comment by dparks1134** [comment]
A `killed` error usually indicates CheckM has exceed the available memory of your machine.
