### ISSUE TITLE
unknown command data

### ISSUE THREAD

**Issue by brandentimm** [Ecogenomics/CheckM#36]
Following the installation instructions here: https://github.com/Ecogenomics/CheckM/wiki/Installation

After installing version 0.4 using pip, I ran 'checkm data update', and got the following error:

unknown command: data

The checkm help also does not list a 'data' command:

checkm
checkm [options] command filenames

Commands:

checkm write [checkm filename (default:checkm.txt) [filepath (default='.')]]
    - writes a checkm manifest file to disc for the files in the given filepath. 
      Use -r to include all files under a given path in a single manifest.
      
checkm print [filepath (default='.')]
    - As for 'write', but will print the manifest to the screen.
      
checkm multi [checkm filename (default:checkm.txt) [filepath (default='.')]]
    - writes a checkm manifest file to disc for the files in the given filepath, recursively creating a manifest file within each subdirectory and using the '@' designation in the parent checkm files above it.
      
checkm check [checkm filename (default:checkm.txt)]
    - checks the given checkm manifest against the files on disc.
      Use -m to recursively scan through any multilevel checkm files it finds in this manifest as well.

checkm remove_multi [checkm filename (default:checkm.txt)]
    - scans through the checkm file, recursively gathering a list of all included checkm manifests, returning the list of files.
      Use the option '-f' or '--force' to cause the tool to try to delete these checkm files.

**Comment by ctSkennerton** [comment]
Hello Branden,

There are multiple software packages on pip with checkm in the name. I think that you may have downloaded a different one. I think that you actually got [this one](https://pypi.python.org/pypi/Checkm/0.4), which is "text-based file manifest format". make sure that use used the command `pip install checkm-genome`, the latest version is 1.0.3

**Comment by brandentimm** [comment]
Ah, indeed.  Thanks!
