### ISSUE TITLE
Checkm data still available?

### ISSUE THREAD

**Issue by standage** [Ecogenomics/CheckM#362]
Greetings!

I am unable to resolve https://data.ace.uq.edu.au/public/CheckM_databases/ in my web browser nor the tarball URL from the command line with curl/wget. Is this resource still live? Is there any way a copy of this data can be deposited in a legit archive such as figshare or zenodo?

**Comment by dparks1134** [comment]
Should be up again now.

**Comment by standage** [comment]
Can confirm. Thanks!

(My suggestion regarding depositing the file in a reliable public archive still stands. Uptime aside, academic websites are notorious victims to department reorganizations, P.I. relocations, and so on.)

**Comment by dparks1134** [comment]
CheckM reference data has been placed on Zenodo:
https://zenodo.org/record/7401545#.Y44ymHbMJD8

**Comment by azat-badretdin** [comment]
Any plans to update the reference set? There are some major changes in NCBI Taxonomy reflecting the global Taxonomy changes and it would be nice to have up to date taxonomically correct marker set...

**Comment by dparks1134** [comment]
CheckM v1 is no longer actively updated. Development effort is now on CheckM v2 that uses a machine learning approach to estimate genome quality: https://www.biorxiv.org/content/10.1101/2022.07.11.499243v1.

**Comment by azat-badretdin** [comment]
Thanks, we will take a look

**Comment by standage** [comment]
> CheckM reference data has been placed on Zenodo

Fantastic. Thank you!
