### ISSUE TITLE
Is there a possibility to have the distance between the putative genome and the closest reference genome?

### ISSUE THREAD

**Issue by dgrissa** [Ecogenomics/CheckM#363]
As part of my research work, I would like to know the different reasons for having genomes with bad scores for completeness usng CheckM. For that, I would like to know the distance between the putative genome and the closest reference genome. Would that be possible or easy to compute? Thank you in advance for your answer.

**Comment by donovan-h-parks** [comment]
CheckM v1 is no longer in active development. I believe the CheckM output contains a Newick tree with your genomes as placed using `pplacer`.  You should be able to pull the information from this tree though I don't know a program that can generate the exact information you are after.
