### ISSUE TITLE
Placing 3 bins into the genome tree with pplacer Killed

### ISSUE THREAD

**Issue by iquasere** [Ecogenomics/CheckM#366]
Hi there! I am trying to run some github actions [where CheckM is failling](https://github.com/iquasere/MOSCA/actions/runs/3808833487/jobs/6479815951#step:6:2350), but this doesn't happen when I run the same actions locally. Is this ```Placing 3 bins into the genome tree with pplacer``` step very memory intensive? 

What could be killing the process, and what could I do to circunmvent it? It's only three bins at that stage that are being profiled, and in the same actions there is an assembly and an annotation of the same data that run fine.

**Comment by donovan-h-parks** [comment]
Yes, the pplacer step is memory intensive and the peak memory usage is largely independent of the number of bins being placed. You can find system requirements at https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements.

**Comment by iquasere** [comment]
Any way to decrease the memory consumption?

**Comment by donovan-h-parks** [comment]
The `taxonomy_wf` requires far less memory if this fits you application. The `lineage_wf` does have a `--reduced_tree` flag as explained here: https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements.

**Comment by iquasere** [comment]
Thank you, I'll try those
