### ISSUE TITLE
Placing bins in reference genome tree problem

### ISSUE THREAD

**Issue by ezaikova** [Ecogenomics/CheckM#37]
Hi, 

I am having issues with "checkm tree". I installed checkm earlier this week and the "test" ran just fine. However, when I tried to analyze my bins, I got the error below. I tried running the "tree" command on the test data (which worked for "test") and still got the same error.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 4 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 4 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 4 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 4 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("./testOUT/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("./testOUT/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:21:44.524 || Total: 0:21:44.524 }

I tried updating the CheckM dependency data with "sudo checkm data update", which didn't help, so then I downloaded the CheckM data (v1.0.3) and used "sudo checkm data setRoot" to point to the new directory. I still got the same error. 

I am not sure if the issue is in my installation or if something is missing.

Best, 

Elena

**Comment by dparks1134** [comment]
Hello,

I haven't run across this issue before. Can you send me the exact command you are running? Also, can you verify that the file <code>./testOUT/storage/tree/concatenated.pplacer.json</code> exists.

Cheers,
Donovan

**Comment by ezaikova** [comment]
Hi Donovan,

I ran the command 

~ $ checkm tree ~/checkm/test_data/ ~/Desktop/tree_testOUT/
(same result with checkm lineage_wf -t 4 ~/checkm/test_data/ ~/Desktop/tree_testOUT/)

and got the error below 
![checkm_tree_error](https://cloud.githubusercontent.com/assets/13909709/9446232/4b461790-4a45-11e5-9f32-9a880eb94dac.png)

tree_testOUT/storage/tree/concatenated.pplacer.json does not exist (tree_testOUT/storage/tree directory contents below)
![checkm_tree_test_stdout](https://cloud.githubusercontent.com/assets/13909709/9446291/a7627d70-4a45-11e5-80c6-38def2238521.png)

However, running 

~ $ checkm test ~/Desktop/checkm_testOUT

seems to have worked, and the concatenated.pplacer.json file does exist

![checkm_test_stdout](https://cloud.githubusercontent.com/assets/13909709/9446513/02319f32-4a47-11e5-8276-f3ff145aa470.png)

Cheers, 

Elena

**Comment by dparks1134** [comment]
Hello,

CheckM appears to be crashing when calling <code>pplacer</code>. Can you verify that you are using the latest version of pplacer (v2.6.32; also called v1.1.alpha16). Alternatively, it may be a subtle issue with your genome that I have not encountered. I'd be happy to look into it if you want to send me your genome.

Cheers,
Donovan

**Comment by ezaikova** [comment]
Hello, 

I am running pplacer-v1.1.alpha16. I also wondered whether there was an issue with my genomic data, so I used the E. coli genome provided in the test_data directory (/checkm/test_data/637000110.fna) to test checkm tree and checkm lineage_wf. The above results are using 637000110.fna. 

Thanks for your help. 

Elena

**Comment by wwood** [comment]
Given the output has the line `Killed` did pplacer run out of memory?

**Comment by dparks1134** [comment]
Good call Ben. Elena, how much memory (RAM) does your machine have? If you have <32GB, you should pass the --reduced_tree flag which works on machines with 16GB.

**Comment by ezaikova** [comment]
Thanks, that was the problem. I've increased the RAM on my VM. Thanks so much!

Elena
