### ISSUE TITLE
Reference data is missing

### ISSUE THREAD

**Issue by tiagocabralborelli** [Ecogenomics/CheckM#370]
Hello
Where can I find the universal reference genes data set to download?

**Comment by donovan-h-parks** [comment]
HMMs for the different marker sets used by CheckM can be found in the `hmms` directory of the CheckM reference data. Unfortunately, I don't think there is an easy way to get a particular set of marker genes. All HMMs are stored in a single file (phylo.hmm or checkm.hmm). You would need to extract the HMMs for the marker genes you are interested in.
