### ISSUE TITLE
Understanding contamination value

### ISSUE THREAD

**Issue by stephane-wang** [Ecogenomics/CheckM#374]
Hi, 

I am working on raw bacterial reads and I did de-novo genome assembly on my raw reads and I wanted to assess the quality of my assemblies with CheckM. So I ran lineage_wf on my dataset but some of the genomes show a level contamination above 100%, one even has a level contamination of ~480%. And would like to understand this value.

Thanks for your help.

**Comment by ramay** [comment]
I found an issue where it is explained https://github.com/Ecogenomics/CheckM/issues/318
