### ISSUE TITLE
ERROR conda.core.link:_execute(952): An error occurred while installing package 'bioconda::checkm-genome-1.2.2-pyhdfd78af_1'.

### ISSUE THREAD

**Issue by RoyaRahmani** [Ecogenomics/CheckM#375]
Hi I am trying to install CheckM-Genome from Bioconda on ubunro 22.04. 
I encountered an issue while trying. 
It seems like the file "checkm_data_2015_01_16.tar.gz" in address [ https://zenodo.org/record/7401545/files/checkm_data_2015_01_16.tar.gz ] is not available any more.
I would like to know how I can resolve this issue and proceed with the proper installation of CheckM on my system.
Thanks.

**Comment by RoyaRahmani** [comment]
The environment's packages are:
**conda list -n checkm**
# packages in environment at /home/roya/anaconda3/envs/checkm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py37h06a4308_0  
curl                      7.71.1               h8f29fe8_2  
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
expat                     2.4.9                h6a678d5_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h5eee18b_3  
glib                      2.69.1               he621ea3_2  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
**hmmer                     3.3.2                h87f3376_2    bioconda**
icu                       58.2                 he6710b0_3  
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.3.2            py37h295c915_0  
krb5                      1.19.4               h568e23c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcurl                   7.71.1               h303737a_2  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20221030         h5eee18b_0  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libllvm14                 14.0.6               hdb19cb5_3  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.9                 h16c4e8d_3  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.2.0                hecacb30_2  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.3               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
lz4-c                     1.9.4                h6a678d5_0  
matplotlib                3.5.3            py37h06a4308_0  
matplotlib-base           3.5.3            py37hf590b9c_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
munkres                   1.0.7                      py_1    bioconda
ncurses                   6.4                  h6a678d5_0  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
**numpy                     1.21.5           py37h6c91a56_3**  
numpy-base                1.21.5           py37ha15fc14_3  
openssl                   1.1.1t               h7f8727e_0  
packaging                 22.0             py37h06a4308_0  
pcre                      8.45                 h295c915_0  
pillow                    9.4.0            py37h6a678d5_0  
pip                       22.3.1           py37h06a4308_0  
ply                       3.11                     py37_0  
**pplacer                   1.1.alpha19          h9ee0642_2    bioconda**
**prodigal                  2.6.3                hec16e2b_4    bioconda**
pyparsing                 3.0.9            py37h06a4308_0  
pyqt                      5.15.7           py37h6a678d5_1  
pyqt5-sip                 12.11.0          py37h6a678d5_1  
pysam                     0.15.3           py37hda2845c_1    bioconda
**python                    3.7.16               h7a1cb2a_0**  
python-dateutil           2.8.2              pyhd3eb1b0_0  
qt-main                   5.15.2               h8373d8f_8  
qt-webengine              5.15.9               hbbf29b9_6  
qtwebkit                  5.212                h3fafdc1_5  
readline                  8.2                  h5eee18b_0  
setuptools                65.6.3           py37h06a4308_0  
sip                       6.6.2            py37h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.2              py37h5eee18b_0  
wheel                     0.38.4           py37h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by donovan-h-parks** [comment]
Hi. I don't maintain the bioconda release of CheckM. If you found a resolution to this, please post it here for others. Sorry I can't be of any direct help.
