### ISSUE TITLE
"checkm tetra" fails on lowercase sequence data

### ISSUE THREAD

**Issue by fungs** [Ecogenomics/CheckM#38]
Depending on the assembler and primary sequence data, contigs can contain lowercase letters. This leads to 'nan' values in the output of the tetra command. The workaround is to map the sequence data to upper case before. However, this should be handled in Python very easily.

**Comment by dparks1134** [comment]
Thanks for the bug report. This has been fixed for v1.0.4 which I plan to release shortly.
