### ISSUE TITLE
maximum number of genomes/MAGs to run checkm

### ISSUE THREAD

**Issue by sapuizait** [Ecogenomics/CheckM#380]
what the title says

I have been trying to run checkm on a 64 cores, 500GB RAM machine to get the genome stats for a bit more than 12000 MAGs but it gets stuck at the "Placing 12279 bins into the genome tree with pplacer (be patient)." step.

Is it unrealistic to try to run it in more than  3-4k genomes/MAGs?
Should I always split in chunks of a few thousand MAGs? whats your recommendation? 

Thanks

**Comment by donovan-h-parks** [comment]
Hi. Yes, I recommend splitting the job up into smaller batches:
https://github.com/Ecogenomics/CheckM/wiki/Bugs-and-Feature-Requests#processing-large-numbers-of-genomes

**Comment by 98jay** [comment]
=

**Comment by sapuizait** [comment]
ah yes! Thank you. 
The 12279 MAGs could not run BUT chunks of 3070 MAGs in 32 processor/128G machines worked nicely!
