### ISSUE TITLE
Having trouble interpreting the meaning of "root" as a marker lineage

### ISSUE THREAD

**Issue by jackieway** [Ecogenomics/CheckM#388]
Hello, I'm running CheckM on KBase (Assess Genome Quality with CheckM - v1.0.18). I first used MetaBAT2 on KBase (MetaBAT2 Contig Binning - v1.7) to bin an assembled metagenome, resulting in 4 bins. When I ran CheckM on the 4 bins, it resulted in the below table. What does a marker lineage of "root" mean for bin 3? I'm having trouble interpreting the results. When I ran GTDB-Tk - v2.3.2 on KBase, it classified bin 3 as an "unclassified bacteria", with a warning "Insufficient number of amino acids in MSA (0.7%)".

Bin Name	Marker Lineage	# Genomes	# Markers	# Marker Sets	0	1	2	3	4	5+	Completeness	Contamination
[bin.001](https://kbase.us/dynserv/66e9a37e7d3a56b64cc372c89d1eaafaa605c397.HTMLFileSetServ/api/v1/169410/14/1/$/0/bin.001.html)	k__Bacteria	5449	104	58	51	53	0	0	0	0	79.31	0.0
[bin.002](https://kbase.us/dynserv/66e9a37e7d3a56b64cc372c89d1eaafaa605c397.HTMLFileSetServ/api/v1/169410/14/1/$/0/bin.002.html)	g__Clostridium	44	404	145	4	399	1	0	0	0	98.31	0.69
[bin.003](https://kbase.us/dynserv/66e9a37e7d3a56b64cc372c89d1eaafaa605c397.HTMLFileSetServ/api/v1/169410/14/1/$/0/bin.003.html)	root	5656	56	24	56	0	0	0	0	0	0.0	0.0
[bin.004](https://kbase.us/dynserv/66e9a37e7d3a56b64cc372c89d1eaafaa605c397.HTMLFileSetServ/api/v1/169410/14/1/$/0/bin.004.html)	o__Clostridiales	50	332	124	17	312	2	0	1	0	95.16	4.03

**Comment by RuoqiWANG01** [comment]
Hi,
root means checkM cannot confirm whether bin3 is bacteria. Bin3 didn't have any sign-copy match (0 1 2 3 4 5+ are all 0).
