### ISSUE TITLE
Make sure pplacer is on your system path.

### ISSUE THREAD

**Issue by apjim0527** [Ecogenomics/CheckM#389]
Hi, please help me to solve the error: "make sure pplacer is on your system path."

I can't seem to search the steps in downloading and installing pplacer.

**Comment by danielle-dzd** [comment]
Instructions are [here](https://matsen.github.io/pplacer/compiling.html)

**Comment by apjim0527** [comment]
Thanks to D. Peterson for this useful solution https://matsen.github.io/pplacer/compiling.html. The issue is solved.
