### ISSUE TITLE
checkm tree_qa throws AttributeError

### ISSUE THREAD

**Issue by AdvancedBiomeasurementsResearchGroup** [Ecogenomics/CheckM#40]
Hi,

I am using checkM version 1.0.3. I installed all yesterday, ran the "checkm test" and no issues came up.

Now, I got an error when analyzing my own genome bins, as explained below:
------------------------------------------------------------------------------------------------------------------
command 1: checkm tree -t 20 ./ ./checkm_tree -x .fa
# completed with no issues
command 2: checkm tree_qa -f ./checkm_tree.txt ./checkm_tree
# error
*******************************************************************************
 [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 3600 of 3600 (100.00%) bins.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/srv/sw/checkm/1.0.3/bin/checkm", line 709, in <module>
    checkmParser.parseOptions(args)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/main.py", line 1197, in parseOptions
    self.treeQA(options)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/main.py", line 177, in treeQA
    treeParser.printSummary(options.out_format, options.tree_folder, RP, options.bTabTable, options.file, binStats)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/treeParser.py", line 633, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/treeParser.py", line 216, in getBinTaxonomy
    domainNode = self.__findDomainNode(node)
  File "/srv/sw/checkm/1.0.3/lib/python2.7/site-packages/checkm/treeParser.py", line 237, in __findDomainNode
    curNode = curNode.parent_node
AttributeError: 'NoneType' object has no attribute 'parent_node'
------------------------------------------------------------------------------------------------------------------

Would it be possible to clarify? Maybe I am running the commands incorrectly or my installation is faulty ...

Thank you very much in advance for your help.

Dieter.

**Comment by dparks1134** [comment]
Hello Dieter,

It looks like you are running CheckM correctly. Perhaps this is a bug that we have not encountered. I noticed that you are running a lot of genomes through CheckM (3600!). Can you try running just a few genomes (say, 2 or 3) to see if the problem persists? If so, it should be easier to determine what is happening.

Cheers,
Donovan

**Comment by AdvancedBiomeasurementsResearchGroup** [comment]
Hi Donovan,

Thank you for the quick response. Yes, I used many bins ... I guess I was not expecting any trouble due to the number of bins.

I tried your suggestion of running with less bins/genomes (I used 2) and now it completed without error. Not sure what is happening or at what point (how many genomes) the process gives the error ...

At this point I will run in smaller batches and remove some bins.

Thanks again !!!

Dieter.

**Comment by dparks1134** [comment]
The number of bins shouldn't matter. My guess is one of the bins is problematic. If you can identify which bin it is, I can determine why it is causing a problem.

**Comment by AdvancedBiomeasurementsResearchGroup** [comment]
Ok, I will run a loop and then see which one fails. Btw, I just tested a subset of 504 and no issues ...

**Comment by dparks1134** [comment]
I am assuming this can be closed as there has been no follow-up in over a month.
