### ISSUE TITLE
Check-M test fails at step two.

### ISSUE THREAD

**Issue by Ashmita005** [Ecogenomics/CheckM#41]
hi 

I have just installed Check M and get the following response in the installation test at step two
 
IOError: [Errno 2] No such file or directory: '/home/ashmita/checkm_test_results/results/storage/tree/concatenated.tre

Any advice as to how to fix it will be appreciated. 

thank you 
ashmita

**Comment by dparks1134** [comment]
Hello Ashmita,

Can you please post the full output from CheckM. It is clear what the problem is just from the IOError message. Also, you might just try running CheckM on a set of your own bins/genomes to see if that works or at least provides a more informative error message.

Cheers,
Donovan

**Comment by Ashmita005** [comment]
Hello Donovan

So as requested I have used Check M on a set of my own bins and here is the full output received. 

ashmita@ashmita-VirtualBox:~/Documents/programms$ checkm lineage_wf -t 5 -x fa /home/ashmita/Documents/bins /home/ashmita/Documents/resultscm

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 26 bins with 5 threads:
    Finished processing 26 of 26 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 26 bins with 5 threads:
    Finished processing 26 of 26 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 26 of 26 (100.00%) bins.
  Extracting 43 HMMs with 5 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 5 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 26 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("/home/ashmita/Documents/resultscm/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/home/ashmita/Documents/resultscm/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:01:39.226 || Total: 0:01:39.226 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 26 of 26 (100.00%) bins.

  Determining marker sets for each genome bin.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 710, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1241, in parseOptions
    self.lineageSet(options)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 226, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/usr/local/lib/python2.7/dist-packages/checkm/treeParser.py", line 477, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/usr/local/lib/python2.7/dist-packages/dendropy/datamodel/basemodel.py", line 217, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/usr/local/lib/python2.7/dist-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/home/ashmita/Documents/resultscm/storage/tree/concatenated.tre'

It is roughly the same error as when I try to run the installation test.. 

Your help will be appreciated
Thank you 
Ashmita

**Comment by dparks1134** [comment]
Helllo Ashmita,

Pplacer appears to be crashing which is likely because you are running out of memory. CheckM requires ~32Gb to place genomes into its full reference tree. You can reduce this to just under 16Gb by using the <code>--reduced_tree</code> flag. Alternatively, you can use the taxonomy_wf if you know the taxonomic identity of the bins you wish to process with CheckM.

**Comment by Ashmita005** [comment]
Thank you Donovan, It now works

**Comment by Buuntu** [comment]
@dparks1134 I get this error too when running CheckM under AWS Batch

**Comment by dparks1134** [comment]
It is likely a memory issue. CheckM requires ~32Gb to place genomes into its full reference tree. You can reduce this to just under 16Gb by using the --reduced_tree flag. Alternatively, you can use the taxonomy_wf if you know the taxonomic identity of the bins you wish to process with CheckM.

**Comment by Buuntu** [comment]
@dparks1134 Yep that's the issue, when setting an AWS Batch job to run with a minimum amount of memory of 32 GB, it works fine.  Would it not be useful for CheckM to error out at the start or at least give a warning if the memory requirements are not met?
