### ISSUE TITLE
Question regarding to taxonomy classification

### ISSUE THREAD

**Issue by donkang75** [Ecogenomics/CheckM#43]
This is one of typical examples I have:

tree_qa output:
TH03311              43                   0         k__Bacteria;p__Bacteroidetes;c__Bacteroidia;o__Bacteroidales;f__Porphyromonadaceae

qa output:
TH03311        k__Bacteria (UID2569)            434         278           186         5    270    3    0    0    0       97.85            1.12               0.00

So, my question is that why in many cases qa output predict higher taxon rank than tree_qa. Should I ignore tree_qa output? Where does the discrepancy come from?

It would be great to have some good explanation of it. Thanks!

**Comment by dparks1134** [comment]
The <code>tree_qa</code> indicates the placement of your bin within CheckM's reference genome tree. It appears your bin/genomes is in the familiy f__Porphyromonadaceae. The <code>qa</code> output indicates information about the marker set that was used to evaluate your bin. In this case, it was a marker set outside the p__Bacteroidetes, but within the domain k__Bacteria. The results here may represent some issues with the taxonomic assignment of IMG's reference genomes. The <code>qa</code> command indicates that a domain level set was used, but that this set consisted of 434 genomes. There are 419 p__Bacteroidetes genomes in the CheckM reference genome tree so it appears your bin is essentially being assessed with a p__Bacteroidetes-specific set of markers. We are currently working on cleaning up the taxonomic assignment of reference genomes to help clarify situations like this. Note that UID2569 indicate a specific node in CheckM's reference tree. You can use the <code>tree_qa</code> command to generate a newick tree and look at exactly where your bin was placed and what genomes are below node UID2569.
