### ISSUE TITLE
Too many bins to plot?

### ISSUE THREAD

**Issue by mdehollander** [Ecogenomics/CheckM#44]
Hi,

I get the following error:
```
*******************************************************************************
 [CheckM - bin_qa_plot] Creating bar plot of bin quality.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.
  Plotting bin completeness, contamination, and strain heterogeneity.

Unexpected error: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "/data/tools/CheckM/0.9.7/bin/checkm", line 717, in <module>
    checkmParser.parseOptions(args)
  File "/data/tools/CheckM/0.9.7/lib/python2.7/site-packages/checkm/main.py", line 1240, in parseOptions
    self.binQAPlot(options)
  File "/data/tools/CheckM/0.9.7/lib/python2.7/site-packages/checkm/main.py", line 820, in binQAPlot
    plot.plot(binFiles, binStatsExt, options.bIgnoreHetero, aai.aaiHetero)
  File "/data/tools/CheckM/0.9.7/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 66, in plot
    xLabelBounds = self.xLabelExtents(sortedBinIds, self.options.font_size)
  File "/data/tools/CheckM/0.9.7/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 105, in xLabelExtents
    bbox = label.get_window_extent(self.get_renderer())
  File "/mnt/data/home/NIOO/mattiash/.virtualenvs/groopm/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 481, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/mnt/data/home/NIOO/mattiash/.virtualenvs/groopm/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 94, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768
```

I assume there are too many bins to plot, because the width and height is too large to be plotted with matplotlib. I have 202 bins. Are this indeed too many bins to plot with CheckM? I did not find any parameter to limit/filter the number of bins to be plotted.

**Comment by dparks1134** [comment]
Hello Mattias,

In the next version of CheckM, I will put in some options to only plot a specific number of the "best" bins. In the meantime, there are two workarounds. You can reduce the DPI (<code>--dpi</code>) as this will allow more bins to be plotted. Alternatively, you can create a directory with only the bins you really want to have plotted (202 is a lot to look at!) and point the <code>bin_qa_plot</code> command to this directory. I usual create a directory and symlink to the bins that are good enough to consider for further processing and are including in a manuscript.

Cheers,
Donovan

**Comment by mdehollander** [comment]
Hi Donovan,

Thanks! I will have a look at that and make a selection of bins. I have to see why there are so many bins.

Greetings,
Mattias

**Comment by xvazquezc** [comment]
Hi all,
I have been able to plot 507 bins from my data but after dealing with the `-dpi` option. But I never got the error showed above. Most of the times this was the error:

```
*******************************************************************************
 [CheckM - bin_qa_plot] Creating bar plot of bin quality.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.
[Error] There are too many bins to plot.
The resulting plot would be 100776 pixels in height and the maximum allowed size is 32768.
Please reduce the number of bins to be plotted or decrease the DPI (--dpi).

  { Current stage: 0:00:41.618 || Total: 0:00:41.618 }
```
Other alternative I tried was to set the output file format to svg but the size of the file (>167MB) makes it impossible to handle in Inkscape, or at least would take way to long to open.

**Comment by dparks1134** [comment]
Hello,
The bin_qa_plot command is really designed to provide a visualization of at most a few dozen bins. More than this and the plot quickly becomes unreasonably large. Generally, we select the best bins and place these in a separate folder. You can then produce a bin_qa_plot for just these bins.  I hope to add some filtering criteria to this plotting function in the future, but for now a manual  selection of the bins to plot is  required when you have more than a few  dozen bins.
