### ISSUE TITLE
AttributeError when using checkm coverage

### ISSUE THREAD

**Issue by jvollme** [Ecogenomics/CheckM#46]
When I run "checkm coverage"  I keep getting AttributeErrors. an outputfile is produced, but the coverage of every contig in every bin is given as zero.
I am using sorted an indexed Bam files (mappings done with bowtie, then converted to .bam-format, sorted and indexed using samtools).

This is the error I run into: 
```Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/coverage.py", line 208, in __workerThread
    elif read.is_secondary or read.is_supplementary:
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'is_supplementary'```

I am using CheckM v1.0.4
the command I ran is:
```checkm coverage -x fa -t 8 ./ checkm_coverage.out input/myinput_reads.BAM```

Edit: my pysam version is 0.8.2.1 (in case that may be part of the problem)

**Comment by dparks1134** [comment]
Hello,

This is a pysam version issue. The pysam interface is currently undergoing rapid revision. The CheckM coverage command requires pysam >= 0.8.3. I have updated the documentation to reflect this. Thank you for bringing this issue to my attention.

Cheers,
Donovan
