### ISSUE TITLE
checkm lineage_wf memory usage

### ISSUE THREAD

**Issue by xvazquezc** [Ecogenomics/CheckM#48]
Hi,
I've been recently started to use CheckM to evaluate the bins from my metagenomic data but I'm getting stuck in the first step of lineage_wf due to the amount of memory the program is using. I even tried the -r option but it exceeds 80 GB of requested memory instead of being limited to ~14GB as exposed in the Quick Start page of the CheckM wiki.

Any solution for this? Thank you

My bins folder contains 507 bins

My command:
checkm lineage_wf -r -t 8 -x fa ./bins ./outdir

Log:
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 507 bins with 8 threads:
    Finished processing 0 of 507 (0.00%) bins.^M    [.....] Finished processing 507 of 507 (100.00%) bins.^M
  Saving HMM info to file.

  Calculating genome statistics for 507 bins with 8 threads:
    Finished processing 0 of 507 (0.00%) bins.^M    [.....] Finished processing 507 of 507 (100.00%) bins.^M

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 507 (0.20%) bins.^M    [.....] Finished processing 507 of 507 (100.00%) bins.^M$
  Extracting 43 HMMs with 8 threads:
    Finished extracting 0 of 43 (0.00%) HMMs.^M    [.....] Finished processing 507 of 507 (100.00%) bins.^M
  Aligning 43 marker genes with 8 threads:
    Finished aligning 0 of 43 (0.00%) marker genes.^M    [.....] Finished processing 507 of 507 (100.00%) bins.^M

  Reading marker alignment files.
  Concatenating alignments.
  Placing 507 bins into the genome tree with pplacer (be patient).
=>> PBS: job killed: vmem 135223554048 exceeded limit 85899345920

**Comment by dparks1134** [comment]
Hello,
This is a bit of a concern. It appears to be an issue with how pplacer handles threads. On our system, I can see that CheckM is using 13.9G with the <code>-r</code> options, but that right when pplacer is finishing it appears to spawn a number of threads which all indicate they are using 13.9G. I suspect they aren't actually using this memory, but perhaps it is being detected as such by PBS. 

Can you up the requested memory threshold for PBS? It would be helpful to know if this is at least a temporary solution. 

Cheers,
Donovan

**Comment by xvazquezc** [comment]
Hi Donovan,
I increased the memory up to 216GB using 2 nodes in the cluster and it completed without problems. The log indicates it used about 135GB of memory.
Cheers,
Xabier

**Comment by dparks1134** [comment]
Hello Xavier,

Glad to hear it worked. The peak memory usage does appear to be correct and is due to pplacer. I have released a new version of CheckM (v1.0.5) that allows the number of threads used by pplacer to be set. This can be used to substantially reduce the peak memory requirement (back to 14G if pplacer is only given 1 thread), at the cost of some extra computation time.

Cheers,
Donovan
