### ISSUE TITLE
tetra_plot: no files generated

### ISSUE THREAD

**Issue by xvazquezc** [Ecogenomics/CheckM#49]
Hi,
I've been trying to use tetra_plot, however although the program exits without error, it does not generate any graph or file. Any idea why it may happened?

Command:
checkm tetra_plot -x fa ./tetraout ./bins ./tetra/plots ./tetra_profile.tsv 95

Log file (some repetitive lines omitted):
*******************************************************************************
 [CheckM - tetra_plot] Creating tetra-distance histogram and delta-TD plot.
*******************************************************************************

  Plotting tetranuclotide distance plots for /srv/scratch/z3382651/meta_analysis/megahit_good/bins/water.1.fa (1 of 507)
    Plot written to: /srv/scratch/z3382651/meta_analysis/megahit_good/megahitout/checkmout/tetra/plots/water.1.tetra_dist_plots.png
  Plotting tetranuclotide distance plots for /srv/scratch/z3382651/meta_analysis/megahit_good/bins/water.10.fa (2 of 507)
    Plot written to: /srv/scratch/z3382651/meta_analysis/megahit_good/megahitout/checkmout/tetra/plots/water.10.tetra_dist_plots.png
  [............................]
  Plotting tetranuclotide distance plots for /srv/scratch/z3382651/meta_analysis/megahit_good/bins/water.98.fa (506 of 507)
    Plot written to: /srv/scratch/z3382651/meta_analysis/megahit_good/megahitout/checkmout/tetra/plots/water.98.tetra_dist_plots.png
  Plotting tetranuclotide distance plots for /srv/scratch/z3382651/meta_analysis/megahit_good/bins/water.99.fa (507 of 507)
    Plot written to: /srv/scratch/z3382651/meta_analysis/megahit_good/megahitout/checkmout/tetra/plots/water.99.tetra_dist_plots.png

  { Current stage: 0:27:41.679 || Total: 0:27:41.679 }

**Comment by dparks1134** [comment]
Hello,
Strange indeed. I can verify that it works for me using CheckM v1.0.5. 

I noticed that the output indicates absolute path names even though you specified relative path names as parameters. This is a bit odd since on my machine the paths are always relative. Perhaps you just changed to absolute paths at some point. If not, any chance you are pointing the output to a symlink directory. This could be an issue though I don't see why.  

Do the other plotting functions in CheckM work? I'm just wondering if this may somehow be related to matplotlib (the underlying Python library used to generate plots).

Cheers,
Donovan

**Comment by xvazquezc** [comment]
Hi Donovan,
I tried using absolute and relative path names and it didn't even create the folders. So I created them manually, ran it again but nothing.
gc_plot works fine. I had some problems with bin_qa_plot due to the large number of bins I have so I had to reduce --dpi down to 190, otherwise the graph was generated without further issues.
Cheers,
Xabier

**Comment by dparks1134** [comment]
Hey Xabier,
Interesting. So both with absolute and relative path names the command isn't creating the output directory? Is this correct? Still at a bit of a loss at what this means, but creating the output directory is one of the first things done by the command.
Cheers,
Donovan

**Comment by xvazquezc** [comment]
Hi Donovan,
That's correct. It doesn't create the output directory or the files.
Xabier

**Comment by dparks1134** [comment]
Hey Xabier,
The first thing the <code>checkm tetra_plot</code> command does is create the output directory so this seems to be at the heart of the issue. I'm not sure what the issue would be though as I would expect CheckM to complain if it couldn't create the directory. Also seems odd given that the other plotting commands are working. Can you confirm that you are using CheckM v1.0.5.
Cheers,
Donovan

**Comment by xvazquezc** [comment]
The cluster has CheckM v1.0.3. I just requested the update to the admin. I'll try again after updating. I'll tell you if I keep having the same problem or not.
