### ISSUE TITLE
Is there any way to de-contamination?

### ISSUE THREAD

**Issue by LouieF** [Ecogenomics/CheckM#51]
Hi ~

Since checkm can find the contamination as multiple copies of marker genes, is there any way to locate and remove these copies in contigs/scaffolds files?

Best
Yifan

**Comment by dparks1134** [comment]
Hello,

You can identify which contigs have multiple marker genes using the tables provided by the <code>qa</code> command. Specifically, have a look at tables 6 and 7 (e.g., checkm qa -o 6 <marker file> <output folder>). Please note that removing contigs/scaffolds that result in contamination without strong justification will largely invalidate the use of CheckM for estimating genome quality.

Cheers,
Donovan

**Comment by ctSkennerton** [comment]
Just to elaborate a bit on Donovan's point: The contamination is an estimate based on the marker genes, however it is possible (or likely) that contigs that originate from another organism may not contain marker genes. Simply removing contigs with the duplicated marker genes will improve the stats but may not mean that your genome is decontaminated and may give a false impression of quality.

**Comment by LouieF** [comment]
@dparks1134 @ctSkennerton  Cool! Thank you for explain it ! I think I need to re-bin it from the very beginning.

I will close this issue within today.

**Comment by dparks1134** [comment]
I am assuming this can be closed as there has been no follow-up in over a month.

**Comment by raw937** [comment]
How do you find the bad contig? I have tried checkm qa -o fasta -o 6 no luck. I am trying to find a bad contig

**Comment by dparks1134** [comment]
CheckM is not designed to identify the source of contamination. Take a look at RefineM (https://github.com/dparks1134/RefineM) or MAGpurify (https://github.com/snayfach/MAGpurify).

**Comment by raw937** [comment]
Hello Donovan, 

Having trouble with refineM install. 
I have the same problem and issue.
Traceback (most recent call last):
File "/usr/local/bin/refinem", line 33, in
from refinem.main import OptionsParser
File "/usr/local/lib/python2.7/dist-packages/refinem/main.py", line 23, in
from refinem.scaffold_stats import ScaffoldStats
File "/usr/local/lib/python2.7/dist-packages/refinem/scaffold_stats.py", line 29, in
from refinem.coverage import Coverage
File "/usr/local/lib/python2.7/dist-packages/refinem/coverage.py", line 30, in
import pysam
ImportError: No module named pysam
