### ISSUE TITLE
checkm tree_qa: meaning of "Taxonomy (contained" and "Taxonomy (sister lineage)"

### ISSUE THREAD

**Issue by jvollme** [Ecogenomics/CheckM#55]
Hello,  
Running "checkm tree_qa" gives me information on the taxonomic placement of the bins. These include the values "Taxonomy (contained)" and "Taxonomy (sister lineage)". What exactly do these mean and what is the difference?

I assumed that "Taxonomy (contained)" indicates the most dominant lineage (where the majority of the detected markergenes are assigned to) and that "Taxonomy (sister lineage)" could indicate the second most dominant lineage. Therfore highly related taxons for "Taxonomy (contained)" and "Taxonomy (sister lineage)" would be a further indication for a relatively "clean" bin, while more unrelated taxons (etc "contained" = alphaproteobacteria and "sister lineage" = deltaproteobacteria) would indicate contamination. Is that correct?

However,  for some bins I have highly related Taxons for these values [e.g: "Taxonomy (contained)"= "f_Methylococcaceae" and "Taxonomy (sister lineage)" g_methylomonas"] but the selected Marker lineage was "k__Bacteria". Shouldn't the selected marker lineage have been [at least] Gammaproteobacteria in these cases [as happened for some other bins with the same "contained" and "sister lineage" Taxonomies]?

**Comment by dparks1134** [comment]
Hello,

Taxonomy (contained) indicates the most-specific named lineage in which you bin resides in the CheckM reference tree. Taxonomy (sister lineage) indicates the named lineage sister to where your bin is placed in the reference tree. For you example, bin it is contained within the lineage f__Methylococcaceae and is sister to g__Methylomonas. You can also dump a Newick file showing the exact placement of your bin if this is required.

There are at least 2 reasons bins with the same contained and sister taxonomies may be evaluated with different marker sets:
1) the current taxonomy (NCBI) does not perfectly follow the topology of the reference tree. As such, it is possible that the Methylococcaceae are polyphyletic which may explain why the bacterial marker set was used. CheckM always considers the phylogeny first and provides taxonomic labels simply for convenience. The next release of CheckM will use a taxonomy that has been curated to follow the topology of the reference tree.
2) more likely, these bins are simply placed on different branches in the reference tree. Your bin evaluated with the bacterial set may in fact reside several branches closer to the root then other bins even though it is still contained in the f_Methylococcaceae. CheckM uses a simulation strategy to decide the best marker set for each branch in the reference tree. The closer you get to the bacterial root the more likely the bacterial marker set will give the best performance even if a gammaproteobacterial marker set could be used. 

If you wish to evaluate all your bins with the same marker set (say, gammaproteobacterial), CheckM supports this through the "taxonomy_wf".

**Comment by jvollme** [comment]
OK thanks. So if I understand it right,  the sister lineage is simply the subbranch within the "contained" taxon that is closely related based on the markergenes in the bin, but which can NOT be unambiguously assigned to the bin. 

But what about the other extreme then. I have one bin that is "contained" within the Alphaproteobacteria but has the following "sister lineage": c__Deltaproteobacteria;o__Bdellovibrionales;f__Bdellovibrionaceae;g__Micavibrio;s__Micavibrio_aeruginosavorus.
How can it be "contained" within the alphaproteobacteria but then have a species within the deltaproteobacteria as a "sister lineage"?

**Comment by dparks1134** [comment]
It may help to take a look at the actual tree. You can export a Newick tree using the "tree_qa" command and see what taxonomy was assigned to different genomes. Currently, CheckM uses the NCBI taxonomy and it is not always congruent with the topology of the inferred genome tree (i.e., there may be multiple Alphaproteobacteria lineages). This has no impact of he CheckM estimates as these taxonomic labels are never considered, and are simply supplied in the output tables to help give a sense of where a genome was placed in the tree.

The g__Micavibrio is a Deltaproteobacteria according to NCBI. However, other sources indicate it is an  Alphaproteobacteria (e.g., MicrobeWiki: https://microbewiki.kenyon.edu/index.php/Micavibrio). Based on your results I would say the NCBI taxonomy is incorrect. We are working on putting together a taxonomy that is congruent with phylogeny which will resolve this sorts of discrepancies.

**Comment by jvollme** [comment]
Ok, thanks a lot! That clears everything up for me!
