### ISSUE TITLE
checkm data setRoot issue

### ISSUE THREAD

**Issue by upendrak** [Ecogenomics/CheckM#58]
Hi, i am currently dockerizing the CheckM tool so that i can integrate into our infrastructure (CyVerse). All of the steps mentioned in the installation worked except checkm data setRoot. Since i am docerkizing i am downloading the latest version of the checkm from the ftp site, untaring it and setting root like this

RUN mkdir CheckM && cd CheckM
RUN wget https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_v1.0.5.tar.gz
RUN tar xvf checkm_data_v1.0.5.tar.gz
RUN checkm data setRoot /CheckM

But i keep getting this prompt.. 

It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 

Am i doing something wrong?

**Comment by dparks1134** [comment]
Can you try entering the absolute path? I have a feeling this may be the issue (and obviously a bug!).

**Comment by upendrak** [comment]
Actually the ChecM is at the root directory and so that is the absolute path

**Comment by dparks1134** [comment]
Sorry for the delay.

The setRoot command does not take the desired directory as a parameter. Run <code>checkm data setRoot</code> and this will bring up an interactive prompt requesting the path you wish to set.

**Comment by upendrak** [comment]
Hi,

I can definitely do that and it worked as well. But the problem is i want to dockerize this tool and for that i cannot enter the path manually (since there won’t be any prompts during the process).

Thanks
Upendra

**Comment by dparks1134** [comment]
Hello Upendra,
I'm not familiar with Docker. Is the requirement that you be able to specify all installation scripts via a configuration file? If you can issue a command such as <code>RUN checkm data setRoot</code> can you follow this with <code>RUN /CheckM</code>?

I will make the setRoot prompt take an argument in the next release, but I don't expect to release this for a few  months.

**Comment by upendrak** [comment]
Hi,

Thanks for the hint but unfortunately it didn’t work while imaging the checkM docker image. I’m not sure how i can dockerize the checkM now.

Probably, i need to wait until the next release.

Thanks anyway for your help though.

Upendra

**Comment by dparks1134** [comment]
Hello Upendra,

This issue has been addressed in v1.0.6.

Cheers,
Donovan

**Comment by upendrak** [comment]
Great. Thanks Donovan. I will try it out...

**Comment by wwood** [comment]
Hi Donovan,

I got the same behaviour as previously i.e. 69aebb73 does not seem to fix it for me. I wonder, did you test it if there is a path set already that does not exist, like how checkm gets shipped? Just a random guess.

However, I was able to workaround this by modifying the contents of checkm/DATA_CONFIG directly so it installs fine in my (GNU Guix) container without having to resort to piping the answer in via STDIN.

Thanks,
ben

**Comment by upendrak** [comment]
Hi Donovan,

It looks like the issue has not been fixed as i am seeing the same behaviour as before. Here is a part of the dockerfile that i am trying to dockerize 

```
FROM ubuntu:14.04.3
RUN apt-get update && apt-get install -y wget python-pip libblas-dev liblapack-dev libatlas-base-dev gfortran unzip python-dev libfreetype6-dev libxft-dev
RUN pip install numpy
RUN pip install checkm-genome
RUN pip install pandas
RUN wget -O- https://github.com/Ecogenomics/CheckM/archive/v1.0.6.tar.gz | tar zxvf -
RUN cd /CheckM-1.0.6 && python setup.py build
RUN cp /CheckM-1.0.6/build/scripts-2.7/checkm /usr/bin
RUN checkm data setRoot /CheckM-1.0.6/
```
Here is the error that i am getting (which is same as before)

```
Step 10 : RUN wget -O- https://github.com/Ecogenomics/CheckM/archive/v1.0.6.tar.gz | tar zxvf -
 ---> Using cache
 ---> 5baebdee69b6
Step 11 : RUN cd /CheckM-1.0.6 && python setup.py build
 ---> Using cache
 ---> 58b17c0a131d
Step 12 : RUN cp /CheckM-1.0.6/build/scripts-2.7/checkm /usr/bin
 ---> Using cache
 ---> 30559554efc5
Step 13 : RUN checkm data setRoot /CheckM-1.0.6/
 ---> Running in e21d653af42e
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 36, in <module>
    from checkm import main
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/usr/local/lib/python2.7/dist-packages/checkm/defaultValues.py", line 26, in <module>
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying:
    class DefaultValues():
  File "/usr/local/lib/python2.7/dist-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/usr/local/lib/python2.7/dist-packages/checkm/checkmData.py", line 114, in __init__
    if not self.setRoot():
  File "/usr/local/lib/python2.7/dist-packages/checkm/checkmData.py", line 177, in setRoot
    path = self.confirmPath(path=path)
  File "/usr/local/lib/python2.7/dist-packages/checkm/checkmData.py", line 198, in confirmPath
    path = raw_input("Where should CheckM store it's data?\n" \
EOFError: EOF when reading a line
The command '/bin/sh -c checkm data setRoot /CheckM-1.0.6/' returned a non-zero code: 1
```
Thanks
Upendra

**Comment by housw** [comment]
in case someone is still looking for a solution, try this: 
```
RUN echo -e "cat << EOF\n/db/CheckM\nEOF\n" | checkm data setRoot
```

Cheers, 
Shengwei

**Comment by marchoeppner** [comment]
Thanks for that work-around, but I really feel that the tool should accept the path from the command line. We are also deploying checkm automatically with a container and it simply isn't an option to have an interactive dialogue. So please consider adding the option of adding a path; especially since this is the only thing ghr dialogue does.
