### ISSUE TITLE
Make pplacer installation more precise

### ISSUE THREAD

**Issue by matsen** [Ecogenomics/CheckM#61]
Hello Donovan--

We're getting a lot of users using pplacer through CheckM. This is great!

Though, I think that they could use [some more direction](https://github.com/matsen/pplacer/issues/349#issuecomment-216108623). Could you point them to the binaries, and perhaps tell them how to put them somewhere that CheckM can find them?

(I still have your issues on my todo list-- I haven't forgotten!)

**Comment by dparks1134** [comment]
Hello Frederick,

I have updated the CheckM installation instructions to point directly to the pplacer binaries and to link to instructions about modify the Linux path:
https://github.com/Ecogenomics/CheckM/wiki/Installation

If you think there is anything else that can be done to help with installation, please let me know. 

Cheers,
Donovan

**Comment by matsen** [comment]
Thanks!
