### ISSUE TITLE
Problems during installaion

### ISSUE THREAD

**Issue by Lily-WL** [Ecogenomics/CheckM#62]
Dear Sir,

When I installed the CheckM using : pip install checkm-genome, a error was feedback. I am a little confused to the source of the error. Can you help to solve it?
 Thank you !

The error is as following.

_Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2aB03d/matplotlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-25plg5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2aB03d/matplotlib/_

**Comment by dparks1134** [comment]
Hello,
The error relates to matplotlib which is one of CheckM's dependencies. You might have better success if you install numpy, scipy, and matplotlib independently first. You can find information of this at:
https://www.scipy.org/install.html

Cheers,
Donovan

**Comment by Lily-WL** [comment]
Thank you for your reply. The problem was solved and all the required modules were set up. It maybe because of the miss of gcc-c++.

But when I excuted "**checkm data update**", some feedback came out. Is it matter? The details were as follows.

**[root@student ~]# checkm data update**

*******************************************************************************
 [CheckM - data] Check for database updates. [update]
*******************************************************************************

Connecting to ACE server.

****************************************************************
0 new file(s) to be downloaded from source
1 existing file(s) to be updated
1.21 GB will need to be downloaded
Confirm you want to download this data
Changes *WILL* be permanent
Continue? (y,n) : y
****************************************************************
(re) creating manifest file (please be patient)
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x2a84fd0: '1'>), ('0', <StateIdentity at 0x2a9d090: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x2a84fd0: '1'>), ('0', <StateIdentity at 0x2a9d090: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x2a84fd0: '1'>), (1, <StateIdentity at 0x2a9d090: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by dparks1134** [comment]
Hello,

This appears to be an issue with Dendropy. Can you check what version you have on your system.

Cheers,
Donovan

**Comment by Lily-WL** [comment]
The version is DendroPy 4.1.0. Seems the details of DendroPy also have some problems. 

**[root@student ~]# python -m dendropy**
DendroPy version      : DendroPy 4.1.0
DendroPy location     : /usr/local/lib/python2.7/site-packages/dendropy
Python version        : 2.7 (r27:82500, Apr 29 2016, 10:17:23) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
Python executable     : /usr/local/bin/python
Python site packages  : ['/usr/local/lib/python2.7/site-packages', '/usr/local/lib/site-python']
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1718490: '1'>), ('0', <StateIdentity at 0x17184d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1718490: '1'>), ('0', <StateIdentity at 0x17184d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x1718490: '1'>), (1, <StateIdentity at 0x17184d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by dparks1134** [comment]
Hello. It does appear to be something wrong with either your installation of Dendropy or perhaps a bug in Dendropy 4.1.0. Can you ask the Dendropy authors about this:
https://github.com/jeetsukumaran/DendroPy/issues

**Comment by Lily-WL** [comment]
I already solved it by updated the version of Python. Thanks!
