### ISSUE TITLE
Interactive dialogues, checkm data update, setRoot

### ISSUE THREAD

**Issue by mherold1** [Ecogenomics/CheckM#63]
Hello,

after I installed checkm, I manually downloaded the data files and did:
`checkm data setRoot checkm_data/`
When I do this I get 2 dialogues:
"It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
Where should CheckM store it's data?"
and then the same thing again for setRoot

Is it possible to do setRoot without having interactive dialogues appear? 

edit: probably already solved in the latest code on git (or version 1.0.6) , which hadn't been installed using pip install 

edit2: Also in the latest version the dialogue above appears when I run `checkm data setRoot dir/`
Even when I type abort it will still set the data directory to dir/ 

edit3:
this worked:
`echo checkm_data_v1.0.6 | checkm data setRoot checkm_data_v1.0.6/`

and sorry that I overlooked https://github.com/Ecogenomics/CheckM/issues/58 which is basically the same issue

**Comment by dparks1134** [comment]
This does still seem to be an open issue, but I am looking to address it when I can find time.

**Comment by jfroula** [comment]
This still seems to be an issue with CheckM v1.0.7
