### ISSUE TITLE
Error during the useage of "coverage" command

### ISSUE THREAD

**Issue by Lily-WL** [Ecogenomics/CheckM#64]
**### Dear Sir,**

### I used the command "checkm coverage" , but a error was feedbacked.
_" **_checkm coverage contig-94-metabat-bins coverage.tsv contig-94-idba5.bam -x fa -t 16_** 
.....................
_[Error] BAM file is either unsorted or not indexed: contig-94-idba5.bam"__

### However, the input bam in transfer from the output *.sam of BWA. And the index was pu in the same folder. As follows:
_"-rw-r--r--. 1 nfsnobody nfsnobody  1276097189 5? 23 18:20 contig-94.fa
-rw-r--r--. 1 nfsnobody nfsnobody          21 5? 23 19:24 contig-94-idba5.amb
-rw-r--r--. 1 nfsnobody nfsnobody    72934382 5? 23 19:24 contig-94-idba5.ann
-rw-r--r--. 1 nfsnobody nfsnobody 21805539458 5? 24 18:28 contig-94-idba5-bwa.bam
-rw-r--r--. 1 nfsnobody nfsnobody 77630480542 5? 23 20:32 contig-94-idba5-bwa.sam
-rw-r--r--. 1 nfsnobody nfsnobody  1223570936 5? 23 19:23 contig-94-idba5.bwt
-rw-r--r--. 1 nfsnobody nfsnobody   305892713 5? 23 19:24 contig-94-idba5.pac
-rw-r--r--. 1 nfsnobody nfsnobody   611785472 5? 23 19:32 contig-94-idba5.sa
drwxr-xr-x. 2 nfsnobody nfsnobody       20480 5? 26 17:31 contig-94-metabat-bins
"_

### How can I solved with it?

Thank you for your time.

**Comment by dparks1134** [comment]
Hello,

The <code>coverage</code> command requires an indexed BAM file. Indexed BAM files have an associated *.bam.bai file. This file needs to be in the same folder as the *.bam file. Samtools can be used to index a BAM file.

Cheers,
Donovan

**Comment by dparks1134** [comment]
Closed due to inactivity.
