### ISSUE TITLE
species name not 

### ISSUE THREAD

**Issue by igsbma** [Ecogenomics/CheckM#67]
If I want to run a species name, for example, 

>checkm taxonomy_wf species Escherichia coli ... 

It won't allow because "Escherichia coli" is two words. What should I do for species? thanks!

Big

**Comment by dparks1134** [comment]
You can put the species name in quotes:
<code>checkm taxonomy_wf species "Escherichia coli" ...</code>

**Comment by igsbma** [comment]
Does not seem working...shown as "unrecognized arguments"...

$ checkm taxon_list --rank species "Gardnerella vaginalis"
usage: checkm taxon_list [-h]
                         [--rank {ALL,life,domain,phylum,class,order,family,genus,species}]
                         [--tmpdir TMPDIR]
checkm taxon_list: error: unrecognized arguments: Gardnerella vaginalis
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x14ad0b90: '1'>), ('0', <StateIdentity at 0x14ad0bd0: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x14ad0b90: '1'>), ('0', <StateIdentity at 0x14ad0bd0: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x14ad0b90: '1'>), (1, <StateIdentity at 0x14ad0bd0: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by dparks1134** [comment]
Closed due to inactivity.

**Comment by dparks1134** [comment]
Hello,

The "taxon_list" command just requires a rank: checkm taxon_list --rank
species. This will list all species recognized by CheckM. You can then use
known species in the "taxonomy_wf" command.

Cheers,
Donovan
