### ISSUE TITLE
To validate which genomic bins are to be merged

### ISSUE THREAD

**Issue by minsookim1983** [Ecogenomics/CheckM#73]
Hello, 

I am trying to figure out genomic bins to be merged. 

I got first the 'merge' file that suggests which genomic bins look similar on the basis of common set of taxonomic marker genes (taxon_set). 

Next, I am trying to compare lineage positions of genomic bins in the reference genome tree, as suggested in 'merge' description. In this step, should I check all lineage positions manually, one by one, using a newick-format phylogenetic tree file? Or, is it safe that the genomic bins with the same UID numbers are regarded as to the genomic bins in the same lineage position?

Please, give me any hint how to judge the similar locations within the reference tree to be merged.

Min-Soo Kim

**Comment by dparks1134** [comment]
Hello,

I generally inspect the positions manually by visualizing the tree in
Dendroscope. The UIDs can be for a very basal node so don't necessarily
indicate the bins are closely positioned in the tree.

Cheers,
Donovan

**Comment by minsookim1983** [comment]
Thank you for your comment.

Min-Soo Kim
