### ISSUE TITLE
taxonomy_wf bugs

### ISSUE THREAD

**Issue by ctSkennerton** [Ecogenomics/CheckM#77]
using the `taxon_list` subcommand shows that there is a rank "life" which would be for markers from both bacteria and archaea but it cannot be accessed from the `taxonomy_wf` subcommand. I get the error:

```
checkm taxonomy_wf: error: argument rank: invalid choice: 'life' (choose from 'domain', 'phylum', 'class', 'order', 'family', 'genus', 'species')
```

**Comment by dparks1134** [comment]
Fixed in CheckM v1.0.9.
