### ISSUE TITLE
Can't find prodigal  on system path

### ISSUE THREAD

**Issue by LovelornPig** [Ecogenomics/CheckM#79]
First, I use virtualenv to active a python2 environment and install checkm by pip.

Then I create a scrtpt  checkm_metaotu.sh :  
      source  /share/backup/zhujie/software/checkm/activate
      checkm lineage_wf -t 8 -x fa /share/backup/zhujie/biodata/checkm_input_metaotu 
 /share/backup/zhujie/biodata/checkm_output_metaotu > checkm_metaotu.log 2>&1

Then I create a qsub script  qsub_checkm_metaotu.sh:
      qsub -cwd -q st.q -l vf=20G,p=8 check_metaotu.sh &

But when I run: ./qsub_checkm_metaotu.sh
I got a error in the checkm_metaotu.log:
     *******************************************************
      [CheckM - tree] Placing bins in reference genome tree.
     *******************************************************
      [Error] Make sure prodigal is on your system path.
      Controlled exit resulting from an unrecoverable error or warning.

In fact, I already added prodigal path to my ~/.bashrc and source it.
So, I really want to know what I did wrong.
Please hele me, thanks very much:)

**Comment by dparks1134** [comment]
I can't say I follow everything you have done, but I would take the error message at face value. Are you sure prodigal and an executable called <code>prodigal</code> is on your path even in the qsub environment?

**Comment by LovelornPig** [comment]
Yes, when I add -V parameter to the qsub_checkm_metaotu.sh, there is no more error.
Thanks very much!  👍 💯 :)
