### ISSUE TITLE
problem with pfam.hmm formatting?

### ISSUE THREAD

**Issue by jfroula** [Ecogenomics/CheckM#8]
I think I'm having issue with the pfam format of the "phyla.hmm" file that was created by 

> checkm data update
> however, it could be something else.  As a test, I tried the lineage_wf command with the ecoli genome you supplied in test_data.  Please see errors below.  Thanks.
### what I did to install and test checkm lineage_wf
# installing with pip

> pip install numpy
> pip install checkm-genome
> ./bin/checkm data update 
>     I typed "DATA" to save data in
# I added prodigal, hmmer, and pplacer to PATH
# test installation with test data (ecoli)

> ./bin/checkm lineage_wf DATA/test_data/ Results 
### The output was

---

 [CheckM - tree] Placing bins in reference genome tree.

---

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.

Error: Unrecognized format, trying to open hmm file /global/projectb/scratch/jfroula/965c9772-6a8a-48d3-9b67-a5a541d84085 for reading.

```
Finished processing 1 of 1 (100.00%) bins.
```

  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.
Process Process-4:
Traceback (most recent call last):
  File "/usr/common/usg/languages/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/common/usg/languages/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/binStatistics.py", line 113, in __processBin
    codingDensity, translationTable, numORFs = self.calculateCodingDensity(binDir, genomeSize, scaffoldStats)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/binStatistics.py", line 229, in calculateCodingDensity
    codingBasePairs = self.__calculateCodingBases(aaGenes, seqStats)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/binStatistics.py", line 240, in __calculateCodingBases
    seqStats[scaffoldId]['# ORFs'] = seqStats[scaffoldId].get('# ORFs', 0) + 1
KeyError: 'AC_000091_1'

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[Errno 2] No such file or directory: 'Results/bins/637000110/hmmer.tree.txt'

  Extracting 43 HMMs with 1 threads:
    Finished extracting 0 of 43 (0.00%) HMMs.

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 1 of 43 (2.33%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 2 of 43 (4.65%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 3 of 43 (6.98%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 4 of 43 (9.30%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 5 of 43 (11.63%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 6 of 43 (13.95%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 7 of 43 (16.28%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 8 of 43 (18.60%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 9 of 43 (20.93%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 10 of 43 (23.26%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 11 of 43 (25.58%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 12 of 43 (27.91%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 13 of 43 (30.23%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 14 of 43 (32.56%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 15 of 43 (34.88%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 16 of 43 (37.21%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 17 of 43 (39.53%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 18 of 43 (41.86%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 19 of 43 (44.19%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 20 of 43 (46.51%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 21 of 43 (48.84%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 22 of 43 (51.16%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 23 of 43 (53.49%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 24 of 43 (55.81%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 25 of 43 (58.14%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 26 of 43 (60.47%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 27 of 43 (62.79%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 28 of 43 (65.12%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 29 of 43 (67.44%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 30 of 43 (69.77%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 31 of 43 (72.09%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 32 of 43 (74.42%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 33 of 43 (76.74%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 34 of 43 (79.07%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 35 of 43 (81.40%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 36 of 43 (83.72%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 37 of 43 (86.05%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 38 of 43 (88.37%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 39 of 43 (90.70%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 40 of 43 (93.02%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 41 of 43 (95.35%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 42 of 43 (97.67%) HMMs.
```

Error: File /global/scratch2/sd/jfroula/CheckM/git/CheckM/DATA/hmms/phylo.hmm does not appear to be in a recognized HMM format.

```
Finished extracting 43 of 43 (100.00%) HMMs.
```

  Aligning 43 marker genes with 1 threads:
    Finished aligning 0 of 43 (0.00%) marker genes.
    Finished aligning 1 of 43 (2.33%) marker genes.
    Finished aligning 2 of 43 (4.65%) marker genes.
    Finished aligning 3 of 43 (6.98%) marker genes.
    Finished aligning 4 of 43 (9.30%) marker genes.
    Finished aligning 5 of 43 (11.63%) marker genes.
    Finished aligning 6 of 43 (13.95%) marker genes.
    Finished aligning 7 of 43 (16.28%) marker genes.
    Finished aligning 8 of 43 (18.60%) marker genes.
    Finished aligning 9 of 43 (20.93%) marker genes.
    Finished aligning 10 of 43 (23.26%) marker genes.
    Finished aligning 11 of 43 (25.58%) marker genes.
    Finished aligning 12 of 43 (27.91%) marker genes.
    Finished aligning 13 of 43 (30.23%) marker genes.
    Finished aligning 14 of 43 (32.56%) marker genes.
    Finished aligning 15 of 43 (34.88%) marker genes.
    Finished aligning 16 of 43 (37.21%) marker genes.
    Finished aligning 17 of 43 (39.53%) marker genes.
    Finished aligning 18 of 43 (41.86%) marker genes.
    Finished aligning 19 of 43 (44.19%) marker genes.
    Finished aligning 20 of 43 (46.51%) marker genes.
    Finished aligning 21 of 43 (48.84%) marker genes.
    Finished aligning 22 of 43 (51.16%) marker genes.
    Finished aligning 23 of 43 (53.49%) marker genes.
    Finished aligning 24 of 43 (55.81%) marker genes.
    Finished aligning 25 of 43 (58.14%) marker genes.
    Finished aligning 26 of 43 (60.47%) marker genes.
    Finished aligning 27 of 43 (62.79%) marker genes.
    Finished aligning 28 of 43 (65.12%) marker genes.
    Finished aligning 29 of 43 (67.44%) marker genes.
    Finished aligning 30 of 43 (69.77%) marker genes.
    Finished aligning 31 of 43 (72.09%) marker genes.
    Finished aligning 32 of 43 (74.42%) marker genes.
    Finished aligning 33 of 43 (76.74%) marker genes.
    Finished aligning 34 of 43 (79.07%) marker genes.
    Finished aligning 35 of 43 (81.40%) marker genes.
    Finished aligning 36 of 43 (83.72%) marker genes.
    Finished aligning 37 of 43 (86.05%) marker genes.
    Finished aligning 38 of 43 (88.37%) marker genes.
    Finished aligning 39 of 43 (90.70%) marker genes.
    Finished aligning 40 of 43 (93.02%) marker genes.
    Finished aligning 41 of 43 (95.35%) marker genes.
    Finished aligning 42 of 43 (97.67%) marker genes.
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
Uncaught exception: Sys_error("Results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("Results/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:00:28.930 || Total: 0:00:28.930 }

---

 [CheckM - lineage_set] Inferring lineage-specific marker sets.

---

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

Unexpected error: <type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "./bin/checkm", line 646, in <module>
    checkmParser.parseOptions(args)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/main.py", line 1159, in parseOptions
    self.lineageSet(options)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/main.py", line 209, in lineageSet
    DefaultValues.HMMER_TABLE_PHYLO_OUT)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/resultsParser.py", line 64, in analyseResults
    self.parseBinHits(outDir, hmmTableFile, bSkipOrfCorrection, bIgnoreThresholds, evalueThreshold, lengthThreshold, binStats, seqStats)
  File "/global/scratch2/sd/jfroula/CheckM/git/CheckM/checkm/resultsParser.py", line 97, in parseBinHits
    resultsManager = ResultsManager(binId, self.models[binId], bIgnoreThresholds, evalueThreshold, lengthThreshold, binStats[binId], seqStats[binId])
KeyError: '637000110'

**Comment by jmwhitha** [comment]
I think I'm having a similar problem. Please help.

checkm lineage_wf -f ./CheckM.txt -t 12 -x fa ./ ./94444

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 42 bins with 12 threads:
Process Process-10:sing 0 of 42 (0.00%) bins.
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 318, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 418, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/usr/local/metabat/MetaBatbinning/checkMDATA/hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 42 bins with 12 threads:
    Finished processing 42 of 42 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1244, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/usr/local/lib/python2.7/dist-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1205, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'

**Comment by Xiaojun928** [comment]
As you discussed above,  HMMER >=3.1b1 works, but in my case, I installed HMMER 3.1b2 and added prodigal, hmmer, and pplacer to PATH. I got the same error like @jfroula 
My version of CheckM is v1.0.11
Could you please do me some help? Many thanks.

`~/anaconda2/bin/checkm lineage_wf ./test_data/ Results`

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.
Error: Unrecognized format, trying to open hmm file /tmp/0a97cb01-5f8f-4574-b3ac-ce4ceff69da6 for reading.

    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
[Errno 2] No such file or directory: 'Results/bins/637000110/hmmer.tree.txt'

  Extracting 43 HMMs with 1 threads:
    Finished extracting 0 of 43 (0.00%) HMMs.
Error: File /home-user/xjwang/software/checkm_data_2015_01_16/hmms/phylo.hmm does not appear to be in a recognized HMM format.

    Finished extracting 1 of 43 (2.33%) HMMs.
Error: File /home-user/xjwang/software/checkm_data_2015_01_16/hmms/phylo.hmm does not appear to be in a recognized HMM format.
                      ... ...
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  No genomes were identified that could be placed in the reference genome tree.

  { Current stage: 0:00:18.546 || Total: 0:00:18.546 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
[Errno 2] No such file or directory: 'Results/bins/637000110/hmmer.tree.txt'


  Determining marker sets for each genome bin.
    Finished processing 1 of 1 (100.00%) bins (current: 637000110).

  Marker set written to: Results/lineage.ms

  { Current stage: 0:00:00.812 || Total: 0:00:19.358 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 0 of 1 (0.00%) bins.
Error: File /home-user/xjwang/software/checkm_data_2015_01_16/hmms/checkm.hmm does not appear to be in a recognized HMM format.


Error: File /tmp/6ebe369b-e9a1-40fb-a026-4e9877277cd2 does not appear to be in a recognized HMM format.


Error: Unrecognized format, trying to open hmm file /tmp/6ebe369b-e9a1-40fb-a026-4e9877277cd2 for reading.

    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:00:00.435 || Total: 0:00:19.794 }

  Parsing HMM hits to marker genes:
[Errno 2] No such file or directory: 'Results/bins/637000110/hmmer.analyze.txt'

  Aligning marker genes with multiple hits in a single bin:
    Finished processing 1 of 1 (100.00%) bins.

  { Current stage: 0:00:00.053 || Total: 0:00:19.847 }

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  { Current stage: 0:00:00.210 || Total: 0:00:20.058 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
[Errno 2] No such file or directory: 'Results/bins/637000110/hmmer.analyze.txt'


------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id      Marker lineage   # genomes   # markers   # marker sets   0    1   2   3   4   5+   Completeness   Contamination   Strain heterogeneity  
------------------------------------------------------------------------------------------------------------------------------------------------------
  637000110    root (UID1)        5656         56            24        56   0   0   0   0   0        0.00            0.00               0.00          
------------------------------------------------------------------------------------------------------------------------------------------------------

  { Current stage: 0:00:00.006 || Total: 0:00:20.064 }

**Comment by dparks1134** [comment]
Hello. I'm not sure what the issue is. I can confirm that we are using HMMER 3.1b2 on our machines with CheckM and it works without issue. Can you confirm that hmmsearch v3.1b2 is the active version on your path. You can check the version with "hmmsearch -h".

You could also try re-indexing the phylo.hmm file:
>hmmfetch --index phylo.hmm

This is at /home-user/xjwang/software/checkm_data_2015_01_16/hmms/ on your system. I don't think this is the issue, but worth a try.

**Comment by Xiaojun928** [comment]
It is my fault to miss an older version of HMMER. As you guessed, v3.1b2 is not active one. After I replace the old version, CheckM works!  Thanks a lot~
