### ISSUE TITLE
killed test...running out of memory?

### ISSUE THREAD

**Issue by UCSBMicrobiologyCore** [Ecogenomics/CheckM#81]
Hi all;

I've just finished installing CHeckM and while I was trying to run the ecoli test results, I get the error below...is this an issue of me running out of memory? I tried on my actual dataset as well with the reduced tree tag, and I'm getting something very similar though I have 16G of RAM. 

thanks in advance

jon@jon-desktop:~$ checkm test ~/checkm_test_results

*******************************************************************************
[CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
*******************************************************************************

[Step 1]: Verifying tree command.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("/home/jon/checkm_test_results/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/home/jon/checkm_test_results/results/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:20:42.922 || Total: 0:20:42.922 }

  [Passed]

[Step 2]: Verifying tree_qa command.

*******************************************************************************
 [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/home/jon/.local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/main.py", line 1311, in parseOptions
    self.test(options)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/main.py", line 1198, in test
    verifyEcoli.run(self, options.output_dir)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/test/test_ecoli.py", line 76, in run
    parser.treeQA(options)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/main.py", line 190, in treeQA
    treeParser.printSummary(options.out_format, options.tree_folder, RP, options.bTabTable, options.file, binStats)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/treeParser.py", line 633, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/treeParser.py", line 191, in getBinTaxonomy
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/home/jon/.local/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/home/jon/.local/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/home/jon/checkm_test_results/results/storage/tree/concatenated.tre'

**Comment by dparks1134** [comment]
With default settings, CheckM requires around 40GB of memory. You can run it on 16GB using the <code>--reduced_tree</code> flag. See the wiki for more details:

https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

**Comment by UCSBMicrobiologyCore** [comment]
Hi Dr. Parks, thanks for the quick reply. When I run reduced tree, I still get a similar output...any ideas?:

 checkm lineage_wf --reduced_tree -x fasta /home/jon/Desktop/bins_2500bp_filtered_18cm_SS /home/jon/Desktop/CheckMout

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 37 bins with 1 threads:
    Finished processing 37 of 37 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 37 bins with 1 threads:
    Finished processing 37 of 37 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 37 of 37 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 37 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("/home/jon/Desktop/CheckMout/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/home/jon/Desktop/CheckMout/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:08:25.662 || Total: 0:08:25.662 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 37 of 37 (100.00%) bins.

  Determining marker sets for each genome bin.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/home/jon/.local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/main.py", line 1245, in parseOptions
    self.lineageSet(options)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/main.py", line 230, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/home/jon/.local/lib/python2.7/site-packages/checkm/treeParser.py", line 477, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/home/jon/.local/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/home/jon/.local/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/home/jon/Desktop/CheckMout/storage/tree/concatenated.tre'

**Comment by dparks1134** [comment]
It appears you are still running out of memory. What OS are you running? If possible, can you verify that you are indeed running out of memory and let me know. I believe that reduced tree should take around 14GB so make sure you don't have anything else substantial being run at the same time.

**Comment by UCSBMicrobiologyCore** [comment]
I'm currently running it on Ubuntu--I just wanted to confirm my commands were correct and it wasn't some other issue besides memory. I'll try and figure it out. thanks!!

**Comment by UCSBMicrobiologyCore** [comment]
used the campus cluster and it was fine...definitely an issue of memory and nothing else thank you for your help!
