### ISSUE TITLE
Empty files "appear to contain nucleotide sequences"

### ISSUE THREAD

**Issue by MrOlm** [Ecogenomics/CheckM#83]
When running the checkM analyze command with the --genes option, if it encounters an empty file it asks:

File XXX appears to contain nucleotide sequences.
Do all files contain only amino acid sequences? [y/N]

Instead of just continuing on like normal.

**Comment by dparks1134** [comment]
Hello,

Thank you for reporting this. I will address  it in the next release of CheckM.

Cheers,
Donovan
