### ISSUE TITLE
checkm outlier errorr Missing gene feature files 

### ISSUE THREAD

**Issue by kshitij1990** [Ecogenomics/CheckM#84]
Hi Everyone,

I am trying to identify the outliers from my bins. For this purpose I am using checkm outliers command but it fails every time with the below error.
**[Error] Missing gene feature files (genes.gff). This plot if not compatible with the --genes option**.

Could anyone please and guide me in order to fix this error

**Comment by dparks1134** [comment]
Hello,

The example for running this command was out of date. The second parameter needs to be the directory created by the lineage_wf (or taxonomy_wf) command:

checkm outliers ./output ./bins tetra.tsv outliers.tsv

Cheers,
Donovan

**Comment by Handymanalan** [comment]
Hi Donovan,

I tried this command (checkm outliers ./output ./bins tetra.tsv outliers.tsv) but it gives me this error message:
**[Error] No bins found. Check the extension (-x) used to identify bins.**

Then I tried "checkm outliers ./output ./bins -x fasta tetra.tsv outliers.tsv"
**[Error] Missing gene feature files (genes.gff). This plot if not compatible with the --genes option.**

The files are all in the folder generated by the lineage_wf command.

Could anyone please help me with this error?

Cheers and many thanks

Alan

**Comment by dparks1134** [comment]
Hello Alan,

Did you have GFF files for all your bins? These are generated by Prodigal when you run the lineage_wf command without using the "--genes" option (i.e. allow CheckM via Prodigal to call genes).

You may wish to look at RefineM if you are aiming to improve your bins:
https://github.com/dparks1134/RefineM

Cheers,
Donovan

**Comment by Handymanalan** [comment]
Yes I have the gff files in the same folder. Thanks for the advise I will check out RefineM.

Cheers

Alan
