### ISSUE TITLE
Output redirection doesn't work

### ISSUE THREAD

**Issue by adityabandla** [Ecogenomics/CheckM#88]
Hi,

I have been trying to use the lineage_wf function to profile my bins. I have been trying to redirect the console output to a text file using the '-f' flag, however it doesn't seem to be working and the output is still displayed on stdout

If the command is delegated to the background, checkm seems to get stuck after finishing one module, for example after placing bins on the tree, it does not proceed to the next step. I assume this would be due to its inability to record the stdout?

**Comment by dparks1134** [comment]
Are results written to the file your specified with the <code>-f</code> flag? This flag indicates results should be written to a file. It does not suppress all output produced by CheckM (i.e., status and progress information). You can suppress all output using the <code>--quiet</code> flag.
