### ISSUE TITLE
Checkm detects twice the number of bins in input folder

### ISSUE THREAD

**Issue by adityabandla** [Ecogenomics/CheckM#89]
Hi,

I am evaluating the bins generated by Metabat using checkm. Metabat reported a total of 794 clusters/bins with each bin written as a separate fasta file. Thus, I had a total of 794 fasta files in my input folder. However, when checkm is invoked, it detects 1588 bins (794 x2). 

I am not sure what is causing this. Any help would be much appreciated

**Comment by dparks1134** [comment]
By default, CheckM will process files with a <code>fna</code> extension. You can chance this using the <code>-x</code> flag.

**Comment by adityabandla** [comment]
Hi Donovan

Thanks for the quick reply! Sorry, I forgot to mention, I did use the -x flag to detect fasta files instead of fna

**Comment by dparks1134** [comment]
Just to double check, the output of <code>ls /path/to/folder | wc -l</code> is 794? If so, can you send me the command you are running along with the output produced by CheckM.

**Comment by adityabandla** [comment]
Yes, its 794. Following is the command that I ran

checkm lineage_wf -x fa $HOME/Assembly_Composite/bins/ $HOME/Assembly_Composite/bins/scg --pplacer_threads 22 -t 22 --tab_table --tmpdir ./checkm/ 2>&1 | tee $HOME/Assembly_Composite/checkm.txt 

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************
Identifying marker genes in 1588 bins with 22 threads:

CheckM does go onto complete the task, although with this discrepancy

**Comment by dparks1134** [comment]
Everything looks correct to me. What version of CheckM are you running? What is the error message produced when CheckM crashes?

**Comment by adityabandla** [comment]
My apologies. In fact, it seems like a bug in Metabat. There seem to be a number of hidden fasta files in the directory specified for the final Metabat bins. The numbers now add up and checkm just seems to be detecting all fasta files (hidden as well as visible).

I am not sure what causes this. Have posted this issue in the Metabat discussion thread.

**Comment by dparks1134** [comment]
Good to know. Thank you for letting me know what the issue was.
