### ISSUE TITLE
checkm qa output format 8 adds number to contigs

### ISSUE THREAD

**Issue by jolespin** [Ecogenomics/CheckM#92]
I'm using `CheckM v1.0.5`.  Below is a screenshot of my issue.  I am trying to figure out which maker hmms are in which contig and the position in which they occur.  For example, `PF00380` appear to occur twice on contig `NODE_841_length_39292_cov_1.25158_ID_1681` but one has a `_5` appended to it and the other has a `_17` appended to it.  What are these numbers?  Is `PF00380.14,15,136` the position in which occurs in the contig? I thought that's what it was but it is the same number for both instances. 

![screen shot 2017-01-19 at 4 22 12 pm](https://cloud.githubusercontent.com/assets/9061708/22130855/cb382f2a-de63-11e6-96d2-f2cfde4fcc6a.png)

**Comment by dparks1134** [comment]
Hello,

Thank you for the question.The reported start and end positions are the position on the gene, not the contig. The <code>_5</code> and <code>_17</code> are the gene numbers. The called genes can be found in <code>./<checkm_output_dir/bins/<bin_id></code>. The information associated with each gene in this file does indicate its position on the contig. You can also find the full results of the HMM search in this directory. 

Output table 9 can produce a FASTA file with all identified marker genes if this is helpful.

Cheers,
Donovan

**Comment by jolespin** [comment]
Thanks a lot Donovan, this really does help.  Just to be clear, in line 2014 above `PF00380.14,15,136` means it's on open reading frame `NODE_841_length_39292_cov_1.25158_ID_1681_5` where the domain hits between position `15` and `136`?

**Comment by dparks1134** [comment]
Yep!
