### ISSUE TITLE
Issue running lineage_wf

### ISSUE THREAD

**Issue by Mbray32** [Ecogenomics/CheckM#94]
Hi I'm trying to run the lineage_wf script. My input is a folder on my desktop with a fasta file in it and my output if a folder called 'checkm' in my home directory.

This is what it looks like:

 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
sh: line 1: 21993 Killed                  pplacer -j 1 -c /usr/local/packages/checkmdata/genome_tree/genome_tree_full.refpkg -o /nethome/mbray32/checkm/storage/tree/concatenated.pplacer.json /nethome/mbray32/checkm/storage/tree/concatenated.fasta > /nethome/mbray32/checkm/storage/tree/pplacer.out
Uncaught exception: Sys_error("/nethome/mbray32/checkm/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/nethome/mbray32/checkm/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:03:27.511 || Total: 0:03:27.511 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

  Determining marker sets for each genome bin.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/usr/local/packages/anaconda2/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 1245, in parseOptions
    self.lineageSet(options)
  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 230, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/checkm/treeParser.py", line 477, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/usr/local/packages/anaconda2/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/nethome/mbray32/checkm/storage/tree/concatenated.tre'

**Comment by dparks1134** [comment]
Hello,

My best guess is that you are running out of memory on your system and this is causing  pplacer to crash. Can you please check the following:
- that you are not running out of memory (CheckM requires 40GB of RAM to run the full lineage_wf; if you only have 16GB of RAM you can run the reduced lineage_wf with the --reduced_tree flag):
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
- that you are using CheckM >= v1.0.5 (checkm -h)
- that pplacer is on your system path (pplacer -h)
- that the following file exists on your system (/usr/local/packages/checkmdata/genome_tree/genome_tree_full.refpkg)

Cheers,
Donovan
