### ISSUE TITLE
workflow for manually updating checkm databases 

### ISSUE THREAD

**Issue by jvollme** [Ecogenomics/CheckM#99]
Hi, I noticed that the last updates to the checkM_databases seem to have been 2015.

Are updatesof these databases planned in the near future? Or (even better) would it be possible/feasible to create a documented workflow that would allow users to locally update these database themselves (possibly based on the NCBI refseq database)?

I would imagine that the new genomes that have been added since 2015 may greatly influence the choice of lineage specific marker genes for several previously under-represented taxa.

**Comment by dparks1134** [comment]
Hello. I am actively working on updating the CheckM database and software though this is still several months away. The existing CheckM database was purposely restricted to only high-quality isolate genomes. The vast increase in the number of available genomes and the reality that under-represented taxa are largely being flushed out with uncultivated-genomes of varying quality has made a straight-forward update of the database challenging.

**Comment by jvollme** [comment]
Thats understandable, thanks. Looking forward to the update then sometime in the future.
